//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class LyricProtocol, NSString, SongInfo;


@interface LyricManager : NSObject
{
    SongInfo *song;
    LyricProtocol *lyricProtocol;
    id leader;
}

+ (id)decodeQrcFileWithContent:(id)arg1;//arg data of file,ret decoded QRC.
+ (id)decodeQrcFileWithPath:(id)arg1;
+ (int)hexStringToString:(const char *)arg1 stringLength:(int)arg2 toString:(char *)arg3;
+ (id)decodeDes:(const void *)arg1 size:(long)arg2;
+ (id)getQrcTextFromXml:(id)arg1;//ret qrc
+ (id)getQrcFilePathByLyricFilePath:(id)arg1;
+ (id)getID3VersionLyricFilePath:(id)arg1 isQrc:(BOOL)arg2;
+ (id)getYInyiLyricFilePath:(id)arg1;
+ (id)getTranslateLyricFilePath:(id)arg1;//arg1:Type:SongInfo Content:{歌曲信息描述 id:8325958166907185731,
//name:Follow Me,
//flacsize:0,
//topsize:-1,
//isGososoSong:0,
//hasCopyright:1}
+ (id)getLyricFilePath:(id)arg1 isQrc:(BOOL)arg2;
+ (id)sharedLyricManager;
//@property(nonatomic) __weak id leader; // @synthesize leader;
@property(retain, nonatomic) LyricProtocol *lyricProtocol; // @synthesize lyricProtocol;
@property(readonly, nonatomic) SongInfo *song; // @synthesize song;
- (BOOL)getIsUseQrc;
- (void)onFingerPrintStatusChange:(id)arg1 fingerPrintStatus:(int)arg2 lyric:(id)arg3 SongId:(long long)arg4 lyricType:(int)arg5;
- (void)dealloc;
- (id)parseOfSong:(id)arg1 withLyric:(id)arg2 withTransLateLyric:(id)arg3 withYinyiLyric:(id)arg4 withLyricType:(int)arg5 withLyricProtocol:(id)arg6;
- (unsigned long)_getLyricAttributeWithFilePath:(id)arg1;
- (void)_saveLyricAttributeWithFilePath:(id)arg1 WithTimeTag:(unsigned long)arg2;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)handleResearchHostCallback:(int)arg1;
- (void)researchLyric:(id)arg1 forceToUseSongID:(BOOL)arg2;
- (void)researchLyric:(id)arg1;
- (id)getLyric:(id)arg1 useFingerPrint:(BOOL)arg2 manualCause:(BOOL)arg3;
- (id)getLyricFromFingerPrintManager:(BOOL)arg1;
- (void)delayCallBackSeachDone:(id)arg1;
- (void)fetchLyricFromServer:(int)arg1;
- (id)getLyricObjectFromLocal;
- (id)getLyricFromLyricManager;
- (BOOL)isTopViewLyricView;
- (id)parseText:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

