//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppUtils : NSObject
{
    NSString *_deviceToken;
}

+ (BOOL)isPushEnabled;
+ (void)updateLocalGUID:(id)arg1;
+ (id)userDefaultUUIDKey;
+ (id)resetLocalGUID;
+ (id)getGUIDFromKeychain;
+ (id)getLocalGUID;
+ (id)getKeyChainServiceName;
+ (id)getKeyChainUserName;
+ (id)fullBundleDisplayName;
+ (id)bundleID;
+ (id)getAppBuildNumber;
+ (id)getAppBuildVersion;
+ (id)getAppVersion;
+ (id)bundleSeedID;
+ (id)getGUID;
+ (id)getAppBuildVersionFull;
+ (id)sharedInstance;
@property(copy, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
- (void)dealloc;

@end

