//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ImageManagerDelegate.h"
#import "ProtocolHostDelegate.h"

@class BannerItem, BannerProtocol, NSArray, NSMutableArray, NSString, SkinViewController, UIView;

__attribute__((visibility("hidden")))
@interface BannerVC : UIViewController <ProtocolHostDelegate, ImageManagerDelegate>
{
    NSMutableArray *_obervers;
    BannerProtocol *_bannerProtocol;
    BOOL _isScrolling;
    NSMutableArray *_exposedBannerIdArray;
    UIView *_bannerView;
    NSArray *_bannerArray;
    NSArray *_availableBannerArray;
    BannerItem *_currentShowingBanner;
    SkinViewController *_hostVC;
}

+ (id)sharedVC;
@property(nonatomic) __weak SkinViewController *hostVC; // @synthesize hostVC=_hostVC;
@property(retain, nonatomic) BannerItem *currentShowingBanner; // @synthesize currentShowingBanner=_currentShowingBanner;
@property(retain, nonatomic) NSArray *availableBannerArray; // @synthesize availableBannerArray=_availableBannerArray;
@property(retain, nonatomic) NSArray *bannerArray; // @synthesize bannerArray=_bannerArray;
@property(retain, nonatomic) UIView *bannerView; // @synthesize bannerView=_bannerView;
- (void).cxx_destruct;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)reportNewStatForType:(int)arg1 statCount:(int)arg2 bannerID:(int)arg3;
- (void)reloadBannerData;
- (BOOL)isReadyForShow;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)_qqmusicBecameInactive;
- (void)_qqmusicBecameActive;
- (id)_filterAvaibleBanners:(id)arg1;
- (void)_cleanUselessBannerCacheData;
- (BOOL)_haveCachedImageInBannerArray:(id)arg1;
- (void)_saveToCacheFile;
- (void)_restoreFromCachedFileIfExist;
- (BOOL)bannerHasExpired:(id)arg1;
- (void)_loadBannerImages;
- (void)_showNextBannerItem;
- (void)_stopScrollingBanner;
- (void)_startScrollingBanner:(BOOL)arg1;
- (void)_bannerCloseBtnTapped:(id)arg1;
- (void)_bannerImageTapped:(id)arg1;
- (void)_setUpBannerUI;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

