//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BannerVC;

@protocol BannerVCDelegate <NSObject>

@optional
- (void)bannerViewImageDidLoaded:(BannerVC *)arg1;
- (void)bannerViewShowingBannerIsChanged:(BannerVC *)arg1;
- (void)bannerViewContentDataIsUpdated:(BannerVC *)arg1;
- (void)bannerViewCloseBtnTapped:(BannerVC *)arg1;
@end

