//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBase.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface BannerProtocol : ProtocolBase
{
    NSArray *bannerArray;
}

@property(retain, nonatomic) NSArray *bannerArray; // @synthesize bannerArray;
- (void).cxx_destruct;
- (id)translateToDateObject:(id)arg1;
- (void)onParseXmlData:(struct _xmlDoc *)arg1;
- (id)getUrl;
- (id)init;

@end

