//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APASIHTTPRequestDelegate.h"

@class APASIHTTPRequest, NSDictionary, NSMutableData, NSMutableDictionary, RequestInfo;

@interface BaseHttp : NSObject <APASIHTTPRequestDelegate>
{
    RequestInfo *requestInfo;
    id <HttpDelegate> httpDelegate;
    APASIHTTPRequest *httpRequst;
    NSDictionary *reponseHeaderDic;
    NSMutableDictionary *requestHeaderDic;
    NSMutableData *requestBody;
}

@property(retain, nonatomic) APASIHTTPRequest *HttpRequest; // @synthesize HttpRequest=httpRequst;
@property(retain, nonatomic) NSDictionary *ReponseHeaderDic; // @synthesize ReponseHeaderDic=reponseHeaderDic;
@property(retain, nonatomic) RequestInfo *RequestInfo; // @synthesize RequestInfo=requestInfo;
@property(nonatomic) id <HttpDelegate> HttpDelegate; // @synthesize HttpDelegate=httpDelegate;
- (void)dealloc;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)pause;
- (void)request:(id)arg1 didReceiveResponseHeaders:(id)arg2;
- (void)requestStarted:(id)arg1;
- (void)connect;
- (void)EncryptBody;
- (void)setBody;
- (void)setHeader;
- (void)modifyUrl;
- (void)initHttpClient;
- (id)initwithRequestInfo:(id)arg1;

@end

