//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface Base64Helper : NSObject
{
}

+ (BOOL)isValidedBase64EncodedData:(id)arg1;
+ (BOOL)isValidedBase64EncodedChar:(unsigned short)arg1;
+ (id)decode_dat_to_dat:(id)arg1;
+ (id)decode_str_to_dat:(id)arg1;
+ (id)decode_dat_to_str:(id)arg1;
+ (id)decode_str_to_str:(id)arg1;
+ (id)encode_dat_to_dat:(id)arg1;
+ (id)encode_str_to_dat:(id)arg1;
+ (id)encode_dat_to_str:(id)arg1;
+ (id)encode_str_to_str:(id)arg1;

@end

