//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BEActionSheetStyleDownload.h"

__attribute__((visibility("hidden")))
@interface BEActionSheetStyleSelectLocalPic : BEActionSheetStyleDownload
{
}

- (id)createCenterLabel:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)fireConfirmButtonClick:(id)arg1;
- (id)confirmText;
- (void)customTitleView;

@end

