//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CDESUtil : NSObject
{
}

+ (id)desDataWithEBC:(id)arg1 key:(id)arg2 encrypt:(BOOL)arg3;
+ (id)desDataWithCBC:(id)arg1 key:(id)arg2 encrypt:(BOOL)arg3 iv:(const char *)arg4;

@end

