//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CGUpnpAvContentManager;

@interface CGUpnpAvContentDirectory : NSObject
{
    CGUpnpAvContentManager *contentMgr;
}

@property(retain) CGUpnpAvContentManager *contentMgr; // @synthesize contentMgr;
- (id)objectForTitlePath:(id)arg1;
- (id)objectForId:(id)arg1;
- (id)rootObject;
- (void)dealloc;
- (id)init;

@end

