//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CGUpnpAvRoot;

@interface CGUpnpAvContentManager : NSObject
{
    CGUpnpAvRoot *rootObj;
}

@property(retain) CGUpnpAvRoot *rootObj; // @synthesize rootObj;
- (id)objectForTitlePath:(id)arg1;
- (id)objectForId:(id)arg1;
- (void)dealloc;
- (id)init;

@end

