//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChannelV4Cell.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ChannelV4CategoryNormalTypeCell : ChannelV4Cell
{
    NSMutableArray *_itemViews;
}

+ (float)cellHeightWithRowData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *itemViews; // @synthesize itemViews=_itemViews;
- (void).cxx_destruct;
- (void)onNotifySkinSettingChange:(id)arg1;
- (void)updateSubviewsHidden;
- (struct CGRect)getItemViewFrameByIndex:(int)arg1;
- (id)categoryItems;
- (void)updateUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

