//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "QMChannelInteractiveProtocol.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface ChannelBaseTabVC : SkinViewController <QMChannelInteractiveProtocol>
{
    SkinViewController *_containerVC;
    NSMutableArray *_tableArray;
}

@property(retain, nonatomic) NSMutableArray *tableArray; // @synthesize tableArray=_tableArray;
@property(nonatomic) __weak SkinViewController *containerVC; // @synthesize containerVC=_containerVC;
- (void).cxx_destruct;
- (void)requestToShowMore:(id)arg1;
- (void)requestToPlayChannel:(id)arg1;
- (void)requestToShowChannel:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)recoverGestureState;
- (void)willResignCurrentTab;
- (void)willActiveCurrentTab;
- (void)serverChanged;
- (float)infoViewTopOffset;
- (id)navigationController;
- (BOOL)isNeedAddBottomLine;
- (id)strVCtype;
- (void)loadView;
- (BOOL)useBgImage;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

