//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ChannelCreator : NSObject
{
    BOOL _isVip;
    BOOL _isSVip;
    BOOL _isFollow;
    BOOL _profileLock;
    NSString *_name;
    NSString *_subName;
    int _creatorType;
    int _clickType;
    unsigned long _uin;
    unsigned long _singerId;
    NSString *_singerMid;
    NSString *_vipIconUrl;
    NSString *_avatarUrl;
    NSString *_desc;
    int _fansNum;
    int _folderNum;
    int _listenNum;
    int _followNum;
    int _shareNum;
    NSString *_gender;
    NSString *_birthday;
    NSString *_area;
    int _vipLevel;
    int _nextLevel;
    int _yearFlag;
    int _vipProgress;
    int _vipRemainDay;
    NSString *_expireDay;
    NSString *_recomInfo;
    int _singerType;
    int _index;
}

+ (id)translateCreatorFromURL:(id)arg1;
+ (void)translateFromCircleJsonData:(id)arg1 ToCreator:(id)arg2;
+ (id)translateFromCircleJsonData:(id)arg1;
+ (void)tranlateToCreatorFromJsonData:(id)arg1 toSubCreator:(id)arg2;
+ (id)tranlateToCreatorFromJsonData:(id)arg1;
+ (id)smallVipIcon;
+ (id)bigVipIcon;
@property(nonatomic) int index; // @synthesize index=_index;
@property(nonatomic) BOOL profileLock; // @synthesize profileLock=_profileLock;
@property(nonatomic) int singerType; // @synthesize singerType=_singerType;
@property(retain, nonatomic) NSString *recomInfo; // @synthesize recomInfo=_recomInfo;
@property(retain, nonatomic) NSString *expireDay; // @synthesize expireDay=_expireDay;
@property(nonatomic) int vipRemainDay; // @synthesize vipRemainDay=_vipRemainDay;
@property(nonatomic) int vipProgress; // @synthesize vipProgress=_vipProgress;
@property(nonatomic) int yearFlag; // @synthesize yearFlag=_yearFlag;
@property(nonatomic) int nextLevel; // @synthesize nextLevel=_nextLevel;
@property(nonatomic) int vipLevel; // @synthesize vipLevel=_vipLevel;
@property(retain, nonatomic) NSString *area; // @synthesize area=_area;
@property(retain, nonatomic) NSString *birthday; // @synthesize birthday=_birthday;
@property(retain, nonatomic) NSString *gender; // @synthesize gender=_gender;
@property(nonatomic) int shareNum; // @synthesize shareNum=_shareNum;
@property(nonatomic) int followNum; // @synthesize followNum=_followNum;
@property(nonatomic) int listenNum; // @synthesize listenNum=_listenNum;
@property(nonatomic) int folderNum; // @synthesize folderNum=_folderNum;
@property(nonatomic) int fansNum; // @synthesize fansNum=_fansNum;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(nonatomic) BOOL isFollow; // @synthesize isFollow=_isFollow;
@property(retain, nonatomic) NSString *avatarUrl; // @synthesize avatarUrl=_avatarUrl;
@property(retain, nonatomic) NSString *vipIconUrl; // @synthesize vipIconUrl=_vipIconUrl;
@property(nonatomic) BOOL isSVip; // @synthesize isSVip=_isSVip;
@property(nonatomic) BOOL isVip; // @synthesize isVip=_isVip;
@property(retain, nonatomic) NSString *singerMid; // @synthesize singerMid=_singerMid;
@property(nonatomic) unsigned long singerId; // @synthesize singerId=_singerId;
@property(nonatomic) unsigned long uin; // @synthesize uin=_uin;
@property(nonatomic) int clickType; // @synthesize clickType=_clickType;
@property(nonatomic) int creatorType; // @synthesize creatorType=_creatorType;
@property(retain, nonatomic) NSString *subName; // @synthesize subName=_subName;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)signature;
- (id)nameByMaxLength:(int)arg1;
- (id)translateCreatorToURL;
- (id)initFromFileByUin:(unsigned long)arg1;
- (void)saveToFile;
- (BOOL)isSingerDJ;
- (BOOL)isRealSinger;
- (BOOL)isSinger;
- (id)getSingerInfo;
- (id)imageFileName;
- (BOOL)isEqualContent:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

