//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChannelV4CellData.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ChannelV4CellDataForTileStyle : ChannelV4CellData
{
    BOOL _noBottomSpacing;
    NSMutableArray *_channels;
}

@property(nonatomic) BOOL noBottomSpacing; // @synthesize noBottomSpacing=_noBottomSpacing;
@property(retain, nonatomic) NSMutableArray *channels; // @synthesize channels=_channels;
- (void).cxx_destruct;
- (int)type;
- (id)init;

@end

