//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ChannelAdItem : NSObject
{
    int _adid;
    NSString *_adimgurl;
    int _adtype;
    NSString *_jmpurl;
    NSString *_tjreport;
    NSString *_mvid;
    NSString *_mvtitle;
    NSString *_singername;
    NSString *_mvpic;
    long long _adrecordid;
}

+ (id)translateFromDic:(id)arg1;
@property(retain, nonatomic) NSString *mvpic; // @synthesize mvpic=_mvpic;
@property(retain, nonatomic) NSString *singername; // @synthesize singername=_singername;
@property(retain, nonatomic) NSString *mvtitle; // @synthesize mvtitle=_mvtitle;
@property(retain, nonatomic) NSString *mvid; // @synthesize mvid=_mvid;
@property(retain, nonatomic) NSString *tjreport; // @synthesize tjreport=_tjreport;
@property(retain, nonatomic) NSString *jmpurl; // @synthesize jmpurl=_jmpurl;
@property(nonatomic) long long adrecordid; // @synthesize adrecordid=_adrecordid;
@property(nonatomic) int adtype; // @synthesize adtype=_adtype;
@property(retain, nonatomic) NSString *adimgurl; // @synthesize adimgurl=_adimgurl;
@property(nonatomic) int adid; // @synthesize adid=_adid;
- (void).cxx_destruct;

@end

