//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ChannelItemKey : NSObject
{
    BOOL _bHaveSongArray;
    int typeId;
    int orderId;
    int orderType;
    int dirId;
    NSString *coverId;
    NSString *action;
    int index;
    unsigned long _creatorUin;
    long long itemId;
}

+ (id)createByChannelItem:(id)arg1;
@property(nonatomic) unsigned long creatorUin; // @synthesize creatorUin=_creatorUin;
@property(nonatomic) BOOL bHaveSongArray; // @synthesize bHaveSongArray=_bHaveSongArray;
@property(nonatomic) int index; // @synthesize index;
@property(retain, nonatomic) NSString *action; // @synthesize action;
@property(retain, nonatomic) NSString *coverId; // @synthesize coverId;
@property(nonatomic) int dirId; // @synthesize dirId;
@property(nonatomic) int orderType; // @synthesize orderType;
@property(nonatomic) int orderId; // @synthesize orderId;
@property(nonatomic) int typeId; // @synthesize typeId;
@property(nonatomic) long long itemId; // @synthesize itemId;
- (void).cxx_destruct;
- (BOOL)isEqualContent:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (int)getIndex;
- (id)getAction;
- (id)getCoverId;
- (id)getKey;
- (unsigned long)getCreatorUin;
- (int)getDirId;
- (int)getOrderType;
- (int)getOrderId;
- (int)getTypeId;
- (long long)getItemId;

@end

