//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChannelV4Cell.h"

#import "ImageManagerDelegate.h"

@class NSString, UIButton, UIButtonWithUserInfo, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface ChannelV4PopularityCell : ChannelV4Cell <ImageManagerDelegate>
{
    UIButton *_clickArea;
    UIImageView *_defaultImageView;
    UIButtonWithUserInfo *_channelImageView;
    UILabel *_titleLabel1;
    UILabel *_subtitleLabel1;
    UILabel *_titleLabel2;
    UILabel *_subtitleLabel2;
    UILabel *_titleLabel3;
    UILabel *_subtitleLabel3;
    UIImageView *_arrowImageView;
}

+ (float)cellHeightWithRowData:(id)arg1;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UILabel *subtitleLabel3; // @synthesize subtitleLabel3=_subtitleLabel3;
@property(retain, nonatomic) UILabel *titleLabel3; // @synthesize titleLabel3=_titleLabel3;
@property(retain, nonatomic) UILabel *subtitleLabel2; // @synthesize subtitleLabel2=_subtitleLabel2;
@property(retain, nonatomic) UILabel *titleLabel2; // @synthesize titleLabel2=_titleLabel2;
@property(retain, nonatomic) UILabel *subtitleLabel1; // @synthesize subtitleLabel1=_subtitleLabel1;
@property(retain, nonatomic) UILabel *titleLabel1; // @synthesize titleLabel1=_titleLabel1;
@property(retain, nonatomic) UIButtonWithUserInfo *channelImageView; // @synthesize channelImageView=_channelImageView;
@property(retain, nonatomic) UIImageView *defaultImageView; // @synthesize defaultImageView=_defaultImageView;
@property(retain, nonatomic) UIButton *clickArea; // @synthesize clickArea=_clickArea;
- (void).cxx_destruct;
- (void)onNotifySkinSettingChange:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)trimImage:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (id)defaultImage;
- (void)onNotifyColorStyleChanged:(id)arg1;
- (void)didClick;
- (int)fontSize;
- (float)cellHeight;
- (void)updateTitleFormData:(id)arg1;
- (void)updateUI;
- (id)popularityData;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

