//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "QMTabBarDelegate.h"

@class ChannelBaseTabVC, NSString, UIScrollView;

__attribute__((visibility("hidden")))
@interface ChannelRootViewController_V4 : SkinViewController <QMTabBarDelegate>
{
    BOOL _UIReadyState;
    int _currentIndex;
    ChannelBaseTabVC *_visibleTabVC;
    UIScrollView *_tabScrollView;
}

@property(retain, nonatomic) UIScrollView *tabScrollView; // @synthesize tabScrollView=_tabScrollView;
@property(retain, nonatomic) ChannelBaseTabVC *visibleTabVC; // @synthesize visibleTabVC=_visibleTabVC;
- (void).cxx_destruct;
- (void)goMusicHallTab:(unsigned int)arg1 categoryId:(int)arg2;
- (void)switchToRecommandTab;
- (void)onColorStyleChanged;
- (void)indicatorVisibleTabVC;
- (void)loadTabViewAtIndex:(int)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)selectedItem:(id)arg1 atIndex:(unsigned int)arg2;
- (void)touchDown:(id)arg1 itemAtIndex:(unsigned int)arg2;
- (int)maxPreloadTabs;
- (void)touchUpInside:(id)arg1 itemAtIndex:(unsigned int)arg2;
- (id)selectedImageView:(id)arg1;
- (id)selectetdItemImage:(id)arg1 atIndex:(unsigned int)arg2;
- (id)backgroundImage:(id)arg1;
- (id)accessibilityLabel:(id)arg1 atIndex:(unsigned int)arg2;
- (id)imageFor:(id)arg1 atIndex:(unsigned int)arg2;
- (void)setupHeadTabBar;
- (void)willSwitchToChannelTab;
- (id)strVCtype;
- (int)vcType;
- (void)touchOnTop;
- (void)popGestureRecognize;
- (void)viewDidPop;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (BOOL)isNeedAddBottomLine;
- (void)loadView;
- (BOOL)useBgImage;
- (void)dealloc;
- (id)init;
- (id)tabComponents;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

