//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChannelLayoutCell.h"

__attribute__((visibility("hidden")))
@interface ChannelLayoutCell_Style5 : ChannelLayoutCell
{
}

+ (float)cellHeight;
- (struct CGRect)frameForCellAtIndex:(unsigned int)arg1;
- (id)reuseIdentifier;
- (Class)channelCellClass;
- (void)setupCustomizedUI;

@end

