//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ChannelHomeProtocol : ProtocolBaseJason
{
    NSMutableArray *_contents;
    double _refreshInterval;
}

@property(readonly, nonatomic) NSMutableArray *contents; // @synthesize contents=_contents;
@property(nonatomic) double refreshInterval; // @synthesize refreshInterval=_refreshInterval;
- (void).cxx_destruct;
- (id)castItemToObject:(id)arg1;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getCVStr;
- (id)getUrl;
- (BOOL)canReportError;
- (int)cid;
- (id)init;

@end

