//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtocolHostDelegate.h"

__attribute__((visibility("hidden")))
@interface ChinaUnicomProtocolManager : NSObject <ProtocolHostDelegate>
{
    BOOL isGetedPhoneNumber;
    BOOL onlyGetPhoneNumber;
}

+ (id)shareInstance;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)startGetPhoneNumberProtocol;
- (void)onlyStartGetPhoneNumberProtocol;
- (void)startChinaUnicomFreeFlowProtocol;

@end

