//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSString, SongInfo;

__attribute__((visibility("hidden")))
@interface ChirrupRecvProtocol : ProtocolBaseJason
{
    NSString *_codeid;
    SongInfo *_songinfo;
    NSString *_uin;
    NSString *_nick;
}

@property(retain, nonatomic) NSString *nick; // @synthesize nick=_nick;
@property(retain, nonatomic) NSString *uin; // @synthesize uin=_uin;
@property(retain, nonatomic) SongInfo *songinfo; // @synthesize songinfo=_songinfo;
@property(retain, nonatomic) NSString *codeid; // @synthesize codeid=_codeid;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (int)cid;
- (id)init;

@end

