//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface CircleLabel : UIView
{
    UILabel *labelFirst;
    UILabel *labelSecond;
    BOOL bNeedAnimation;
    struct CGRect rectFirstBegin;
    struct CGRect rectFirstEnd;
    struct CGRect rectSecondBegin;
    struct CGRect rectSecondEnd;
    BOOL currentSideFading;
    double circleInterval;
}

@property(nonatomic) double circleInterval; // @synthesize circleInterval;
@property(retain, nonatomic) UILabel *labelSecond; // @synthesize labelSecond;
@property(retain, nonatomic) UILabel *labelFirst; // @synthesize labelFirst;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setSideFading:(BOOL)arg1;
- (void)songNameAnimate:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)setText:(id)arg1;
- (void)setTextFont:(float)arg1 bold:(BOOL)arg2;
- (void)setTextColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 fontSize:(float)arg2 textColor:(id)arg3 align:(int)arg4 bold:(BOOL)arg5 shadow:(BOOL)arg6 shadowOffset:(struct CGSize)arg7 shadowColor:(id)arg8;
- (id)initWithFrame:(struct CGRect)arg1;

@end

