//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface ContentValues : NSObject
{
    NSMutableDictionary *column;
}

- (void).cxx_destruct;
- (id)description;
- (id)getSetValue;
- (id)getInsertValue;
- (void)put:(id)arg1 AndChar:(BOOL)arg2;
- (void)put:(id)arg1 AndLongLong:(long long)arg2;
- (void)put:(id)arg1 AndUnsignedInt:(unsigned int)arg2;
- (void)put:(id)arg1 AndInt:(int)arg2;
- (void)put:(id)arg1 And:(id)arg2;
- (void)basicPut:(id)arg1 And:(id)arg2;
- (id)getString:(id)arg1;
- (long long)getLongLong:(id)arg1;
- (int)getInt:(id)arg1;
- (unsigned int)getUnsignedInt:(id)arg1;
- (BOOL)valueExist:(id)arg1;
- (void)initWith:(struct sqlite3_stmt *)arg1;
- (id)init;

@end

