//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

__attribute__((visibility("hidden")))
@interface CoverView : UIImageView
{
}

- (void)imageChanged:(id)arg1;
- (id)_renderSingerImage:(id)arg1;
- (void)setCoverImage:(id)arg1;
- (void)addBottomView;
- (void)addMaskView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

