//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CrashReportObject, NSString;

@protocol CrashReportSenderDelegate

@optional
- (NSString *)createReportContentByReportInfo:(CrashReportObject *)arg1;
- (void)handleCrashReport:(CrashReportObject *)arg1;
@end

