//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CrashReporter : NSObject
{
    id <CrashUploadResultDelegete> delegate;
    BOOL mergeExp;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <CrashUploadResultDelegete> delegate; // @synthesize delegate;
- (BOOL)cleanCrashRecords:(id)arg1;
- (BOOL)cleanCrashRecord;
- (BOOL)checkCrash;
- (id)getCrashToUpload;
- (BOOL)uploadCrashes:(id)arg1;
- (void)setAttachLog:(id)arg1;
- (void)printCrashStack;
- (void)setNSException:(id)arg1;
- (id)getCrashLog;
- (id)getCrashStack;
- (id)getCurrentException;
- (id)getCrashStackShortNames;
- (BOOL)setIncludeShortName:(id)arg1;
- (BOOL)setExcludeShortName:(id)arg1 saveAndUpload:(BOOL)arg2;
- (BOOL)isLastCloseByCrash;
- (void)setLogLevel:(int)arg1;
- (void)setGUID:(id)arg1;
- (void)setUserId:(id)arg1;
- (void)setStrInternalBuildNumber:(id)arg1;
- (void)setBundleVer:(id)arg1;
- (void)setBundleId:(id)arg1;
- (BOOL)resetDBPath:(id)arg1;
- (void)setAppKey:(id)arg1;
- (void)uninstall;
- (void)install:(id)arg1 uploadAtomatic:(BOOL)arg2;
- (BOOL)isCleanBeforeUpload;
- (BOOL)isExpMergeUpload;
- (BOOL)userMachHandler;
- (void)setUserMachHandler:(BOOL)arg1;
- (BOOL)isEnableSymbolicateInProcess;
- (void)setEnableSymbolicateInProcess:(BOOL)arg1;
- (void)setCleanBeforeUpload:(BOOL)arg1;
- (void)setExpMergeUpload:(BOOL)arg1;
- (id)init;

@end

