//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIToolbar.h"

@class CALayer;

__attribute__((visibility("hidden")))
@interface CRNavigationBar : UIToolbar
{
    CALayer *_colorLayer;
}

@property(retain, nonatomic) CALayer *colorLayer; // @synthesize colorLayer=_colorLayer;
- (void).cxx_destruct;
- (void)displayColorLayer:(BOOL)arg1;
- (void)layoutSubviews;
- (float)convertValue:(float)arg1 withOpacity:(float)arg2;
- (float)minOpacityForValue:(float)arg1;
- (void)setBarTintColor:(id)arg1;

@end

