//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface DiskManager : NSObject
{
}

+ (id)sharedDiskManager;
- (void)dealloc;
- (void)_statUsedSpace;
- (void)addUsedSpaceStatInfo;
- (void)_onNotifyCheckFirstPieceCacheFolderSizeFinish:(id)arg1;
- (void)checkFirstPieceCache;
- (BOOL)tooManyFirstPieces;
- (void)deleteFirstPieceCacheWhileLowDiskSpace;
- (unsigned long long)freeSpaceValueOfDisk;
- (BOOL)showWarningWhenDownloadingFor:(unsigned long long)arg1;
- (void)mainThreadShowAlert;
- (BOOL)hasEnoughDiskspaceOf:(unsigned long long)arg1;
- (void)showNoDiskSpaceWarningFor:(BOOL)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (BOOL)canShowSpaceWarningAgain;

@end

