//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CGUpnpControlPointDelegate.h"

@class CGUpnpAvController, CGUpnpAvRenderer, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface DLNAController : NSObject <CGUpnpControlPointDelegate>
{
    BOOL bRedirected;
    BOOL bSearching;
    NSObject<OS_dispatch_queue> *myQueue;
    NSObject<OS_dispatch_queue> *myQueueForPositionInfo;
    BOOL _dlnaDisable;
    CGUpnpAvController *_dlnaCtl;
    NSMutableArray *_dlnaRenders;
    CGUpnpAvRenderer *_dlnaRender;
    id <DLNAControllerDelegate> delegate;
    float _trackDuration;
    float _curPlayTime;
    unsigned int _fileSize;
    NSString *_curTitle;
}

+ (BOOL)dlnaCtlExsist;
+ (id)sharedDLNAController;
@property(retain) NSString *curTitle; // @synthesize curTitle=_curTitle;
@property unsigned int fileSize; // @synthesize fileSize=_fileSize;
@property BOOL dlnaDisable; // @synthesize dlnaDisable=_dlnaDisable;
@property id <DLNAControllerDelegate> delegate; // @synthesize delegate;
@property(retain) CGUpnpAvRenderer *dlnaRender; // @synthesize dlnaRender=_dlnaRender;
@property(retain) NSMutableArray *dlnaRenders; // @synthesize dlnaRenders=_dlnaRenders;
- (BOOL)stop;
- (BOOL)seek:(double)arg1;
- (BOOL)pause;
- (BOOL)play;
- (BOOL)isPlaying;
- (void)controlPoint:(id)arg1 deviceInvalid:(id)arg2;
- (void)controlPoint:(id)arg1 deviceUpdated:(id)arg2;
- (void)controlPoint:(id)arg1 deviceRemoved:(id)arg2;
- (void)controlPoint:(id)arg1 deviceAdded:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)playOnThreadWithInfo:(id)arg1;
- (void)beginPlayDLNAWithUrl:(id)arg1;
- (void)playURL:(id)arg1 atRenderIndex:(int)arg2 title:(id)arg3;
- (void)playURL:(id)arg1;
- (void)setRenderAtIndex:(int)arg1;
- (void)searchUpdateTimer:(id)arg1;
- (void)searchReaders:(BOOL)arg1;
- (BOOL)needSearchRenders;
- (void)clearRenders;
- (void)resetCtlWithNetworkChaged;
@property(readonly) float trackDuration; // @synthesize trackDuration=_trackDuration;
@property(readonly) float curPlayTime; // @synthesize curPlayTime=_curPlayTime;
@property(readonly) NSString *curRenderName;
@property(readonly) CGUpnpAvController *dlnaCtl; // @synthesize dlnaCtl=_dlnaCtl;
- (id)dispatchQueue;
- (void)didFindRendersMain:(id)arg1;
- (void)mainPlayStop:(id)arg1;
- (void)loseConnectionMain:(id)arg1;
- (void)mainPlayFailed:(id)arg1;
- (void)mainPlayDown:(id)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

