//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ASIHTTPRequest, DownloadBasicInfo, NSFileHandle, NSObject<OS_dispatch_queue>, NSString, NSURL, RetryLogic, SingleHourglass;

__attribute__((visibility("hidden")))
@interface DownLoadTask : NSObject
{
    DownloadBasicInfo *info;
    NSURL *downloadURL;
    ASIHTTPRequest *taskConnection;
    NSString *storeDataFilePath;
    NSFileHandle *storeDataFileHandle;
    id <DownLoadTaskDelegate> delegate;
    NSString *statFrom;
    SingleHourglass *hourglass;
    int netType;
    int failRepeatCount;
    int iUrlIndex;
    int totalReceivedBytes;
    NSObject<OS_dispatch_queue> *downloadFileWritingQueue;
    BOOL isQQImage;
    BOOL bSupport304;
    BOOL _exclusiveSongChecked;
    SingleHourglass *hourGlassConnectedToServer;
    SingleHourglass *hourGlassGetFirstPacket;
    unsigned long iTimeConnectedToServer;
    unsigned long iTimeGetFirstPacket;
    NSString *_cdnHost;
    NSString *_cdnIp;
    NSString *_writeFileException;
    int _downloadErrorCode;
    int _currentSongRateType;
    NSString *_weiYunURL;
    int _statusCode;
    NSString *_lastModified;
    RetryLogic *_retryLogic;
}

@property(nonatomic) BOOL exclusiveSongChecked; // @synthesize exclusiveSongChecked=_exclusiveSongChecked;
@property(retain, nonatomic) RetryLogic *retryLogic; // @synthesize retryLogic=_retryLogic;
@property(retain, nonatomic) NSString *lastModified; // @synthesize lastModified=_lastModified;
@property(nonatomic) int statusCode; // @synthesize statusCode=_statusCode;
@property(retain, nonatomic) NSString *weiYunURL; // @synthesize weiYunURL=_weiYunURL;
@property(readonly, nonatomic) int currentSongRateType; // @synthesize currentSongRateType=_currentSongRateType;
@property(nonatomic) int downloadErrorCode; // @synthesize downloadErrorCode=_downloadErrorCode;
@property(readonly, nonatomic) NSString *writeFileException; // @synthesize writeFileException=_writeFileException;
@property(readonly, nonatomic) NSString *cdnIp; // @synthesize cdnIp=_cdnIp;
@property(readonly, nonatomic) __weak NSString *cdnHost; // @synthesize cdnHost=_cdnHost;
@property(nonatomic) BOOL bSupport304; // @synthesize bSupport304;
@property(readonly, nonatomic) int totalReceivedBytes; // @synthesize totalReceivedBytes;
@property(nonatomic) unsigned long iTimeGetFirstPacket; // @synthesize iTimeGetFirstPacket;
@property(nonatomic) unsigned long iTimeConnectedToServer; // @synthesize iTimeConnectedToServer;
@property(retain) SingleHourglass *hourGlassGetFirstPacket; // @synthesize hourGlassGetFirstPacket;
@property(retain) SingleHourglass *hourGlassConnectedToServer; // @synthesize hourGlassConnectedToServer;
@property(retain, nonatomic) NSString *statFrom; // @synthesize statFrom;
@property(nonatomic) int iUrlIndex; // @synthesize iUrlIndex;
@property(nonatomic) int netType; // @synthesize netType;
@property(readonly, nonatomic) SingleHourglass *hourglass; // @synthesize hourglass;
@property(nonatomic) __weak id <DownLoadTaskDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSString *storeDataFilePath; // @synthesize storeDataFilePath;
@property(retain, nonatomic) NSFileHandle *storeDataFileHandle; // @synthesize storeDataFileHandle;
@property(retain, nonatomic) NSURL *downloadURL; // @synthesize downloadURL;
@property(retain, nonatomic) ASIHTTPRequest *taskConnection; // @synthesize taskConnection;
@property(readonly, nonatomic) DownloadBasicInfo *info; // @synthesize info;
- (void).cxx_destruct;
- (void)_fetchMVDownloadURLFailed:(int)arg1;
- (void)_asyncFetchMVURL;
- (int)_getSongRateTypeByQuality:(int)arg1;
- (id)_makeStringStatable:(id)arg1;
- (void)_setLastError:(int)arg1;
- (id)getRetryLogic;
- (void)dealloc;
- (int)getSpeedByBps;
- (void)connectionError;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)request:(id)arg1 didReceiveData:(id)arg2;
- (void)request:(id)arg1 didReceiveResponseHeaders:(id)arg2;
- (void)requestStarted:(id)arg1;
- (void)sendSpeedStat;
- (int)get3GName;
- (int)getWifiName;
- (void)innerRestartTask;
- (void)cancleTask;
- (void)innerCancleTask;
- (void)cancelRequestBy304:(id)arg1;
- (void)resumeTask;
- (void)pauseTask;
- (void)startTask;
- (void)_downloadImageAndLyricForSong;
- (void)innerStartTask;
- (void)updateFileLastModifiedByPath:(id)arg1 withValue:(id)arg2;
- (id)lastModifiedByPath:(id)arg1;
- (id)fileModificationDateByPath:(id)arg1;
- (id)rfc1123DateFormatter;
- (id)createConnection:(unsigned int)arg1;
- (id)initWithDownloadInfo:(id)arg1;

@end

