//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SongCell.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface DownloadHistoryCell : SongCell
{
    UIImageView *autoSaveFinishView;
}

@property(retain, nonatomic) UIImageView *autoSaveFinishView; // @synthesize autoSaveFinishView;
- (void).cxx_destruct;
- (void)setIsHq:(BOOL)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

