//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

@class GreenDiamondView, QQUser;

__attribute__((visibility("hidden")))
@interface EditUserInfoViewController : SkinViewController
{
    QQUser *_user;
    GreenDiamondView *_gdView;
}

@property(retain, nonatomic) GreenDiamondView *gdView; // @synthesize gdView=_gdView;
@property(retain, nonatomic) QQUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)addGreenDiamondView;
- (void)headerFinish:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithUser:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

