//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class ListBase, MusicGene, NSArray;

__attribute__((visibility("hidden")))
@interface FetchGeneInfoProtocol : ProtocolBaseJason
{
    unsigned long _visitUin;
    MusicGene *_gene;
    ListBase *_songlist;
    NSArray *_users;
}

@property(readonly, nonatomic) NSArray *users; // @synthesize users=_users;
@property(readonly, nonatomic) ListBase *songlist; // @synthesize songlist=_songlist;
@property(readonly, nonatomic) MusicGene *gene; // @synthesize gene=_gene;
@property(readonly, nonatomic) unsigned long visitUin; // @synthesize visitUin=_visitUin;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (int)cid;
- (id)initWithVisitUin:(unsigned long)arg1 MusicGene:(id)arg2;

@end

