//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface FileViewController : SkinViewController
{
    NSString *path;
}

+ (id)getFileViewControllerByPath:(id)arg1;
+ (Class)getFileViewControllerClassByPath:(id)arg1;
@property(retain) NSString *path; // @synthesize path;
- (void).cxx_destruct;
- (void)showAlert:(id)arg1;
- (id)getPath;
- (void)loadView;
- (id)initWithFilePath:(id)arg1;

@end

