//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface FilterAddToDownloadingResult : NSObject
{
    BOOL _exist320Mp3File;
    BOOL _existFlacFile;
    NSMutableArray *_canDownload128Mp3Songs;
    NSMutableArray *_canDownload320Mp3Songs;
    NSMutableArray *_canDownloadFlacSongs;
    NSMutableArray *_inDownloaded;
    NSMutableArray *_inDownloading;
    NSMutableArray *_disableDownload;
    unsigned long long _total128Mp3Size;
    unsigned long long _total320Mp3Size;
    unsigned long long _totalFlacSize;
}

@property(retain) NSMutableArray *disableDownload; // @synthesize disableDownload=_disableDownload;
@property(retain) NSMutableArray *inDownloading; // @synthesize inDownloading=_inDownloading;
@property(retain) NSMutableArray *inDownloaded; // @synthesize inDownloaded=_inDownloaded;
@property BOOL existFlacFile; // @synthesize existFlacFile=_existFlacFile;
@property BOOL exist320Mp3File; // @synthesize exist320Mp3File=_exist320Mp3File;
@property unsigned long long totalFlacSize; // @synthesize totalFlacSize=_totalFlacSize;
@property unsigned long long total320Mp3Size; // @synthesize total320Mp3Size=_total320Mp3Size;
@property unsigned long long total128Mp3Size; // @synthesize total128Mp3Size=_total128Mp3Size;
@property(retain) NSMutableArray *canDownloadFlacSongs; // @synthesize canDownloadFlacSongs=_canDownloadFlacSongs;
@property(retain) NSMutableArray *canDownload320Mp3Songs; // @synthesize canDownload320Mp3Songs=_canDownload320Mp3Songs;
@property(retain) NSMutableArray *canDownload128Mp3Songs; // @synthesize canDownload128Mp3Songs=_canDownload128Mp3Songs;
- (void).cxx_destruct;
- (void)_setCapacity:(unsigned int)arg1;
- (id)initWithCapacity:(unsigned int)arg1;
- (id)init;

@end

