//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SongInfo;

@protocol FingerPrintManagerDelegate <NSObject>
- (void)onFingerPrintStatusChange:(SongInfo *)arg1 fingerPrintStatus:(int)arg2 lyric:(NSString *)arg3 SongId:(long long)arg4 lyricType:(int)arg5;
@end

