//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBase.h"

@class NSData, NSString;

__attribute__((visibility("hidden")))
@interface FingerPrintProtocol : ProtocolBase
{
    NSData *_dataFingerPrint;
    unsigned int _iDuration;
    long long _iSongIdMatched;
    float _fMatchRate;
    NSString *_strSinger;
    NSString *_strAlbum;
    NSString *_strLyric;
    BOOL _bManualCause;
    int _lyricType;
}

@property(nonatomic) int lyricType; // @synthesize lyricType=_lyricType;
@property(readonly, nonatomic) NSString *strLyric; // @synthesize strLyric=_strLyric;
@property(readonly, nonatomic) NSString *strAlbum; // @synthesize strAlbum=_strAlbum;
@property(readonly, nonatomic) NSString *strSinger; // @synthesize strSinger=_strSinger;
@property(readonly, nonatomic) long long iSongIdMatched; // @synthesize iSongIdMatched=_iSongIdMatched;
@property(retain, nonatomic) NSData *dataFingerPrint; // @synthesize dataFingerPrint=_dataFingerPrint;
- (void).cxx_destruct;
- (void)onParseXmlData:(struct _xmlDoc *)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (void)start;
- (id)getUrl;
- (BOOL)canReportError;
- (id)initWithFingerPrint:(id)arg1 andDuration:(unsigned int)arg2 manualCause:(BOOL)arg3;

@end

