//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface FlashScreenItem : NSObject <NSCoding>
{
    BOOL isClickable;
    BOOL isGDTSplash;
    int iId;
    NSString *strName;
    NSString *strPath;
    NSString *strStartTime;
    NSString *strEndTime;
    NSString *strClickURL;
    NSString *strExposureURL;
    NSString *strSplashType;
    NSString *strPageType;
    int jumpType;
    int jumpId;
    NSString *zipPackageUrl;
    int staticTimeout;
    int dynamicTimeout;
    NSString *mvId;
    NSString *mvTitle;
    NSString *singerName;
    NSDate *getSplashDate;
    NSString *mvPic;
    long long longJumpId;
}

+ (void)saveFlashScreens:(id)arg1;
@property(retain, nonatomic) NSString *mvPic; // @synthesize mvPic;
@property(retain, nonatomic) NSDate *getSplashDate; // @synthesize getSplashDate;
@property(retain, nonatomic) NSString *singerName; // @synthesize singerName;
@property(retain, nonatomic) NSString *mvTitle; // @synthesize mvTitle;
@property(retain, nonatomic) NSString *mvId; // @synthesize mvId;
@property(nonatomic) int dynamicTimeout; // @synthesize dynamicTimeout;
@property(nonatomic) int staticTimeout; // @synthesize staticTimeout;
@property(retain, nonatomic) NSString *zipPackageUrl; // @synthesize zipPackageUrl;
@property(nonatomic) int jumpId; // @synthesize jumpId;
@property(nonatomic) long long longJumpId; // @synthesize longJumpId;
@property(nonatomic) int jumpType; // @synthesize jumpType;
@property(nonatomic) BOOL isGDTSplash; // @synthesize isGDTSplash;
@property(nonatomic) BOOL isClickable; // @synthesize isClickable;
@property(retain, nonatomic) NSString *strPageType; // @synthesize strPageType;
@property(retain, nonatomic) NSString *strSplashType; // @synthesize strSplashType;
@property(retain, nonatomic) NSString *strExposureURL; // @synthesize strExposureURL;
@property(retain, nonatomic) NSString *strClickURL; // @synthesize strClickURL;
@property(retain, nonatomic) NSString *strEndTime; // @synthesize strEndTime;
@property(retain, nonatomic) NSString *strStartTime; // @synthesize strStartTime;
@property(retain, nonatomic) NSString *strPath; // @synthesize strPath;
@property(retain, nonatomic) NSString *strName; // @synthesize strName;
@property(nonatomic) int iId; // @synthesize iId;
- (void).cxx_destruct;
- (id)staticSplashResourceName;
- (id)dynamicSplashJSIndexPath;
- (id)dynamicSplashDirPath;
- (BOOL)isAD;
- (BOOL)isDynamicSplashPrepared;
- (BOOL)isStaticSplashPrepared;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

