//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FMCProtocolListener.h"
#import "NSStreamDelegate.h"

@class FMCAbstractProtocol, FMCLockScreenManager, NSMutableArray, NSObject<FMCTransport>, NSString, NSTimer;

@interface FMCSyncProxy : NSObject <FMCProtocolListener, NSStreamDelegate>
{
    unsigned char _version;
    unsigned char bulkSessionID;
    BOOL isConnected;
    BOOL alreadyDestructed;
    FMCLockScreenManager *lsm;
    FMCAbstractProtocol *_protocol;
    NSObject<FMCTransport> *_transport;
    NSMutableArray *_proxyListeners;
    NSTimer *_handshakeTimer;
    NSString *_debugConsoleGroupName;
}

+ (void)disableSiphonDebug;
+ (void)enableSiphonDebug;
@property(retain) NSString *debugConsoleGroupName; // @synthesize debugConsoleGroupName=_debugConsoleGroupName;
@property(retain) NSTimer *handshakeTimer; // @synthesize handshakeTimer=_handshakeTimer;
@property(retain) NSMutableArray *proxyListeners; // @synthesize proxyListeners=_proxyListeners;
@property(retain) NSObject<FMCTransport> *transport; // @synthesize transport=_transport;
@property(retain) FMCAbstractProtocol *protocol; // @synthesize protocol=_protocol;
- (void).cxx_destruct;
- (void)stream:(id)arg1 handleEvent:(unsigned int)arg2;
- (void)putFileStream:(id)arg1:(id)arg2;
- (void)sendDataStream:(id)arg1 withServiceType:(unsigned char)arg2;
- (void)OSRHTTPRequestCompletionHandler:(id)arg1 response:(id)arg2 error:(id)arg3;
- (void)OESPHTTPRequestCompletionHandler:(id)arg1 response:(id)arg2 error:(id)arg3;
- (void)sendEncodedSyncPData:(id)arg1 toURL:(id)arg2 withTimeout:(id)arg3;
- (void)invokeMethodOnDelegates:(SEL)arg1 withObject:(id)arg2;
- (void)addDelegate:(id)arg1;
- (void)handleRpcMessage:(id)arg1;
- (void)handleProtocolMessage:(id)arg1;
- (void)sendRPCRequestPrivate:(id)arg1;
- (void)sendRPCRequest:(id)arg1;
- (void)onProtocolMessageReceived:(id)arg1;
- (void)handleProtocolSessionStarted:(unsigned char)arg1 sessionID:(unsigned char)arg2 version:(unsigned char)arg3;
- (void)onError:(id)arg1 exception:(id)arg2;
- (void)onProtocolClosed;
- (void)onProtocolOpened;
- (void)startRPCSession;
- (void)destroyHandshakeTimer;
- (void)handshakeTimerFired;
- (id)proxyVersion;
- (id)getProxyVersion;
- (id)getProtocol;
- (id)getTransport;
- (void)notifyProxyClosed;
- (void)dealloc;
- (void)dispose;
- (void)destructObjects;
- (id)initWithTransport:(id)arg1 protocol:(id)arg2 delegate:(id)arg3;

@end

