//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ClusterInfo.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface FolderInfo : ClusterInfo
{
    int seq;
    unsigned long folder_QQ;
    int folder_ID;
    long long tid;
    unsigned long folder_TimeTag;
    int folder_Count;
    int folder_offline_Count;
    BOOL folder_Update;
    int folder_Op;
    BOOL editable;
    unsigned long folder_create_Time;
    int folder_synType;
    int folder_order;
    NSMutableArray *folderSongs;
    NSString *folder_oldName;
    int eFolderSongStatus;
    BOOL folder_AutoSyn;
    NSString *folder_from;
    int folder_type;
    unsigned long folder_fromqq;
    NSString *folder_fromIcon;
    NSString *folder_Icon;
    NSString *folderDesc;
    NSString *folderTagIds;
    NSString *folderTagNames;
    int _folder_subType;
}

+ (id)getAutoSavedFolder;
+ (void)addXmlNode:(struct _xmlNode *)arg1 FolderInfo:(id)arg2 IncludeName:(BOOL)arg3;
+ (unsigned int)firstSongInfoInFolderSongs:(id)arg1 songInfo:(id)arg2;
+ (BOOL)isUserOnlineFolderByUin:(unsigned long)arg1 folderId:(int)arg2 foldType:(int)arg3;
+ (BOOL)isUserLocalFolderByUin:(unsigned long)arg1 folderId:(int)arg2 foldType:(int)arg3;
+ (BOOL)isUserFolderByUin:(unsigned long)arg1 folderId:(int)arg2 foldType:(int)arg3;
+ (BOOL)isTaoFolderByUin:(unsigned long)arg1 folderId:(int)arg2 foldType:(int)arg3;
+ (BOOL)isSystemFolderByUin:(unsigned long)arg1 folderId:(int)arg2 foldType:(int)arg3;
+ (id)getKeyByUin:(unsigned long)arg1 FolderId:(int)arg2 FolderType:(int)arg3 Tid:(long long)arg4;
+ (id)getKey:(id)arg1;
@property int folder_subType; // @synthesize folder_subType=_folder_subType;
@property(retain) NSString *folderTagNames; // @synthesize folderTagNames;
@property(retain) NSString *folderTagIds; // @synthesize folderTagIds;
@property(retain) NSString *folderDesc; // @synthesize folderDesc;
@property(retain) NSString *folder_fromIcon; // @synthesize folder_fromIcon;
@property unsigned long folder_fromqq; // @synthesize folder_fromqq;
@property int folder_type; // @synthesize folder_type;
@property(retain) NSString *folder_from; // @synthesize folder_from;
@property(retain) NSString *folder_oldName; // @synthesize folder_oldName;
@property int eFolderSongStatus; // @synthesize eFolderSongStatus;
@property(retain) NSMutableArray *folderSongs; // @synthesize folderSongs;
@property int folder_order; // @synthesize folder_order;
@property int folder_synType; // @synthesize folder_synType;
@property unsigned long folder_create_Time; // @synthesize folder_create_Time;
@property BOOL folder_AutoSyn; // @synthesize folder_AutoSyn;
@property BOOL editable; // @synthesize editable;
@property int folder_Op; // @synthesize folder_Op;
@property BOOL folder_Update; // @synthesize folder_Update;
@property int folder_offline_Count; // @synthesize folder_offline_Count;
@property int folder_Count; // @synthesize folder_Count;
@property unsigned long folder_TimeTag; // @synthesize folder_TimeTag;
@property long long tid; // @synthesize tid;
@property int folder_ID; // @synthesize folder_ID;
@property(readonly) unsigned long folder_QQ; // @synthesize folder_QQ;
@property int seq; // @synthesize seq;
- (void).cxx_destruct;
- (id)cloneFolderSongs;
- (BOOL)isLoveFolderOfCurrentUser;
- (BOOL)isLoveFolderOfUin:(unsigned long long)arg1;
- (BOOL)isAutoSavedFolder;
- (BOOL)isAutoSavingFolder;
- (BOOL)isRecentPlayFolder;
- (BOOL)isDownloadedFolder;
- (BOOL)isDownloadingFolder;
- (BOOL)isUserOnlineFolder;
- (BOOL)isUserLocalFolder;
- (BOOL)isForbitByCreator;
- (BOOL)isDeletedByCreator;
- (BOOL)isTaoFolder;
- (BOOL)isUserFolder;
- (BOOL)isSystemFolder;
- (int)compareByOrder:(id)arg1;
- (void)setFolderIcon:(id)arg1 preferLocalPath:(BOOL)arg2;
@property(readonly) NSString *folder_Icon; // @synthesize folder_Icon;
- (int)compareByCreateTime:(id)arg1;
- (int)compareByFolderId:(id)arg1;
- (BOOL)isEqualContent:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)folder_Name;
- (void)setFolder_Name:(id)arg1;
- (id)getCreator;
- (id)translateToSongListItem;
- (void)internalInit;
- (id)initWithQQ:(unsigned long)arg1 folderId:(int)arg2 FolderType:(int)arg3 Tid:(long long)arg4;
- (id)init;

@end

