//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface FolderIcoUploadConfig : NSObject
{
    BOOL _uploadFailed;
    NSString *_originalURL;
    NSMutableArray *_uploadHistorys;
}

@property BOOL uploadFailed; // @synthesize uploadFailed=_uploadFailed;
@property(retain) NSMutableArray *uploadHistorys; // @synthesize uploadHistorys=_uploadHistorys;
@property(retain) NSString *originalURL; // @synthesize originalURL=_originalURL;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

