//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTabVC.h"

#import "ImageManagerDelegate.h"
#import "InputDelegate.h"
#import "MusicListCategoriesVCDelegate.h"

@class AlbumIntroduction, KSImagePickerController, NSString, SongListItem, UIImage;

__attribute__((visibility("hidden")))
@interface FolderSongsDetailTabVC : BaseTabVC <ImageManagerDelegate, InputDelegate, MusicListCategoriesVCDelegate>
{
    BOOL bCanEdit;
    BOOL _isRankCommentTab;
    SongListItem *_songListItem;
    UIImage *_saveImage;
    id <SongListEditDegate> _editDelegate;
    int _editType;
    AlbumIntroduction *_albumIntrodution;
    SongListItem *_songListItemBackUp;
    KSImagePickerController *_imagePicker;
}

@property(retain, nonatomic) KSImagePickerController *imagePicker; // @synthesize imagePicker=_imagePicker;
@property(retain, nonatomic) SongListItem *songListItemBackUp; // @synthesize songListItemBackUp=_songListItemBackUp;
@property(retain, nonatomic) AlbumIntroduction *albumIntrodution; // @synthesize albumIntrodution=_albumIntrodution;
@property(nonatomic) int editType; // @synthesize editType=_editType;
@property(nonatomic) __weak id <SongListEditDegate> editDelegate; // @synthesize editDelegate=_editDelegate;
@property(retain, nonatomic) UIImage *saveImage; // @synthesize saveImage=_saveImage;
@property(nonatomic) BOOL isRankCommentTab; // @synthesize isRankCommentTab=_isRankCommentTab;
@property(retain, nonatomic) SongListItem *songListItem; // @synthesize songListItem=_songListItem;
@property(nonatomic) BOOL bCanEdit; // @synthesize bCanEdit;
- (void).cxx_destruct;
- (id)getDetailUrl;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (id)viewControllerToPresentImagePicker;
- (void)actionSheet:(id)arg1 actionSheetButtonClickedAtIndex:(int)arg2;
- (id)addFolderIcoUploadFailedImageView:(id)arg1 indexPath:(id)arg2;
- (BOOL)_canEditAlbumImage;
- (void)_showSelectImageFromSystemLibrary;
- (void)imageSavedToPhotosAlbum:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveImageToLocol:(id)arg1;
- (void)_showFullScreenImage:(id)arg1 indexPath:(id)arg2;
- (void)_touchUpInsideImage:(id)arg1;
- (id)_parentCell:(id)arg1;
- (void)onNotifyFolderPictureChanged:(id)arg1;
- (void)_onNotifyColorStyleChanged:(id)arg1;
- (id)_emptyTagMsg;
- (void)_albumIntroductionDidUpdate:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)gotoTag:(id)arg1;
- (void)updateAlubmImage;
- (id)createCommonLineView;
- (void)_onAlbumImageClicked:(id)arg1;
- (BOOL)isChangeAnyInfo;
- (void)saveListInfo;
- (void)willResignCurrentTab;
- (void)back:(id)arg1;
- (void)inputView:(id)arg1 inPutFinishWithResult:(id)arg2;
- (void)editDesc;
- (void)categoriesVCDidFinish:(id)arg1;
- (void)v4CategoriesVCDidFinished:(id)arg1;
- (id)musicListCategoriesFromChannelV4Categories:(id)arg1;
- (id)channelV4CategoriesFromMusicListCategories:(id)arg1;
- (void)editTag;
- (void)editTitle;
- (id)inputView:(id)arg1 checkInputResult:(id)arg2;
- (void)updateUI;
- (id)songDescription;
- (BOOL)isNeedAddBottomLine;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)moreRootCellRowForTableView:(id)arg1 AtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)getBgName;
- (int)vcType;
- (void)viewDidLoad;
- (struct UIEdgeInsets)getScrollViewOriginOffset;
- (void)viewDidPop;
- (void)reFresh;
- (id)songsTableView;
- (void)newTable;
- (void)loadView;
- (BOOL)isNeedSongTableView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

