//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ASIFormDataRequest, NSMutableData, NSString;

__attribute__((visibility("hidden")))
@interface FolderIcoUploader : NSObject
{
    BOOL _serverRefused;
    NSString *_localPath;
    NSMutableData *_receivedData;
    ASIFormDataRequest *_request;
    CDUnknownBlockType _block;
    NSString *_url;
}

@property(nonatomic) BOOL serverRefused; // @synthesize serverRefused=_serverRefused;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) ASIFormDataRequest *request; // @synthesize request=_request;
@property(copy, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(copy, nonatomic) NSString *localPath; // @synthesize localPath=_localPath;
- (void).cxx_destruct;
- (void)callBack;
- (void)parseReceivedData;
- (id)getProcessedUrl;
- (id)getUrl;
- (id)createUploadRequest;
- (void)uploadWithBlock:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithLocalPath:(id)arg1;

@end

