//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ProtocolHostDelegate.h"

@class NSArray, QQFriendGroupInfoProtocol, UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface FollowQQFriendsVC : SkinViewController <ProtocolHostDelegate>
{
    QQFriendGroupInfoProtocol *_protocol;
    NSArray *_groupInfos;
    UIActivityIndicatorView *_acView;
}

@property(retain, nonatomic) UIActivityIndicatorView *acView; // @synthesize acView=_acView;
@property(retain, nonatomic) NSArray *groupInfos; // @synthesize groupInfos=_groupInfos;
@property(retain, nonatomic) QQFriendGroupInfoProtocol *protocol; // @synthesize protocol=_protocol;
- (void).cxx_destruct;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)getBgName;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidPop;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

