//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ImageManagerDelegate.h"
#import "ProfileViewControllerDelegate.h"
#import "QMTabBarDelegate.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface FollowsViewController : SkinViewController <ImageManagerDelegate, ProfileViewControllerDelegate, QMTabBarDelegate>
{
    BOOL shouldUpdateFollowList;
    BOOL singerNewborn;
    BOOL userNewborn;
    BOOL _loadingMore;
    BOOL _bUserEvent;
    int currentIndex;
    int SingerTotalCount;
    int UserTotalCount;
    int _followsTotalCount;
    NSMutableArray *_FollowsList;
    int _selectIndex;
    long long _visitUin;
}

@property(nonatomic) int selectIndex; // @synthesize selectIndex=_selectIndex;
@property(nonatomic) BOOL bUserEvent; // @synthesize bUserEvent=_bUserEvent;
@property(retain, nonatomic) NSMutableArray *FollowsList; // @synthesize FollowsList=_FollowsList;
@property(nonatomic) BOOL loadingMore; // @synthesize loadingMore=_loadingMore;
@property(nonatomic) int followsTotalCount; // @synthesize followsTotalCount=_followsTotalCount;
@property(nonatomic) long long visitUin; // @synthesize visitUin=_visitUin;
@property(nonatomic) int UserTotalCount; // @synthesize UserTotalCount;
@property(nonatomic) int SingerTotalCount; // @synthesize SingerTotalCount;
@property(nonatomic) int currentIndex; // @synthesize currentIndex;
@property(nonatomic) BOOL userNewborn; // @synthesize userNewborn;
@property(nonatomic) BOOL singerNewborn; // @synthesize singerNewborn;
- (void).cxx_destruct;
- (void)onNotifyUpdateFollowList;
- (void)doMoreAboutTabBar:(id)arg1;
- (void)segmentedControlValueChanged:(id)arg1;
- (void)cancelFollowSinger:(long long)arg1;
- (void)cancelFollowUser:(long long)arg1;
- (void)touchDown:(id)arg1 itemAtIndex:(unsigned int)arg2;
- (void)touchUpInside:(id)arg1 itemAtIndex:(unsigned int)arg2;
- (id)selectedImageView:(id)arg1;
- (id)selectetdItemImage:(id)arg1 atIndex:(unsigned int)arg2;
- (id)pressedItemImage:(id)arg1 atIndex:(unsigned int)arg2;
- (id)backgroundImage:(id)arg1;
- (id)accessibilityLabel:(id)arg1 atIndex:(unsigned int)arg2;
- (id)imageFor:(id)arg1 atIndex:(unsigned int)arg2;
- (BOOL)moreDataIsLoading:(id)arg1;
- (void)processingLoadMoreAction:(id)arg1;
- (BOOL)hasMoreDataInTableView:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)showTable;
- (void)reFresh;
- (void)_showTabInfoViewWithTitle:(id)arg1 subtitle:(id)arg2 tapSelector:(SEL)arg3 iconName:(id)arg4;
- (void)_showTabLoadingView;
- (void)_blankMethod;
- (BOOL)isGuest;
- (void)onNotifyFollowsListUpdate:(id)arg1;
- (void)showEmptyFollows:(int)arg1;
- (void)viewDidPop;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)moreButtonDidClick:(id)arg1;
- (void)_hideTabLoadingView;
- (void)_loadUserList;
- (void)_loadSingerList;
- (void)refreshTable;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(BOOL)arg1;
- (id)createTableHeaderView;
- (void)enterFollowMoreVC;
- (void)setSubviewsSelected:(BOOL)arg1;
- (void)setSubviewsNotSelected;
- (void)setSubviewsSelected;
- (void)freshHeaderSeprateLine;
- (void)buildTableHeaderView;
- (void)_buildHeaderTabBar;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithUin:(long long)arg1 totalFollowsCount:(int)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

