//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChannelCell.h"

#import "ImageManagerDelegate.h"

@class BEActivityView, FriendShareExpInfo, NSString, QMBothSidesCircularProgressView, SongInfo, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface ForMeShareSong_Style : ChannelCell <ImageManagerDelegate>
{
    BOOL _bLoading;
    SongInfo *_songInfo;
    FriendShareExpInfo *_expInfo;
    UIButton *_playPauseBtn;
    UILabel *_songNmLabel;
    UILabel *_singerAlubmLabel;
    UIImageView *_loadingBgView;
    UIImageView *_loadingActView;
    BEActivityView *_activityView;
    UIActivityIndicatorView *_bufferActivityView;
    QMBothSidesCircularProgressView *_processView;
    id <ForMelayoutDelegate> _layoutCellDelegate;
}

+ (struct CGSize)cellSize;
@property(nonatomic) __weak id <ForMelayoutDelegate> layoutCellDelegate; // @synthesize layoutCellDelegate=_layoutCellDelegate;
@property(nonatomic) BOOL bLoading; // @synthesize bLoading=_bLoading;
@property(retain, nonatomic) QMBothSidesCircularProgressView *processView; // @synthesize processView=_processView;
@property(retain, nonatomic) UIActivityIndicatorView *bufferActivityView; // @synthesize bufferActivityView=_bufferActivityView;
@property(retain, nonatomic) BEActivityView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIImageView *loadingActView; // @synthesize loadingActView=_loadingActView;
@property(retain, nonatomic) UIImageView *loadingBgView; // @synthesize loadingBgView=_loadingBgView;
@property(retain, nonatomic) UILabel *singerAlubmLabel; // @synthesize singerAlubmLabel=_singerAlubmLabel;
@property(retain, nonatomic) UILabel *songNmLabel; // @synthesize songNmLabel=_songNmLabel;
@property(retain, nonatomic) UIButton *playPauseBtn; // @synthesize playPauseBtn=_playPauseBtn;
@property(retain, nonatomic) FriendShareExpInfo *expInfo; // @synthesize expInfo=_expInfo;
@property(retain, nonatomic) SongInfo *songInfo; // @synthesize songInfo=_songInfo;
- (void).cxx_destruct;
- (void)setBScrolling:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setScrollProgress:(float)arg1;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)_loadImage;
- (id)defaultImage;
- (void)refreshView;
- (BOOL)isPlayingThisSong;
- (void)refreshPlayState;
- (void)playStatusDidChange:(id)arg1;
- (void)playListDidChange:(id)arg1;
- (void)playOrPause:(id)arg1;
- (void)setupCustomizedUI;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

