//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ForMeBaseData.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class AlbumInfo, ChannelCreator, ChannelItem, DissInfo, SingerCluster;

__attribute__((visibility("hidden")))
@interface ForMeRecData : ForMeBaseData <NSCopying, NSCoding>
{
    BOOL _hasFollowed;
    BOOL _hasFaved;
    ChannelCreator *_creator;
    ChannelCreator *_owner;
    SingerCluster *_singer;
    int _orderNum;
    AlbumInfo *_albumInfo;
    DissInfo *_dissInfo;
    ChannelCreator *_recUser;
    ChannelItem *_shareItem;
}

+ (void)translateForMeDataFromJson:(id)arg1 toRecData:(id)arg2;
+ (id)translateForMeDataFromJsonData:(id)arg1;
@property(nonatomic) BOOL hasFaved; // @synthesize hasFaved=_hasFaved;
@property(nonatomic) BOOL hasFollowed; // @synthesize hasFollowed=_hasFollowed;
@property(retain, nonatomic) ChannelItem *shareItem; // @synthesize shareItem=_shareItem;
@property(retain, nonatomic) ChannelCreator *recUser; // @synthesize recUser=_recUser;
@property(retain, nonatomic) DissInfo *dissInfo; // @synthesize dissInfo=_dissInfo;
@property(retain, nonatomic) AlbumInfo *albumInfo; // @synthesize albumInfo=_albumInfo;
@property(nonatomic) int orderNum; // @synthesize orderNum=_orderNum;
@property(retain, nonatomic) SingerCluster *singer; // @synthesize singer=_singer;
@property(retain, nonatomic) ChannelCreator *owner; // @synthesize owner=_owner;
@property(retain, nonatomic) ChannelCreator *creator; // @synthesize creator=_creator;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)typeLogo;
- (id)typeTxt;
- (id)mainURL;
- (id)subTitle;
- (id)title;
- (void)setSongListKey;

@end

