//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface ForMeHelper : NSObject
{
}

+ (id)formatedCreatorName:(id)arg1;
+ (id)translateOwnerFromJson:(id)arg1;
+ (id)translatereRecUserFromJson:(id)arg1;
+ (id)translateShareUserFromJson:(id)arg1;
+ (id)translateSingerFromJson:(id)arg1;
+ (id)getDicFromObject:(id)arg1;

@end

