//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CategoryChannelData.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class ListBase, QQFriend;

__attribute__((visibility("hidden")))
@interface FriendShareData : CategoryChannelData <NSCopying, NSCoding>
{
    BOOL _hasMore;
    BOOL _bLoading;
    ListBase *_songList;
    QQFriend *_qqFriend;
    int _nextFrdIndex;
}

+ (id)translateFromJsonData:(id)arg1 baseData:(id)arg2;
@property(nonatomic) int nextFrdIndex; // @synthesize nextFrdIndex=_nextFrdIndex;
@property(nonatomic) BOOL bLoading; // @synthesize bLoading=_bLoading;
@property(nonatomic) BOOL hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) QQFriend *qqFriend; // @synthesize qqFriend=_qqFriend;
@property(retain, nonatomic) ListBase *songList; // @synthesize songList=_songList;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithLayoutStyle:(int)arg1;
- (id)init;
- (id)zanReasonAtIndex:(int)arg1;
- (id)reasonForIndex:(int)arg1;

@end

