//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TreeNode, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface FriendFolderCell : UITableViewCell
{
    UIButton *btnExpand;
    UILabel *label;
    SEL onExpand;
    TreeNode *treeNode;
    id owner;
}

@property(retain, nonatomic) UIButton *btnExpand; // @synthesize btnExpand;
@property(retain, nonatomic) UILabel *label; // @synthesize label;
@property(nonatomic) __weak id owner; // @synthesize owner;
@property(nonatomic) SEL onExpand; // @synthesize onExpand;
- (void).cxx_destruct;
- (void)setTreeNode:(id)arg1;
- (void)onExpand:(id)arg1;

@end

