//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ClickInfo, ExposureInfo, GDTAD, GDTLoadAdRequest, GDTNetRequest, NSArray, NSData, NSString;

@protocol GDTAdProtoDelegate <NSObject>
- (GDTNetRequest *)encodeCloseRequest:(GDTAD *)arg1 clickInfo:(ClickInfo *)arg2;
- (NSString *)encodeLinkClickUrl:(GDTAD *)arg1 clickInfo:(ClickInfo *)arg2;
- (GDTNetRequest *)encodeExposureRequest:(NSString *)arg1 exposureInfo:(ExposureInfo *)arg2;
- (NSArray *)decodeLoadAdResponse:(NSData *)arg1 posId:(NSString *)arg2;
- (GDTNetRequest *)encodeLoadAdRequest:(GDTLoadAdRequest *)arg1;
@end

