//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDTAD.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSDate, UIImage;

__attribute__((visibility("hidden")))
@interface GDTAdItem : GDTAD <NSCoding, NSCopying>
{
    BOOL _isExposured;
    UIImage *_bannerImage;
    NSDate *_expireDate;
}

+ (id)parseGDTAdItems:(id)arg1;
@property(nonatomic) BOOL isExposured; // @synthesize isExposured=_isExposured;
@property(retain, nonatomic) NSDate *expireDate; // @synthesize expireDate=_expireDate;
@property(retain, nonatomic) UIImage *bannerImage; // @synthesize bannerImage=_bannerImage;
- (void).cxx_destruct;
- (BOOL)isExpired;
- (id)imageFileName;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

