//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol GDTBannerProtocolCallback <NSObject>
- (void)loadGDTBannerFailed:(int)arg1 posId:(NSString *)arg2 appKey:(NSString *)arg3;
- (void)loadGDTBannerSuccessed:(NSArray *)arg1 posId:(NSString *)arg2 appKey:(NSString *)arg3;
@end

