//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GDTBannerView;

@protocol GDTBannerServiceProtocol <NSObject>
- (void)gdtBannerViewShouldClose:(GDTBannerView *)arg1;
- (void)gdtBannerViewDidLoad:(GDTBannerView *)arg1;

@optional
- (void)gdtBannerViewShouldRefreshFrame:(GDTBannerView *)arg1;
@end

