//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ClickInfo, GDTAdItem, GDTBannerView, NSString;

@protocol GDTBannerViewDelegate <NSObject>
- (void)gdtBannerViewShouldClose:(GDTBannerView *)arg1 clickInfo:(ClickInfo *)arg2 item:(GDTAdItem *)arg3;
- (void)gdtBannerViewTapped:(GDTBannerView *)arg1 clickInfo:(ClickInfo *)arg2 targetUrl:(NSString *)arg3 item:(GDTAdItem *)arg4;
@end

