//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GDTAD, NSString;

@protocol GDTClickCallback <NSObject>
- (void)onClickFail:(int)arg1;
- (void)onClickSuccess:(GDTAD *)arg1 targetUrl:(NSString *)arg2;
@end

