//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GDTNetCallback.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface GDTCGICallback : NSObject <GDTNetCallback>
{
    NSString *_posId;
    id <GDTAdProtoDelegate> _adProtoDelegate;
    id <GDTLoadAdCallback> _loadAdCallback;
}

- (void).cxx_destruct;
- (void)onFail:(int)arg1;
- (void)onSuccess:(id)arg1;
- (id)initWithPosId:(id)arg1 adProtoDelegate:(id)arg2 loadAdCallback:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

