//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface GDTPlainNetRequest : NSObject
{
    NSString *_url;
    NSDictionary *_paras;
    id <GDTPlainNetRequestCallback> _callback;
}

@property(retain, nonatomic) id <GDTPlainNetRequestCallback> callback; // @synthesize callback=_callback;
@property(copy, nonatomic) NSDictionary *paras; // @synthesize paras=_paras;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;

@end

