//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GDTNetClientDelegate.h"

@class NSOperationQueue, NSString;

__attribute__((visibility("hidden")))
@interface GDTPlainNetClient : NSObject <GDTNetClientDelegate>
{
    NSOperationQueue *requestQueue;
}

+ (id)instance;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedGDTPlainNetClient;
- (void).cxx_destruct;
- (void)get:(id)arg1 callback:(id)arg2;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

