//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface GDTReportProtocol : ProtocolBaseJason
{
    NSString *_reportUrl;
}

@property(retain, nonatomic) NSString *reportUrl; // @synthesize reportUrl=_reportUrl;
- (void).cxx_destruct;
- (id)getUrl;

@end

