//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "MusicGeneSongCellDelegate.h"

@class ChannelCreator, GeneDetailInfoLoader, GeneRoundButton, MusicGene, NSString, ProfileViewController;

__attribute__((visibility("hidden")))
@interface GeneSongListViewController : SkinViewController <MusicGeneSongCellDelegate>
{
    ProfileViewController *_profileVC;
    ChannelCreator *_user;
    MusicGene *_musicGene;
    id _delegate;
    GeneDetailInfoLoader *_geneInfoLoader;
    GeneRoundButton *_geneView;
}

@property(retain, nonatomic) GeneRoundButton *geneView; // @synthesize geneView=_geneView;
@property(retain, nonatomic) GeneDetailInfoLoader *geneInfoLoader; // @synthesize geneInfoLoader=_geneInfoLoader;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) MusicGene *musicGene; // @synthesize musicGene=_musicGene;
@property(readonly, nonatomic) ChannelCreator *user; // @synthesize user=_user;
@property(nonatomic) __weak ProfileViewController *profileVC; // @synthesize profileVC=_profileVC;
- (void).cxx_destruct;
- (id)trimString:(id)arg1 byMaxLength:(int)arg2;
- (id)userName;
- (id)setupHeaderView;
- (BOOL)isSelfGene;
- (id)allVCTypes;
- (void)didClickUserHeaderInCell:(id)arg1;
- (void)didClickHeartBtnInCell:(id)arg1;
- (void)didClickPlayBtnInCell:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)showBannerTips:(id)arg1 WithIcon:(int)arg2 Force:(BOOL)arg3;
- (void)handleHeartBtnEvent:(id)arg1;
- (void)onNotifyPlayingStatusChange:(id)arg1;
- (int)getPlayingIndexIfPlayingCurrentList:(int)arg1;
- (void)onNotifyPlayingSongChange:(id)arg1;
- (BOOL)isCurrentListPlaying;
- (id)allSongs;
- (id)list;
- (id)listData;
- (int)vcType;
- (float)infoViewTopOffset;
- (void)hideAll;
- (void)reFresh;
- (void)loadView;
- (id)initWithUser:(id)arg1 andMusicGene:(id)arg2 andDelegate:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

