//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class HGPageView, HGTouchView, NSIndexSet, NSMutableArray, NSMutableDictionary, NSString, UIScrollView;

__attribute__((visibility("hidden")))
@interface HGPageScrollView : UIView <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    id <HGPageScrollViewDelegate> _delegate;
    id <HGPageScrollViewDataSource> _dataSource;
    UIScrollView *_scrollView;
    HGTouchView *_scrollViewTouch;
    int _numberOfPages;
    int _numberOfFreshPages;
    struct _NSRange _visibleIndexes;
    NSMutableArray *_visiblePages;
    NSMutableArray *_deletedPages;
    NSMutableDictionary *_reusablePages;
    HGPageView *_selectedPage;
    BOOL _isPendingScrolledPageUpdateNotification;
    NSIndexSet *indexesBeforeVisibleRange;
    NSIndexSet *indexesWithinVisibleRange;
    NSIndexSet *indexesAfterVisibleRange;
}

@property(retain, nonatomic) NSIndexSet *indexesAfterVisibleRange; // @synthesize indexesAfterVisibleRange;
@property(retain, nonatomic) NSIndexSet *indexesWithinVisibleRange; // @synthesize indexesWithinVisibleRange;
@property(retain, nonatomic) NSIndexSet *indexesBeforeVisibleRange; // @synthesize indexesBeforeVisibleRange;
@property(nonatomic) __weak id <HGPageScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <HGPageScrollViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)prepareHidePageScrollView;
- (void)handleTapGestureFrom:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)swiffCurrentPage;
- (void)highlightCurrentPage;
- (id)dequeueReusablePageWithIdentifier:(id)arg1;
- (void)setTransform:(float)arg1 forObstructionLayerOfPage:(id)arg2;
- (void)setOpacity:(float)arg1 forObstructionLayerOfPage:(id)arg2;
- (void)setTransformForPage:(id)arg1;
- (void)setAlphaForPage:(id)arg1;
- (void)updateVisiblePages;
- (void)updateScrolledPage:(id)arg1 index:(int)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setNumberOfPages:(int)arg1;
- (void)reloadPagesAtIndexes:(id)arg1;
- (void)deletePagesAtIndexes:(id)arg1 animated:(BOOL)arg2;
- (void)insertPagesAtIndexes:(id)arg1 animated:(BOOL)arg2;
- (void)prepareForDataUpdate:(int)arg1 withIndexSet:(id)arg2;
- (void)shiftPage:(id)arg1 withOffset:(float)arg2;
- (void)setFrameForPage:(id)arg1 atIndex:(int)arg2;
- (void)removePagesFromScrollView:(id)arg1 animated:(BOOL)arg2;
- (void)insertPageInScrollView:(id)arg1 atIndex:(int)arg2 animated:(BOOL)arg3;
- (void)addPageToScrollView:(id)arg1 atIndex:(int)arg2;
- (id)loadPageAtIndex:(int)arg1 insertIntoVisibleIndex:(int)arg2;
- (void)reloadData;
- (void)reloadData:(int)arg1;
- (void)preparePage:(id)arg1;
- (void)scrollToPageAtIndex:(int)arg1 animated:(BOOL)arg2;
- (int)indexForVisiblePage:(id)arg1;
- (int)indexForSelectedPage;
- (id)pageSelected;
- (id)pageAtIndex:(int)arg1;
- (int)numberOfPages;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

