//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HttpFactory : NSObject
{
}

+ (void)setHttpFactory:(id)arg1;
+ (id)getIntanceHttpFactory;
- (void)dealloc;
- (id)creatHttpResovleByRequstInfo:(id)arg1;
- (id)creatHttpByRequestInfo:(id)arg1;

@end

