//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSDictionary, UIImageView;

@interface HVMPInfoButton : UIButton
{
    NSDictionary *_buttonInfo;
    UIImageView *_markView;
    UIImageView *_updateMarkView;
    UIImageView *_hboFreeMarkView;
}

@property(retain, nonatomic) NSDictionary *buttonInfo; // @synthesize buttonInfo=_buttonInfo;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

