//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "HVMPTVEpisodeDelegate.h"
#import "QLRequestModelDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class HVMPRightSectionHeaderView, KKMediaRootViewController, KKVideoInfo, NSArray, NSDate, NSMutableArray, NSString, QLASIHTTPRequest, QLActivityLabel, QLCoverRelatedModel, QLErrorView, QLFooterDragRefreshView, QLHeaderDragRefreshView, QLMainMovieControlView, UITableView;

@interface HVMPRightListView : UIView <QLRequestModelDelegate, UITableViewDataSource, UITableViewDelegate, HVMPTVEpisodeDelegate>
{
    int lastSelectedVideoIndex;
    BOOL loaded;
    BOOL hideHeaderView;
    int loadingStatus;
    BOOL isLastRequestFinished;
    NSMutableArray *episodeInfoList;
    NSMutableArray *episodeTitles;
    NSMutableArray *episodeIndices;
    NSMutableArray *episodeFlags;
    NSMutableArray *trailerTitles;
    NSMutableArray *trailerIndices;
    int lastSelectedEpisodeIndex;
    NSMutableArray *updateFlags;
    NSMutableArray *hboFreeFlags;
    NSMutableArray *aryRelatedMovieItems;
    NSMutableArray *varietyMovieItems;
    int curRelyYearIndex;
    int curRelyMonthIndex;
    int topRelyYearIndex;
    int topRelyMonthIndex;
    int bottomRelyYearIndex;
    int bottomRelyMonthIndex;
    int curVarietyCoverCellRow;
    int curVarietyEpisodeCellRow;
    int loadedRelyMonthCount;
    BOOL hasLoadedVarietyEpisodes;
    NSArray *varietyRelys;
    NSDate *programRequestTime;
    NSMutableArray *programList;
    int currentLiveDayOffset;
    QLASIHTTPRequest *dataRequest;
    QLASIHTTPRequest *relateRequest;
    HVMPRightSectionHeaderView *headerView;
    QLActivityLabel *loadingView;
    QLFooterDragRefreshView *_footerView;
    QLHeaderDragRefreshView *_headerView;
    UIView *_backgroundView;
    BOOL _isLoadNextVarietyLastTime;
    QLCoverRelatedModel *_relatedModel;
    NSMutableArray *makeshiftForLive;
    BOOL _resetWithDetailInfo;
    BOOL _networkAvailable;
    BOOL _shortRelateRequested;
    KKMediaRootViewController *mediaRootViewController;
    UITableView *_tableView;
    NSMutableArray *playBackAry;
    QLErrorView *errorView;
    KKVideoInfo *videoInfo;
    QLMainMovieControlView *_movieMask;
    int _listStyle;
}

@property BOOL shortRelateRequested; // @synthesize shortRelateRequested=_shortRelateRequested;
@property BOOL networkAvailable; // @synthesize networkAvailable=_networkAvailable;
@property BOOL resetWithDetailInfo; // @synthesize resetWithDetailInfo=_resetWithDetailInfo;
@property(nonatomic) int listStyle; // @synthesize listStyle=_listStyle;
@property(nonatomic) QLMainMovieControlView *movieMask; // @synthesize movieMask=_movieMask;
@property(retain, nonatomic) KKVideoInfo *videoInfo; // @synthesize videoInfo;
@property(retain, nonatomic) QLErrorView *errorView; // @synthesize errorView;
@property(retain, nonatomic) NSMutableArray *playBackAry; // @synthesize playBackAry;
@property(nonatomic) KKMediaRootViewController *mediaRootViewController; // @synthesize mediaRootViewController;
- (id)packageTheDateAndTime:(id)arg1;
- (id)packageFromArray:(id)arg1;
- (BOOL)checkResponseStatus:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)configureFooterDragRefreshView;
- (void)configureHeaderDragRefreshView;
- (BOOL)isVideoDownloadedAtSubIndex:(int)arg1 subName:(id)arg2;
- (BOOL)episodeNetworkAvaiable;
- (void)episodeButtonSelected:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)coverDetailReceived:(id)arg1;
- (void)requestDidCancelLoad:(id)arg1;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidStartLoad:(id)arg1;
- (void)requestDidFinishLoad:(id)arg1;
- (void)requestVarietyRely:(BOOL)arg1;
- (BOOL)hasLoadedLastPage;
- (BOOL)hasLoadedFirstPage;
- (void)requestLiveProgramsForDay:(int)arg1;
- (void)syncSelectedEpisode;
- (BOOL)hasNextVideo;
- (BOOL)playNextCover;
- (void)resetList;
- (void)requestModelDidFinishLoad:(id)arg1;
- (void)requestMovieRelated;
- (void)loadList;
- (void)showEmpty:(id)arg1;
- (void)showLoading:(BOOL)arg1;
- (void)loadVarietyMovieItem:(id)arg1;
- (void)hideRightListView;
- (void)hideRightListViewAction;
- (int)currentEpisodeIndex;
- (int)current;
- (BOOL)isSimpleVideo;
- (int)videoType;
- (id)mainController;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

