//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ApKeyChangeObserver.h"
#import "HttpControlDelegate.h"
#import "IAppIAPPayDelegate.h"
#import "ILogDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITotalViewControllerDelegate.h"

@class NSDate, UITotalViewController;

@interface IAPPayHelper : NSObject <HttpControlDelegate, ILogDelegate, IAppIAPPayDelegate, UITotalViewControllerDelegate, UIAlertViewDelegate, ApKeyChangeObserver>
{
    id <IAPPayDelegate> delegate;
    id <IAPGetBalanceDelegate> getBalanceDelegate;
    id <IAPGetProductListDelegate> getProductDelegate;
    BOOL _alertWaiting;
    int _changeKeyStateLastTime;
    UITotalViewController *_payListViewCtrler;
    NSDate *_lastLaunchUITime;
    id <IAPPayUIDelegate> _uiDelegate;
}

+ (void)setIsEnLog:(unsigned char)arg1;
+ (id)getVersion;
+ (void)setLocal:(id)arg1;
+ (BOOL)judgeIsCanPay;
+ (id)getIntanceIapHelp;
@property(nonatomic) id <IAPGetProductListDelegate> GetProductDelagate; // @synthesize GetProductDelagate=getProductDelegate;
@property(nonatomic) id <IAPPayUIDelegate> uiDelegate; // @synthesize uiDelegate=_uiDelegate;
@property(retain, nonatomic) NSDate *lastLaunchUITime; // @synthesize lastLaunchUITime=_lastLaunchUITime;
@property(retain, nonatomic) UITotalViewController *payListViewCtrler; // @synthesize payListViewCtrler=_payListViewCtrler;
@property(nonatomic) id <IAPGetBalanceDelegate> GetBalanceDelegate; // @synthesize GetBalanceDelegate=getBalanceDelegate;
@property(nonatomic) id <IAPPayDelegate> Delegate; // @synthesize Delegate=delegate;
- (void)onUITotalViewDidClosed;
- (void)onUITotalViewWillOpened;
- (void)onH5Page:(id)arg1 loadError:(id)arg2;
- (void)onH5Page:(id)arg1 error:(id)arg2;
- (void)onH5LoadSucess:(id)arg1;
- (void)onRefreshRepay;
- (void)onH5RequestPayProduct:(id)arg1 itemCount:(id)arg2 zoneId:(id)arg3 deposit:(BOOL)arg4 productType:(id)arg5;
- (void)onRequstPay:(id)arg1;
- (void)launchMpInfo:(id)arg1 withOpenid:(id)arg2 withOpenKey:(id)arg3 withSessionId:(id)arg4 withSessionType:(id)arg5 withPf:(id)arg6 withPfkey:(id)arg7 withZoneId:(id)arg8 withVarItem:(id)arg9;
- (void)requestGoodsInfo:(id)arg1;
- (void)restoreCompletedTransactions:(id)arg1 withOpenid:(id)arg2 withOpenKey:(id)arg3 withSessionId:(id)arg4 withSessionType:(id)arg5 withPf:(id)arg6 withPfkey:(id)arg7 withZoneId:(id)arg8 withVarItem:(id)arg9;
- (void)requestGoodsList:(id)arg1 withOpenid:(id)arg2 withOpenKey:(id)arg3 withSessionId:(id)arg4 withSessionType:(id)arg5 withPf:(id)arg6 withPfkey:(id)arg7 withZoneId:(id)arg8 withVarItem:(id)arg9 withIsDepositGameCoin:(unsigned char)arg10 withProductType:(int)arg11 withIsUi:(BOOL)arg12;
- (void)LaunchGoodsList:(id)arg1 withOpenid:(id)arg2 withOpenKey:(id)arg3 withSessionId:(id)arg4 withSessionType:(id)arg5 withPf:(id)arg6 withPfkey:(id)arg7 withZoneId:(id)arg8 withVarItem:(id)arg9 withIsDepositGameCoin:(unsigned char)arg10 withProductType:(int)arg11;
- (void)LaunchPay:(id)arg1 withOpenid:(id)arg2 withOpenKey:(id)arg3 withSessionId:(id)arg4 withSessionType:(id)arg5 withPf:(id)arg6 withPfkey:(id)arg7 withZoneId:(id)arg8 withVarItem:(id)arg9 withIsDepositGameCoin:(unsigned char)arg10 withProductType:(int)arg11 productIcon:(id)arg12 productName:(id)arg13;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)onUpdateKeyNetworkError:(int)arg1 resolve:(id)arg2 offerId:(id)arg3 openId:(id)arg4;
- (void)onKeyUpdateError:(int)arg1 message:(id)arg2 requestInfo:(id)arg3 offerId:(id)arg4 openId:(id)arg5;
- (void)onUpdateSecKey:(id)arg1 payKey:(id)arg2 keyTime:(id)arg3 originalRequestInfo:(id)arg4 offerId:(id)arg5 openId:(id)arg6;
- (void)onPayProcessEnd:(id)arg1;
- (void)onPayProcessBegin:(id)arg1;
- (void)showSandboxAlert;
- (void)dealloc;
- (void)logwithMessage:(id)arg1;
- (void)restoreGoods:(id)arg1;
- (void)receiveProductFinish;
- (id)createRequestInfo;
- (void)restoreTransaction:(id)arg1 receipt:(id)arg2;
- (void)restoreTransactionFail:(id)arg1;
- (void)failedTransaction:(id)arg1;
- (void)completeTransaction:(id)arg1 receipt:(id)arg2;
- (void)receiveProductsFail:(id)arg1;
- (void)receiveProducts:(id)arg1;
- (void)onError:(id)arg1;
- (void)onPause:(id)arg1;
- (void)onFinish:(id)arg1;
- (void)distributeGoods:(id)arg1;
- (void)payOrder:(id)arg1;
- (BOOL)checkParameter:(id)arg1 ignoreProductType:(BOOL)arg2;
- (BOOL)registerPay:(id)arg1 withOpenid:(id)arg2 withOpenKey:(id)arg3 withSessionId:(id)arg4 withSessionType:(id)arg5 withPf:(id)arg6 withPfkey:(id)arg7 withEnv:(id)arg8;
- (void)pay:(id)arg1 withOpenid:(id)arg2 withOpenKey:(id)arg3 withSessionId:(id)arg4 withSessionType:(id)arg5 withPf:(id)arg6 withPfkey:(id)arg7 withPayItem:(id)arg8 withProductId:(id)arg9 withIsDepositGameCoin:(unsigned char)arg10 withProductType:(int)arg11 withZoneId:(id)arg12 withVarItem:(id)arg13;
- (id)init;

@end

