//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DownLoadTaskDelegate.h"

@class DownLoadTask, ImageItem, NSString;

__attribute__((visibility("hidden")))
@interface ImageDownloadTask : NSObject <DownLoadTaskDelegate>
{
    BOOL _didReceiveResponse;
    id <ImageDownloadTaskDelegate> _delegate;
    ImageItem *_imageItem;
    DownLoadTask *_downloadTask;
    float _maxWaitingTime;
}

@property(nonatomic) float maxWaitingTime; // @synthesize maxWaitingTime=_maxWaitingTime;
@property(readonly, nonatomic) DownLoadTask *downloadTask; // @synthesize downloadTask=_downloadTask;
@property(readonly, nonatomic) ImageItem *imageItem; // @synthesize imageItem=_imageItem;
@property(nonatomic) __weak id <ImageDownloadTaskDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancelDownload:(id)arg1 byResponseStateCode:(int)arg2;
- (void)download:(id)arg1 error:(id)arg2;
- (void)download:(id)arg1 didDownloadSuccWithFile:(id)arg2;
- (void)download:(id)arg1 didAppendProgress:(float)arg2;
- (void)download:(id)arg1 didReceiveResponseHeaders:(id)arg2;
- (void)download:(id)arg1 didReceiveResponse:(id)arg2;
- (void)notifyImageItemDelegate;
- (BOOL)isFocusImageTask:(id)arg1;
- (void)reachMaxWaitingTime;
- (void)invalidateDownloadTask;
- (void)cancelTask;
- (BOOL)startTask;
- (id)initWithImageItem:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

