//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ImageUtils : NSObject
{
}

+ (id)buttonBgImageWithSize:(struct CGSize)arg1 image:(id)arg2 cornerRadius:(float)arg3;
+ (id)getImageWithAsset:(id)arg1;
+ (id)getFullScreenImageWithAsset:(id)arg1;
+ (id)generateThumbnail:(id)arg1 size:(struct CGSize)arg2;
+ (id)generateThumbnailWithImagePath:(id)arg1 size:(struct CGSize)arg2;

@end

