//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ProtocolHostDelegate.h"
#import "UITextFieldDelegate.h"

@class EmailReportProtocol, NSString;

__attribute__((visibility("hidden")))
@interface IPlimitVC : SkinViewController <ProtocolHostDelegate, UITextFieldDelegate>
{
    BOOL bReturnBuuton;
    BOOL bPlayingButton;
    EmailReportProtocol *protocol;
}

- (void).cxx_destruct;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)dealloc;
- (void)doReportError;
- (void)doFinishReport;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)onKboardWillHide:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (void)beginReport:(id)arg1;
- (BOOL)isMatchEmailAddress:(id)arg1;
- (void)doInputFinish;
- (void)back:(id)arg1;
- (void)popGestureRecognize;
- (void)jumpToDownloadJOOX:(id)arg1;
- (void)loadView;
- (id)initWithReturnButton:(BOOL)arg1 NowPlayButton:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

