//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface JsonHelper : NSObject
{
}

+ (BOOL)getBoolFromDictionary:(id)arg1 forKey:(id)arg2;
+ (unsigned long long)getUnsignedLongLongFromDictionary:(id)arg1 forKey:(id)arg2;
+ (long long)getLongLongFromDictionary:(id)arg1 forKey:(id)arg2;
+ (unsigned long)getUnsignedLongFromDictionary:(id)arg1 forKey:(id)arg2;
+ (double)getDoubleFromDictionary:(id)arg1 forKey:(id)arg2;
+ (int)getIntegerFromDictionary:(id)arg1 forKey:(id)arg2 withDefault:(int)arg3;
+ (int)getIntegerFromDictionary:(id)arg1 forKey:(id)arg2;
+ (id)getDicFromDictionary:(id)arg1 forKey:(id)arg2 withDefault:(id)arg3;
+ (id)getArrayFromDictionary:(id)arg1 forKey:(id)arg2;
+ (id)getStringFromDictionary:(id)arg1 forKey:(id)arg2 isBase64Format:(BOOL)arg3 default:(id)arg4;
+ (id)getStringFromDictionary:(id)arg1 forKey:(id)arg2 isBase64Format:(BOOL)arg3;

@end

