//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString, UIImage, VideoGetvinfoDataController, VideoSetDataController;

@interface KKMediaPlayInfo : NSObject
{
    BOOL _wasFoundLocalPath;
    BOOL _needToAirplay;
    BOOL _isAirplayed;
    BOOL _isVideoDetailInfoReady;
    BOOL _startedPlay;
    BOOL _videoHasNoCopyRight;
    BOOL _isP2PPlayMode;
    BOOL _videoPlayInfoReady;
    NSArray *_localPaths;
    int _currentIndex;
    int _videoDataType;
    NSMutableArray *_videoUrlsArray;
    NSMutableArray *_videoTimesArray;
    int _dltype;
    int _didAirplayedState;
    float _initialPlayedTime;
    VideoGetvinfoDataController *_videoDataController;
    VideoSetDataController *_progInfoDataController;
    UIImage *_smallScreenshot;
    UIImage *_midleScreenshot;
    NSString *_curDefn;
    NSString *_preDefn;
    int _preFormat;
    int _changeUrlToRetryCount;
    int _requestMediaType;
}

@property(nonatomic) BOOL videoPlayInfoReady; // @synthesize videoPlayInfoReady=_videoPlayInfoReady;
@property(nonatomic) int requestMediaType; // @synthesize requestMediaType=_requestMediaType;
@property(nonatomic) BOOL isP2PPlayMode; // @synthesize isP2PPlayMode=_isP2PPlayMode;
@property(nonatomic) BOOL videoHasNoCopyRight; // @synthesize videoHasNoCopyRight=_videoHasNoCopyRight;
@property(nonatomic) BOOL startedPlay; // @synthesize startedPlay=_startedPlay;
@property(nonatomic) int changeUrlToRetryCount; // @synthesize changeUrlToRetryCount=_changeUrlToRetryCount;
@property(nonatomic) BOOL isVideoDetailInfoReady; // @synthesize isVideoDetailInfoReady=_isVideoDetailInfoReady;
@property(nonatomic) int preFormat; // @synthesize preFormat=_preFormat;
@property(copy, nonatomic) NSString *preDefn; // @synthesize preDefn=_preDefn;
@property(copy, nonatomic) NSString *curDefn; // @synthesize curDefn=_curDefn;
@property(retain) UIImage *midleScreenshot; // @synthesize midleScreenshot=_midleScreenshot;
@property(retain) UIImage *smallScreenshot; // @synthesize smallScreenshot=_smallScreenshot;
@property(retain) VideoSetDataController *progInfoDataController; // @synthesize progInfoDataController=_progInfoDataController;
@property(retain) VideoGetvinfoDataController *videoDataController; // @synthesize videoDataController=_videoDataController;
@property(nonatomic) float initialPlayedTime; // @synthesize initialPlayedTime=_initialPlayedTime;
@property(nonatomic) int didAirplayedState; // @synthesize didAirplayedState=_didAirplayedState;
@property(nonatomic) BOOL isAirplayed; // @synthesize isAirplayed=_isAirplayed;
@property(nonatomic) BOOL needToAirplay; // @synthesize needToAirplay=_needToAirplay;
@property int dltype; // @synthesize dltype=_dltype;
@property(retain) NSMutableArray *videoTimesArray; // @synthesize videoTimesArray=_videoTimesArray;
@property(retain) NSMutableArray *videoUrlsArray; // @synthesize videoUrlsArray=_videoUrlsArray;
@property(nonatomic) int videoDataType; // @synthesize videoDataType=_videoDataType;
@property(nonatomic) int currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain) NSArray *localPaths; // @synthesize localPaths=_localPaths;
@property(nonatomic) BOOL wasFoundLocalPath; // @synthesize wasFoundLocalPath=_wasFoundLocalPath;
- (int)countMP4Order:(float)arg1;
- (void)resetMediaPlayInfo;
- (void)resetCurVideoReleatedPlayInfoOnly;
- (void)resetPlayMediaInfo;
- (void)resetSearchLocal;
- (void)dealloc;
- (id)init;

@end

