//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface KSongNewInfo : NSObject
{
    BOOL _bSHowRed;
    NSString *_strUid;
    double _dTimeStamp;
}

@property(nonatomic) BOOL bSHowRed; // @synthesize bSHowRed=_bSHowRed;
@property(nonatomic) double dTimeStamp; // @synthesize dTimeStamp=_dTimeStamp;
@property(retain, nonatomic) NSString *strUid; // @synthesize strUid=_strUid;
- (void).cxx_destruct;
- (void)resetNewInfo;

@end

