//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface LaucherNumer : NSObject
{
    unsigned long lastUpdateTime;
    unsigned long lastlastUpdateTime;
    int showLauncherNum;
    id <LaucherNumer> _delegate;
}

@property(nonatomic) __weak id <LaucherNumer> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int showLauncherNum; // @synthesize showLauncherNum;
@property(readonly, nonatomic) unsigned long lastlastUpdateTime; // @synthesize lastlastUpdateTime;
@property(readonly, nonatomic) unsigned long lastUpdateTime; // @synthesize lastUpdateTime;
- (void).cxx_destruct;
- (BOOL)isValided;
- (void)updateLastUpdateTime:(BOOL)arg1;
- (id)initWithDelegate:(id)arg1;

@end

