//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQMusicCell.h"

#import "ImageManagerDelegate.h"

@class NSObject, NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface LibraryImageCell : QQMusicCell <ImageManagerDelegate>
{
    NSObject *_curObject;
    UILabel *_centerLabel;
    UIImageView *_iconImageView;
    UIImageView *_vipIcon;
    UIImageView *_headerLine;
    UIImageView *_seperateLine;
    UIImageView *_piaoIcon;
    UIImageView *_buluoIcon;
}

@property(retain, nonatomic) UIImageView *buluoIcon; // @synthesize buluoIcon=_buluoIcon;
@property(retain, nonatomic) UIImageView *piaoIcon; // @synthesize piaoIcon=_piaoIcon;
@property(retain, nonatomic) UIImageView *seperateLine; // @synthesize seperateLine=_seperateLine;
@property(retain, nonatomic) UIImageView *headerLine; // @synthesize headerLine=_headerLine;
@property(retain, nonatomic) UIImageView *vipIcon; // @synthesize vipIcon=_vipIcon;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UILabel *centerLabel; // @synthesize centerLabel=_centerLabel;
@property(retain, nonatomic) NSObject *curObject; // @synthesize curObject=_curObject;
- (void).cxx_destruct;
- (int)qmCellType;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)setIsShowBuluoIcon:(BOOL)arg1;
- (void)setIsShowPiaoIcon:(BOOL)arg1;
- (void)setVipLogo:(BOOL)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

