//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class DirectCluster, ListBase;

__attribute__((visibility("hidden")))
@interface LibraryRadioProtocol : ProtocolBaseJason
{
    DirectCluster *cluster;
    ListBase *list;
    int retState;
}

@property(nonatomic) int retState; // @synthesize retState;
@property(retain, nonatomic) ListBase *list; // @synthesize list;
@property(retain, nonatomic) DirectCluster *cluster; // @synthesize cluster;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (id)getUrl;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)init;

@end

