//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ListTagDelegate.h"
#import "ProtocolHostDelegate.h"
#import "SongQueryCallBackDelegate.h"

@class ListBase, MusicCircleNewInfo, NSArray, NSMutableArray, NSMutableDictionary, NSString, ParticularCategoryIndexProtocol, ParticularIndexSingerProtocol, SingerCategoryProtocol, TopMusicStyleProtocol;

__attribute__((visibility("hidden")))
@interface LibraryManager : NSObject <ProtocolHostDelegate, ListTagDelegate, SongQueryCallBackDelegate>
{
    NSMutableArray *category;
    ListBase *hotList;
    TopMusicStyleProtocol *hotSongProtocol;
    ListBase *qqSongSearchResult;
    ListBase *singersList;
    SingerCategoryProtocol *singersProtocol;
    ListBase *particularSingersList;
    ListBase *singerssong;
    ListBase *singerAlbum;
    ListBase *singerMV;
    ListBase *singerAlbumSong;
    NSMutableDictionary *singerClusterArray;
    ListBase *directList;
    ListBase *searchResult;
    ListBase *singerSongFolder;
    NSArray *_singerBuluoNewInfo;
    MusicCircleNewInfo *_musicCircleNewInfo;
    ParticularCategoryIndexProtocol *_particularCategoryIndexProtocol;
    ParticularIndexSingerProtocol *_particularIndexSingerProtocol;
}

+ (id)sharedLibraryManager;
@property(retain, nonatomic) ParticularIndexSingerProtocol *particularIndexSingerProtocol; // @synthesize particularIndexSingerProtocol=_particularIndexSingerProtocol;
@property(retain, nonatomic) ParticularCategoryIndexProtocol *particularCategoryIndexProtocol; // @synthesize particularCategoryIndexProtocol=_particularCategoryIndexProtocol;
@property(retain, nonatomic) MusicCircleNewInfo *musicCircleNewInfo; // @synthesize musicCircleNewInfo=_musicCircleNewInfo;
@property(retain, nonatomic) NSArray *singerBuluoNewInfo; // @synthesize singerBuluoNewInfo=_singerBuluoNewInfo;
@property(readonly, nonatomic) ListBase *directList; // @synthesize directList;
@property(retain, nonatomic) NSMutableDictionary *singerClusterArray; // @synthesize singerClusterArray;
@property(readonly, nonatomic) __weak ListBase *singerAlbumSong; // @synthesize singerAlbumSong;
@property(readonly, nonatomic) __weak ListBase *qqSongSearchResult; // @synthesize qqSongSearchResult;
@property(readonly, nonatomic) __weak ListBase *searchResult; // @synthesize searchResult;
@property(retain, nonatomic) NSMutableArray *category; // @synthesize category;
- (void).cxx_destruct;
- (void)cleanCachedData;
- (void)removeMusicCircleNewInfo;
- (void)handleMusicCircleNewInfo:(id)arg1;
- (void)getMusicCircleNewInfo;
- (void)getSingerBuluoNewInfo;
- (void)songQueryCallBackWithSongArray:(id)arg1;
- (id)getSingerCluster:(id)arg1;
- (id)addSingerClusterArray:(id)arg1;
- (void)onList:(id)arg1 WithResult:(int)arg2 AndAct:(id)arg3;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)querySongsWithDic:(id)arg1;
- (void)querySongsInfo:(id)arg1 withDelegate:(id)arg2 from:(id)arg3 afterDelay:(double)arg4;
- (void)querySongsInfo:(id)arg1;
- (void)searchByCluster:(id)arg1 withList:(id)arg2 withType:(int)arg3;
- (void)searchByCluster:(id)arg1 withList:(id)arg2;
- (BOOL)isMusicClusterEqual:(id)arg1 musicCluster2:(id)arg2;
- (BOOL)getLibraryRadioListByCluster:(id)arg1 withList:(id)arg2;
- (BOOL)getLibraryRadioListByCluster:(id)arg1 Fresh:(BOOL)arg2;
- (void)getMoreSingerSongFolderByCluster:(id)arg1;
- (BOOL)getSingerSongFolderByCluster:(id)arg1 Fresh:(BOOL)arg2;
- (void)getMoreSingerMVListByCluster:(id)arg1;
- (BOOL)getSingerMVListByCluster:(id)arg1 Fresh:(BOOL)arg2;
- (void)getMoreSingerAlbumListByCluster:(id)arg1;
- (BOOL)getSingerAlbumListByCluster:(id)arg1 Fresh:(BOOL)arg2;
- (void)getMoreSongListByCluster:(id)arg1;
- (BOOL)getSongListByCluster:(id)arg1 Fresh:(BOOL)arg2;
- (BOOL)getParticularIndexMoreListByCluster:(id)arg1 Fresh:(BOOL)arg2;
- (BOOL)getParticularIndexByCluster:(id)arg1 Fresh:(BOOL)arg2;
- (BOOL)getSingerListByCluster:(id)arg1 Fresh:(BOOL)arg2;
- (BOOL)getSingersList:(BOOL)arg1;
- (BOOL)freshHotListByCluster:(id)arg1 Fresh:(BOOL)arg2;
@property(readonly, nonatomic) __weak ListBase *hotList; // @synthesize hotList;
@property(readonly, nonatomic) __weak ListBase *singerSongFolder; // @synthesize singerSongFolder;
@property(readonly, nonatomic) __weak ListBase *singerMV; // @synthesize singerMV;
@property(readonly, nonatomic) __weak ListBase *singerAlbum; // @synthesize singerAlbum;
@property(readonly, nonatomic) __weak ListBase *singerssong; // @synthesize singerssong;
@property(readonly, nonatomic) __weak ListBase *particularSingersList; // @synthesize particularSingersList;
@property(readonly, nonatomic) ListBase *singersList; // @synthesize singersList;
- (void)dealloc;
- (void)createCategoryCluster;
- (id)getSearchId;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

