//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

__attribute__((visibility("hidden")))
@interface ListenedSongListTid : NSObject <NSCoding>
{
    long long _openedTime;
    long long _songListTid;
}

@property long long songListTid; // @synthesize songListTid=_songListTid;
@property long long openedTime; // @synthesize openedTime=_openedTime;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

