//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ClusterInfo, ExpInfo, ListBase, NSArray, NSDictionary, NSMutableArray;

@protocol ListBaseDBProtocol

@optional
- (void)onList:(ListBase *)arg1 DB:(NSDictionary *)arg2 DelInfos:(NSArray *)arg3;
- (void)onList:(ListBase *)arg1 DB:(NSDictionary *)arg2 DataChangeInfos:(NSArray *)arg3 WithExp:(NSArray *)arg4;
- (void)onList:(ListBase *)arg1 DB:(NSDictionary *)arg2 AddInfos:(NSArray *)arg3 WithExp:(NSArray *)arg4;
- (void)onList:(ListBase *)arg1 DB:(NSDictionary *)arg2 updateInfo:(ClusterInfo *)arg3 WithExp:(ExpInfo *)arg4;
- (void)onList:(ListBase *)arg1 DB:(NSDictionary *)arg2 AddInfo:(ClusterInfo *)arg3 WithExp:(ExpInfo *)arg4;
- (void)onList:(ListBase *)arg1 DB:(NSDictionary *)arg2 DelInfo:(ClusterInfo *)arg3;
- (NSArray *)onList:(ListBase *)arg1 GetDataByDB:(NSDictionary *)arg2 WithExp:(NSMutableArray *)arg3;
@end

