//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UserDBAdapter;

__attribute__((visibility("hidden")))
@interface LocalDB : NSObject
{
    UserDBAdapter *userDBAdapter;
}

- (void).cxx_destruct;
- (void)UpdateZeroAlbum:(id)arg1 NewAlbumId:(int)arg2;
- (void)UpdateZeroSinger:(id)arg1 NewSingerId:(int)arg2;
- (void)updateMissingSongsToDownloading:(id)arg1;
- (BOOL)updateFolder:(id)arg1;
- (BOOL)deleteFolder:(id)arg1;
- (BOOL)insertFolder:(id)arg1;
- (id)getAllLocalList;
- (int)getCountOfLocalSongs;
- (int)getCountOfAllSongs;
- (int)getNextLocalFolderId;
- (int)getCountOfIPodData;
- (id)getSongsByFolder:(id)arg1;
- (id)getLocalAllWhere:(BOOL)arg1;
- (void)deleteSongs:(id)arg1;
- (BOOL)deleteSong:(id)arg1 fromFolder:(id)arg2;
- (BOOL)deleteSong:(id)arg1;
- (void)insertSongs:(id)arg1 expInfos:(id)arg2;
- (BOOL)insertSong:(id)arg1 expInfo:(id)arg2;
- (id)init;

@end

