//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FingerPrintManagerDelegate.h"
#import "ProtocolHostDelegate.h"

@class LyricProtocol, NSString, SongInfo;

__attribute__((visibility("hidden")))
@interface LyricManager : NSObject <ProtocolHostDelegate, FingerPrintManagerDelegate>
{
    SongInfo *song;
    LyricProtocol *lyricProtocol;
    id <LyricManagerDelegate> leader;
}

+ (id)decodeQrcFileWithContent:(id)arg1;
+ (id)decodeQrcFileWithPath:(id)arg1;
+ (int)hexStringToString:(const char *)arg1 stringLength:(int)arg2 toString:(char *)arg3;
+ (id)decodeDes:(const char *)arg1 size:(long)arg2;
+ (id)getQrcTextFromXml:(id)arg1;
+ (id)getQrcFilePathByLyricFilePath:(id)arg1;
+ (id)getID3VersionLyricFilePath:(id)arg1 isQrc:(BOOL)arg2;
+ (id)getYInyiLyricFilePath:(id)arg1;
+ (id)getTranslateLyricFilePath:(id)arg1;
+ (id)getLyricFilePath:(id)arg1 isQrc:(BOOL)arg2;
+ (id)sharedLyricManager;
@property(nonatomic) __weak id <LyricManagerDelegate> leader; // @synthesize leader;
@property(retain, nonatomic) LyricProtocol *lyricProtocol; // @synthesize lyricProtocol;
@property(readonly, nonatomic) SongInfo *song; // @synthesize song;
- (void).cxx_destruct;
- (BOOL)getIsUseQrc;
- (void)onFingerPrintStatusChange:(id)arg1 fingerPrintStatus:(int)arg2 lyric:(id)arg3 SongId:(long long)arg4 lyricType:(int)arg5;
- (void)dealloc;
- (id)parseOfSong:(id)arg1 withLyric:(id)arg2 withTransLateLyric:(id)arg3 withYinyiLyric:(id)arg4 withLyricType:(int)arg5 withLyricProtocol:(id)arg6;
- (unsigned long)_getLyricAttributeWithFilePath:(id)arg1;
- (void)_saveLyricAttributeWithFilePath:(id)arg1 WithTimeTag:(unsigned long)arg2;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)handleResearchHostCallback:(int)arg1;
- (void)researchLyric:(id)arg1 forceToUseSongID:(BOOL)arg2;
- (void)researchLyric:(id)arg1;
- (id)getLyric:(id)arg1 useFingerPrint:(BOOL)arg2 manualCause:(BOOL)arg3;
- (id)getLyricFromFingerPrintManager:(BOOL)arg1;
- (void)delayCallBackSeachDone:(id)arg1;
- (void)fetchLyricFromServer:(int)arg1;
- (id)getLyricObjectFromLocal;
- (id)getLyricFromLyricManager;
- (BOOL)isTopViewLyricView;
- (id)parseText:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

