//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, SongInfo;

__attribute__((visibility("hidden")))
@interface MatchedSongItem : NSObject
{
    SongInfo *_songInfo;
    NSData *_rangesMatchedSongName;
    NSData *_rangesMatchedAlbumName;
    NSData *_rangesMatchedSingerName;
}

@property(retain) NSData *rangesMatchedSingerName; // @synthesize rangesMatchedSingerName=_rangesMatchedSingerName;
@property(retain) NSData *rangesMatchedAlbumName; // @synthesize rangesMatchedAlbumName=_rangesMatchedAlbumName;
@property(retain) NSData *rangesMatchedSongName; // @synthesize rangesMatchedSongName=_rangesMatchedSongName;
@property(retain) SongInfo *songInfo; // @synthesize songInfo=_songInfo;
- (void).cxx_destruct;

@end

