//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImage, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface MoreCustomButton : UIButton
{
    UIImageView *_titleImageView;
    UIImage *_titleImage;
    UIImageView *_redPointImageView;
    UILabel *_mainTitleLabel;
    UILabel *_subTitleLabel;
}

@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *mainTitleLabel; // @synthesize mainTitleLabel=_mainTitleLabel;
@property(retain, nonatomic) UIImageView *redPointImageView; // @synthesize redPointImageView=_redPointImageView;
@property(retain, nonatomic) UIImage *titleImage; // @synthesize titleImage=_titleImage;
@property(retain, nonatomic) UIImageView *titleImageView; // @synthesize titleImageView=_titleImageView;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 withSeperateLine:(BOOL)arg2;

@end

