//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface MPTipsMiniProgressView : UIView
{
    UIColor *_tintColor;
    float _progress;
}

- (void)setProgress:(float)arg1;
- (float)progress;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

