//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTAWXOEvent.h"

#import "MTAWXOEventProtocol.h"

@class NSArray, NSDictionary, NSString;

@interface MTAWXOCustomEvent : MTAWXOEvent <MTAWXOEventProtocol>
{
    NSString *_eventID;
    NSArray *_args;
    NSDictionary *_kvs;
    unsigned int _duration;
}

@property unsigned int duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSDictionary *kvs; // @synthesize kvs=_kvs;
@property(retain, nonatomic) NSArray *args; // @synthesize args=_args;
@property(retain, nonatomic) NSString *eventID; // @synthesize eventID=_eventID;
- (void)dealloc;
- (id)init;
- (void)encode:(id)arg1;
- (int)getType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

