//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTAWXOEvent.h"

#import "MTAWXOEventProtocol.h"

@class NSString;

@interface MTAWXOPageView : MTAWXOEvent <MTAWXOEventProtocol>
{
    unsigned int _duration;
    NSString *_page;
    NSString *_refer;
}

@property(retain, nonatomic) NSString *refer; // @synthesize refer=_refer;
@property(retain, nonatomic) NSString *page; // @synthesize page=_page;
@property unsigned int duration; // @synthesize duration=_duration;
- (void)dealloc;
- (id)init;
- (void)encode:(id)arg1;
- (int)getType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

