//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MusicCircleFeed.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MusicCircleSquareFeed : MusicCircleFeed
{
    BOOL _isFollow;
    NSString *_recomReason;
    int _recomReasonType;
    int _groupId;
}

+ (id)tranlateFromJsonData:(id)arg1;
@property(nonatomic) int groupId; // @synthesize groupId=_groupId;
@property(nonatomic) BOOL isFollow; // @synthesize isFollow=_isFollow;
@property(nonatomic) int recomReasonType; // @synthesize recomReasonType=_recomReasonType;
@property(retain, nonatomic) NSString *recomReason; // @synthesize recomReason=_recomReason;
- (void).cxx_destruct;
- (float)fullHeight;
- (void)dealloc;

@end

