//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class FeedZanInfo, MusicCircleFeed;

__attribute__((visibility("hidden")))
@interface MusicCircleZanProtocol : ProtocolBaseJason
{
    BOOL _bAddZan;
    MusicCircleFeed *_feed;
    FeedZanInfo *_zanInfo;
}

@property(retain, nonatomic) FeedZanInfo *zanInfo; // @synthesize zanInfo=_zanInfo;
@property(retain, nonatomic) MusicCircleFeed *feed; // @synthesize feed=_feed;
@property(nonatomic) BOOL bAddZan; // @synthesize bAddZan=_bAddZan;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUser;
- (id)getUrl;
- (int)cid;

@end

