//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ChannelCreator, NSAttributedString, NSString;

__attribute__((visibility("hidden")))
@interface MusicCircleActionInfo : NSObject
{
    ChannelCreator *_owner;
    ChannelCreator *_replayCommentUser;
    NSString *_msg;
    NSAttributedString *_attributeString;
    NSString *_pic;
    NSString *_feedId;
    int _type;
    int _userType;
    NSString *_commentID;
    unsigned long _contentID;
    int _serverFeedType;
    int _serverFeedSubType;
    long long _time;
    long long _singerId;
}

+ (id)attributedMessageString:(id)arg1;
+ (id)translateFromJsonData:(id)arg1;
@property(nonatomic) int serverFeedSubType; // @synthesize serverFeedSubType=_serverFeedSubType;
@property(nonatomic) int serverFeedType; // @synthesize serverFeedType=_serverFeedType;
@property(nonatomic) unsigned long contentID; // @synthesize contentID=_contentID;
@property(retain, nonatomic) NSString *commentID; // @synthesize commentID=_commentID;
@property(nonatomic) int userType; // @synthesize userType=_userType;
@property(nonatomic) long long singerId; // @synthesize singerId=_singerId;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(retain, nonatomic) NSAttributedString *attributeString; // @synthesize attributeString=_attributeString;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(nonatomic) long long time; // @synthesize time=_time;
@property(retain, nonatomic) ChannelCreator *replayCommentUser; // @synthesize replayCommentUser=_replayCommentUser;
@property(retain, nonatomic) ChannelCreator *owner; // @synthesize owner=_owner;
- (void).cxx_destruct;
- (float)cellHeight;
- (id)imageFileName:(id)arg1;
- (id)picFileName;
- (id)oppicFileName;
- (id)description;

@end

