//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQMusicCell.h"

#import "ImageManagerDelegate.h"

@class MusicCircleFeed, NSArray, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface MusicCircleIDetailImageCell : QQMusicCell <ImageManagerDelegate>
{
    NSArray *imageArray;
    NSArray *_tempImageArray;
    NSMutableArray *_imageViewArray;
    id <MusicCircleCellDelegate> delegate;
    MusicCircleFeed *feed;
}

@property(retain, nonatomic) MusicCircleFeed *feed; // @synthesize feed;
@property(nonatomic) __weak id <MusicCircleCellDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSMutableArray *imageViewArray; // @synthesize imageViewArray=_imageViewArray;
@property(retain, nonatomic) NSArray *tempImageArray; // @synthesize tempImageArray=_tempImageArray;
@property(retain, nonatomic) NSArray *imageArray; // @synthesize imageArray;
- (void).cxx_destruct;
- (void)clickImage:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)setImageArrayData:(id)arg1 feedInfo:(id)arg2;
- (void)updateUI;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

