//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ListBase, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface MyMusicSearchResult : NSObject
{
    BOOL _finished;
    NSString *_input;
    long _lastUpdateTime;
    NSMutableArray *_matchedSongItems;
    ListBase *_listBase;
}

@property BOOL finished; // @synthesize finished=_finished;
@property(retain) ListBase *listBase; // @synthesize listBase=_listBase;
@property(retain) NSMutableArray *matchedSongItems; // @synthesize matchedSongItems=_matchedSongItems;
@property long lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
@property(retain) NSString *input; // @synthesize input=_input;
- (void).cxx_destruct;

@end

