//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TitleCell.h"

@class QMLabel, UIImageView;

__attribute__((visibility("hidden")))
@interface MyMusicRootAllFolderCell : TitleCell
{
    id <MyMusicRootAllFolderCell> _delegate;
    QMLabel *_number;
    UIImageView *_redPoint;
}

@property(retain) UIImageView *redPoint; // @synthesize redPoint=_redPoint;
@property(retain) QMLabel *number; // @synthesize number=_number;
@property __weak id <MyMusicRootAllFolderCell> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onNotifySkinSettingChange:(id)arg1;
- (void)setRedPointHidden:(BOOL)arg1;
- (void)setFolderCount:(int)arg1;
- (void)onTouchUpInsideMore:(id)arg1;
- (void)layoutSubviews;
- (void)buildSubViews;

@end

