//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQMusicCell.h"

@class URLImageView;

__attribute__((visibility("hidden")))
@interface MyMusicRootNotLoginUserInfoCell : QQMusicCell
{
    URLImageView *_image;
}

@property(retain) URLImageView *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (BOOL)showArrow;
- (void)updateUI:(id)arg1;
- (void)layoutSubviews;
- (void)buildSubViews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

