//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class QMLabel, ThreeButtonItemData, UIImageView;

__attribute__((visibility("hidden")))
@interface MyMusicRootLocalMusicNumButton : UIControl
{
    QMLabel *_subTitle;
    UIImageView *_redPoint;
    UIImageView *_icoImageView;
    QMLabel *_titleLabel;
    ThreeButtonItemData *_itemData;
}

@property(retain) ThreeButtonItemData *itemData; // @synthesize itemData=_itemData;
@property(retain) QMLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain) UIImageView *icoImageView; // @synthesize icoImageView=_icoImageView;
@property(retain) UIImageView *redPoint; // @synthesize redPoint=_redPoint;
@property(retain) QMLabel *subTitle; // @synthesize subTitle=_subTitle;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (BOOL)isAccessibilityElement;
- (void)refreshSkinSetting;
- (id)data;
- (id)getSubTitleLabel;
- (BOOL)getRedPointIsHidden;
- (void)setRedPointHidden:(BOOL)arg1;
- (void)updateIconImageView:(id)arg1;
- (void)updateSubTitle:(id)arg1;
- (void)updateMainTitle:(id)arg1;
- (void)updateData:(id)arg1;
- (float)fontSize;
- (void)addConstraintsToImageView:(id)arg1 titleLabel:(id)arg2 numberLabel:(id)arg3 redPoint:(id)arg4;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

