//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface NetGetNumberProtocol : ProtocolBaseJason
{
    NSString *phoneNumber;
    int returnCode;
    NSString *returnMsg;
}

@property(retain) NSString *phoneNumber; // @synthesize phoneNumber;
- (void).cxx_destruct;
- (BOOL)isDataBeginWithFiveZero:(id)arg1;
- (void)onParseJasonData:(id)arg1;
- (BOOL)parseCompressedData:(id)arg1;
- (void)netBase:(id)arg1 didFailWithError:(int)arg2;
- (id)getUrl;

@end

