//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ASIHTTPRequestDelegate.h"

@class ASIHTTPRequest, FolderInfo, NSFileHandle, NSObject<OS_dispatch_queue>, NSString, NSURL, SongInfo;

__attribute__((visibility("hidden")))
@interface NextAudioData : NSObject <ASIHTTPRequestDelegate>
{
    ASIHTTPRequest *_asiHttpRequest;
    int _songLength;
    int _dataLength;
    NSString *_saveFilePath;
    NSString *_tempPath;
    NSURL *_downloadURL;
    NSObject<OS_dispatch_queue> *_fileWritingQueue;
    FolderInfo *_cacheNextFolder;
    int _currentLength;
    SongInfo *_currentSong;
    NSFileHandle *_storeDataFileHandle;
    int _statusCode;
    int _songRateType;
}

@property(nonatomic) int songRateType; // @synthesize songRateType=_songRateType;
@property(nonatomic) int statusCode; // @synthesize statusCode=_statusCode;
@property(retain, nonatomic) NSFileHandle *storeDataFileHandle; // @synthesize storeDataFileHandle=_storeDataFileHandle;
@property(retain, nonatomic) SongInfo *currentSong; // @synthesize currentSong=_currentSong;
@property(nonatomic) int currentLength; // @synthesize currentLength=_currentLength;
@property(retain, nonatomic) ASIHTTPRequest *asiHttpRequest; // @synthesize asiHttpRequest=_asiHttpRequest;
@property(retain, nonatomic) NSURL *downloadURL; // @synthesize downloadURL=_downloadURL;
@property(retain, nonatomic) NSString *tempPath; // @synthesize tempPath=_tempPath;
@property(retain, nonatomic) NSString *saveFilePath; // @synthesize saveFilePath=_saveFilePath;
- (void).cxx_destruct;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)request:(id)arg1 didReceiveData:(id)arg2;
- (void)request:(id)arg1 didReceiveResponseHeaders:(id)arg2;
- (void)saveAndCheckNext;
- (id)createASIRequest:(id)arg1;
- (void)checkFileCreateConnection;
- (void)startCacheNextImgAndLyric;
- (void)start;
- (BOOL)prepare;
- (BOOL)hasRichLimitLength;
- (void)cancelInMainThread;
- (void)stop;
- (void)startCache;
- (id)_findSongInfoInFolderSongs:(id)arg1 songInfo:(id)arg2;
- (void)insertCacheNextSongInfo:(id)arg1;
- (BOOL)limitCacheNextFolderSongs;
- (void)setCacheNextSong:(id)arg1;
- (void)loadFolderInfo;
- (int)minBufferingSize;
- (void)dealloc;
- (id)initWithCacheSong:(id)arg1 songRateType:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

