//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface NowPlayingAnimationView : UIView
{
    UIView *playingView1;
    UIView *playingView2;
    UIView *playingView3;
    UIView *playingView4;
    float _myViewWidth;
    float _viewMargin;
    float _viweOffset;
    float _radio;
    UIColor *_customColor;
}

@property(retain, nonatomic) UIColor *customColor; // @synthesize customColor=_customColor;
- (void).cxx_destruct;
- (void)_onNotifyColorStyleChanged:(id)arg1;
- (void)myAudioPlayerStateChanged:(id)arg1;
- (void)stopAnimation;
- (void)startAnimation;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 withWidth:(float)arg2 margin:(float)arg3 offset:(float)arg4 radio:(float)arg5;

@end

