//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (QNUtils)
+ (id)qn_cast:(id)arg1 warnOnFailure:(BOOL)arg2;
+ (id)qn_cast:(id)arg1;
- (BOOL)qn_removeObserver:(id)arg1 forKeyPath:(id)arg2;
- (BOOL)qn_removeObserver:(id)arg1 forKeyPath:(id)arg2 context:(void *)arg3;
- (BOOL)qn_addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned int)arg3 context:(void *)arg4;
- (void)qn_performSelectorOnMainThreadInNextRunLoop:(SEL)arg1 withObject:(id)arg2;
@end

