//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (NSObjectJumperBundlePrivate)
- (id)callScriptMethodWithName:(id)arg1 needCallOriginal:(char *)arg2:(id)arg3:(id)arg4:(id)arg5:(id)arg6:(id)arg7:(id)arg8:(id)arg9:(id)arg10;
@end

