//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface ProcessView : UIView
{
    UIView *_viewForeground;
    float _value;
    float _start;
    UIImageView *backgroundLeft;
    UIImageView *backgroundRight;
    UIImageView *backgroundMiddle;
    UIImageView *foregroundLeft;
    UIImageView *foregroundRight;
    UIImageView *foregroundMiddle;
    id <ProcessViewDelegate> delegate;
}

@property(nonatomic) __weak id <ProcessViewDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) UIImageView *foregroundMiddle; // @synthesize foregroundMiddle;
@property(retain, nonatomic) UIImageView *foregroundRight; // @synthesize foregroundRight;
@property(retain, nonatomic) UIImageView *foregroundLeft; // @synthesize foregroundLeft;
@property(retain, nonatomic) UIImageView *backgroundMiddle; // @synthesize backgroundMiddle;
@property(retain, nonatomic) UIImageView *backgroundRight; // @synthesize backgroundRight;
@property(retain, nonatomic) UIImageView *backgroundLeft; // @synthesize backgroundLeft;
- (void).cxx_destruct;
- (void)onNotifyColorStyleChanged:(id)arg1;
- (void)removeDelegate;
- (void)dealloc;
- (float)value;
- (void)redraw;
- (float)startValue;
- (void)setStartValue:(float)arg1;
- (void)setValue:(float)arg1;
- (void)setProcess:(float)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andDelegate:(id)arg2 cornerRadius:(float)arg3;
- (id)initWithFrame:(struct CGRect)arg1 andDelegate:(id)arg2;

@end

