//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol ProcessCallback <NSObject>
- (void)networkInfo:(CDStruct_34f44c17 *)arg1;
@end

