//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AHAlertView.h"

@class NSString, UIImageView;

@interface QLAlertView : AHAlertView
{
    NSString *alertIconPath;
    NSString *bdgeIconPath;
    UIImageView *alertImgView;
    UIImageView *bdgeImgView;
}

+ (void)qlnoticeWithMsg:(id)arg1 title:(id)arg2 confirmTitle:(id)arg3 cancelTitle:(id)arg4;
@property(retain, nonatomic) UIImageView *bdgeImgView; // @synthesize bdgeImgView;
@property(retain, nonatomic) UIImageView *alertImgView; // @synthesize alertImgView;
@property(retain, nonatomic) NSString *bdgeIconPath; // @synthesize bdgeIconPath;
@property(retain, nonatomic) NSString *alertIconPath; // @synthesize alertIconPath;
- (BOOL)canBecomeFirstResponder;
- (void)layoutSubviews;
- (void)setViews;
- (id)lineLayer;
- (void)dealloc;
- (id)initWithTxt:(id)arg1 title:(id)arg2 icon:(id)arg3 bdgeIconPath:(id)arg4 cancelTitle:(id)arg5 cancelblock:(CDUnknownBlockType)arg6 confirmTitle:(id)arg7 confirmblock:(CDUnknownBlockType)arg8;
- (id)initWithFrame:(struct CGRect)arg1;

@end

