//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface QLAppSkinObj : NSObject
{
    NSString *_name;
    UIColor *_mainBgColor;
    UIColor *_mainTitleColor;
    UIColor *_subTitleColor;
    UIColor *_seperatorLineColor;
}

@property(retain, nonatomic) UIColor *seperatorLineColor; // @synthesize seperatorLineColor=_seperatorLineColor;
@property(retain, nonatomic) UIColor *subTitleColor; // @synthesize subTitleColor=_subTitleColor;
@property(retain, nonatomic) UIColor *mainTitleColor; // @synthesize mainTitleColor=_mainTitleColor;
@property(retain, nonatomic) UIColor *mainBgColor; // @synthesize mainBgColor=_mainBgColor;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void)dealloc;

@end

