//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QLRequestModel.h"

@class NSMutableArray, NSString, QLASIHTTPRequest;

@interface QLCoverRelatedModel : QLRequestModel
{
    BOOL _isTenVideo;
    BOOL _isDetail;
    QLASIHTTPRequest *dataRequest;
    unsigned int _defaultResolution;
    int _columeID;
    NSString *_coverID;
    NSString *_videoID;
    int _videoType;
    NSMutableArray *_relatedItems;
    NSMutableArray *_relatedSections;
    NSMutableArray *_movieTitles;
    NSMutableArray *_movieVids;
    NSMutableArray *_screenShots;
    NSMutableArray *_movieinfos;
    NSString *_relatedTitle;
    NSString *_extenalParams;
    NSString *_reqTopic;
}

+ (BOOL)isCoverStyleForVideoType:(int)arg1;
@property(copy, nonatomic) NSString *reqTopic; // @synthesize reqTopic=_reqTopic;
@property(copy, nonatomic) NSString *extenalParams; // @synthesize extenalParams=_extenalParams;
@property BOOL isDetail; // @synthesize isDetail=_isDetail;
@property(retain) NSString *relatedTitle; // @synthesize relatedTitle=_relatedTitle;
@property(readonly, nonatomic) NSMutableArray *movieinfos; // @synthesize movieinfos=_movieinfos;
@property(readonly, nonatomic) NSMutableArray *screenShots; // @synthesize screenShots=_screenShots;
@property(readonly, nonatomic) NSMutableArray *movieVids; // @synthesize movieVids=_movieVids;
@property(readonly, nonatomic) NSMutableArray *movieTitles; // @synthesize movieTitles=_movieTitles;
@property(readonly) NSMutableArray *relatedSections; // @synthesize relatedSections=_relatedSections;
@property(readonly) NSMutableArray *relatedItems; // @synthesize relatedItems=_relatedItems;
@property(nonatomic) int videoType; // @synthesize videoType=_videoType;
@property BOOL isTenVideo; // @synthesize isTenVideo=_isTenVideo;
@property(copy, nonatomic) NSString *videoID; // @synthesize videoID=_videoID;
@property(copy, nonatomic) NSString *coverID; // @synthesize coverID=_coverID;
@property(nonatomic) int columeID; // @synthesize columeID=_columeID;
@property(nonatomic) unsigned int defaultResolution; // @synthesize defaultResolution=_defaultResolution;
@property(retain, nonatomic) QLASIHTTPRequest *dataRequest; // @synthesize dataRequest;
- (void)requestDidFinishLoad:(id)arg1;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidRetryRequest:(id)arg1;
- (void)load:(int)arg1 more:(BOOL)arg2;
- (id)init;
- (void)insertItemFromMovieItem:(id)arg1;
- (void)initModels;
- (void)dealloc;

@end

