//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView;

@interface QLMPFunctionCell : UITableViewCell
{
    BOOL _favorite;
    UIImageView *_separator;
    UIImageView *_separatorV;
    id <QLMPFunctionCellDelegate> _delegate;
    UIButton *_favoriteButton;
    UIButton *_downloadButton;
}

+ (float)cellHeight;
@property(nonatomic) BOOL favorite; // @synthesize favorite=_favorite;
@property(retain, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(retain, nonatomic) UIButton *favoriteButton; // @synthesize favoriteButton=_favoriteButton;
@property(nonatomic) id <QLMPFunctionCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *separatorV; // @synthesize separatorV=_separatorV;
@property(retain, nonatomic) UIImageView *separator; // @synthesize separator=_separator;
- (void)onDownloadClicked:(id)arg1;
- (void)onFavoriteClicked:(id)arg1;
- (void)setBottomSeparatorHide:(BOOL)arg1;
- (void)enableFavoriteBtn:(BOOL)arg1;
- (void)hideFavorite:(BOOL)arg1;
- (void)hideDownload:(BOOL)arg1;
- (void)enableDownloadBtn:(BOOL)arg1;
- (void)enableDownload:(BOOL)arg1;
- (void)setFavoriteFlag:(BOOL)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

