//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface QLResource : NSObject
{
    NSMutableDictionary *_URLDict;
}

+ (id)dictionaryWithContentsOfData:(id)arg1;
+ (id)instance;
- (id)readUrlResFile:(id)arg1;
- (void)printKey:(id)arg1;
- (void)resetToDefault;
- (BOOL)setURL:(id)arg1 Value:(id)arg2;
- (id)URLWithKey:(id)arg1;
- (void)dealloc;
- (id)init;

@end

