//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface QLStatusBar : UIView
{
    UIButton *_tapButton;
    id _btnTarget;
    SEL _btnTapAction;
    BOOL _barIsShowed;
    UILabel *_textLabel;
    UIView *_colorBgView;
}

+ (id)sharedInstance;
+ (BOOL)isShowed;
@property(nonatomic) BOOL barIsShowed; // @synthesize barIsShowed=_barIsShowed;
@property(retain, nonatomic) UIView *colorBgView; // @synthesize colorBgView=_colorBgView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void)showStatusBarInView:(id)arg1;
- (void)showStatusBar:(BOOL)arg1;
- (void)showStatusBar:(BOOL)arg1 animated:(BOOL)arg2;
- (void)addTarget:(id)arg1 tapAction:(SEL)arg2;
- (void)dealloc;
- (void)initCommon;
- (id)initWithFrame:(struct CGRect)arg1;

@end

