//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

@class NSDateFormatter, NSObject, NSString, UISwitch;

__attribute__((visibility("hidden")))
@interface QMAlarmSettingVC : SkinViewController
{
    NSObject *_callBackDelegate;
    UISwitch *_clockSwitch;
    NSDateFormatter *_dateFormatter;
    NSString *_repeatTypeStr;
    UISwitch *_remindSwitch;
}

@property(retain, nonatomic) UISwitch *remindSwitch; // @synthesize remindSwitch=_remindSwitch;
@property(retain, nonatomic) NSString *repeatTypeStr; // @synthesize repeatTypeStr=_repeatTypeStr;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) UISwitch *clockSwitch; // @synthesize clockSwitch=_clockSwitch;
@property(nonatomic) __weak NSObject *callBackDelegate; // @synthesize callBackDelegate=_callBackDelegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)setLocalNotificationWithFireDate:(id)arg1 andRepeatInterval:(unsigned int)arg2 andOriginDate:(id)arg3;
- (void)setLocalNotificationWithFireDate:(id)arg1 andRepeatInterval:(unsigned int)arg2;
- (void)headerCancel:(id)arg1;
- (void)headerFinish:(id)arg1;
- (void)onRemindSwitchChanged:(id)arg1;
- (void)onClockSwitchChanged:(id)arg1;
- (void)setTableFootView;
- (void)refreshView;
- (void)viewDidPop;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;

@end

