//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIAlertAction;

__attribute__((visibility("hidden")))
@interface QMAlertAction : NSObject
{
    BOOL _enabled;
    NSString *_title;
    int _style;
    CDUnknownBlockType _handler;
    UIAlertAction *_alertAction;
}

+ (id)actionWithTitle:(id)arg1 style:(int)arg2 handler:(CDUnknownBlockType)arg3;
@property(retain) UIAlertAction *alertAction; // @synthesize alertAction=_alertAction;
@property(copy) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) int style; // @synthesize style=_style;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 style:(int)arg2 handler:(CDUnknownBlockType)arg3;

@end

