//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSMutableArray, NSString, UIAlertController, UIBlockAlertView;

__attribute__((visibility("hidden")))
@interface QMAlertController : UIViewController
{
    UIBlockAlertView *_alertView;
    int _alertControllerStyle;
    NSMutableArray *_alertActions;
    NSString *_alertTitle;
    NSString *_alertMessage;
    UIAlertController *_alertController;
}

+ (void)showInViewController:(id)arg1 title:(id)arg2 message:(id)arg3 leftTitle:(id)arg4 leftBlock:(CDUnknownBlockType)arg5 rightTitle:(id)arg6 rightBlock:(CDUnknownBlockType)arg7;
+ (void)showInViewController:(id)arg1 title:(id)arg2 message:(id)arg3 actionTitle:(id)arg4 actionBlock:(CDUnknownBlockType)arg5;
+ (void)showInViewController:(id)arg1 title:(id)arg2;
+ (id)alertControllerWithTitle:(id)arg1 message:(id)arg2 preferredStyle:(int)arg3;
+ (BOOL)isAlertControllerEnabled;
@property(retain) UIAlertController *alertController; // @synthesize alertController=_alertController;
@property(retain) NSString *alertMessage; // @synthesize alertMessage=_alertMessage;
@property(retain) NSString *alertTitle; // @synthesize alertTitle=_alertTitle;
@property(retain) NSMutableArray *alertActions; // @synthesize alertActions=_alertActions;
@property int alertControllerStyle; // @synthesize alertControllerStyle=_alertControllerStyle;
@property(retain) UIBlockAlertView *alertView; // @synthesize alertView=_alertView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)_split:(id)arg1 toCancelAction:(id *)arg2 otherActions:(id *)arg3 orderedActions:(id *)arg4;
- (void)showInViewController:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (int)getPreferredStyle;
- (id)title;
- (id)getTextFields;
- (id)getActions;
- (id)getMessage;
- (void)addTextFieldWithConfigurationHandler:(CDUnknownBlockType)arg1;
- (void)addAction:(id)arg1;
- (id)initControllerWithTitle:(id)arg1 message:(id)arg2 preferredStyle:(int)arg3;

@end

