//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CLLocationManagerDelegate.h"
#import "MKMapViewDelegate.h"
#import "QReverseGeocoderDelegate.h"
#import "QUserLocationOffsetMgrDelegate.h"
#import "UIScrollViewDelegate.h"

@class CADisplayLink, CLLocationManager, MKMapView, NSArray, NSMutableArray, NSString, QAnnotationContainerView, QAnnotationView, QCallOutView, QMapDataMgr, QReachability, QReverseGeocoder, QScrollView, QSearchInternal, QUserLocation, QUserLocationOffsetMgr, QUserLocationView, UIImageView;

@interface QMapViewInternal : UIView <UIScrollViewDelegate, CLLocationManagerDelegate, QReverseGeocoderDelegate, MKMapViewDelegate, QUserLocationOffsetMgrDelegate>
{
    id <QMapViewDelegate> _mapViewDelegate;
    unsigned int _mapType;
    QScrollView *_tileScrollView;
    QMapDataMgr *_mapDataMgr;
    UIImageView *_imageView;
    NSMutableArray *_annotationViewReuseQueue;
    QAnnotationContainerView *_annotationContainerView;
    float _lastScale;
    struct CGPoint _lastContentOffset;
    QUserLocation *_userLocation;
    QUserLocationView *_userLocationView;
    CLLocationManager *_locationManager;
    BOOL _isStartUserLocation;
    QUserLocationOffsetMgr *_userLocationOffsetMgr;
    QReverseGeocoder *_reverseGeocode;
    QAnnotationView *_longPressPointView;
    BOOL _longPressedEnabled;
    MKMapView *_mapView;
    QCallOutView *_callOutView;
    QSearchInternal *mSearcher;
    SEL _selAnnotationPositionChanged;
    SEL _selAnnotationScaleChanged;
    SEL _selOverlayScaleChanged;
    SEL _selOverlayScaleChangedWithFactor;
    BOOL _isStartMapZoomScaleAnimation;
    BOOL _isCityBoundsReady;
    CDStruct_34734122 tmp;
    CDStruct_34734122 tmpgap;
    int times;
    double tmpWidth;
    double tmpHeight;
    double tmpWidthgap;
    double tmpHeightgap;
    BOOL _isZoomEnabled;
    BOOL _isScrollEnabled;
    BOOL _isShowsUserLocation;
    BOOL _isUserLocationVisible;
    BOOL _isScrollAnimated;
    NSArray *_annotations;
    float _currentScale;
    UIView *_overlayContainerView;
    QReachability *_hostReachability;
    CADisplayLink *_displayLink;
    CDStruct_2c43369c _centerCoordinate;
    CDStruct_34734122 _newMapCenter;
    CDStruct_02837cd9 _visibleMapRect;
    CDStruct_feeb6407 _region;
}

@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) QReachability *hostReachability; // @synthesize hostReachability=_hostReachability;
@property(retain, nonatomic) UIView *overlayContainerView; // @synthesize overlayContainerView=_overlayContainerView;
@property(nonatomic) CDStruct_c3b9c2ee newMapCenter; // @synthesize newMapCenter=_newMapCenter;
@property(nonatomic) BOOL isScrollAnimated; // @synthesize isScrollAnimated=_isScrollAnimated;
@property(nonatomic) float currentScale; // @synthesize currentScale=_currentScale;
@property(nonatomic) BOOL isStartUserLocation; // @synthesize isStartUserLocation=_isStartUserLocation;
@property(retain, nonatomic) QAnnotationView *longPressPointView; // @synthesize longPressPointView=_longPressPointView;
@property(retain, nonatomic) QReverseGeocoder *reverseGeocode; // @synthesize reverseGeocode=_reverseGeocode;
@property(nonatomic) QUserLocation *userLocation; // @synthesize userLocation=_userLocation;
@property(nonatomic, getter=isUserLocationVisible) BOOL userLocationVisible; // @synthesize userLocationVisible=_isUserLocationVisible;
@property(nonatomic) BOOL showsUserLocation; // @synthesize showsUserLocation=_isShowsUserLocation;
@property(nonatomic, getter=isLongPressedEnabled) BOOL longPressedEnabled; // @synthesize longPressedEnabled=_longPressedEnabled;
@property(nonatomic) unsigned int mapType; // @synthesize mapType=_mapType;
@property(nonatomic) id <QMapViewDelegate> delegate; // @synthesize delegate=_mapViewDelegate;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)deselectAnnotation:(id)arg1 animated:(BOOL)arg2;
- (void)selectAnnotation:(id)arg1 animated:(BOOL)arg2;
- (id)dequeueReusableAnnotationViewWithIdentifier:(id)arg1;
- (id)viewForAnnotation:(id)arg1;
@property(readonly, nonatomic) NSArray *annotations; // @synthesize annotations=_annotations;
- (void)removeAnnotations:(id)arg1;
- (void)removeAnnotation:(id)arg1;
- (void)addAnnotations:(id)arg1;
- (void)addAnnotation:(id)arg1;
- (void)notifyLocationOffsetMgrState:(unsigned int)arg1 location:(id)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)updateUserLocation:(id)arg1;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (BOOL)isShowsUserLocation;
@property(nonatomic, getter=isScrollEnabled) BOOL scrollEnabled; // @synthesize scrollEnabled=_isScrollEnabled;
@property(nonatomic, getter=isZoomEnabled) BOOL zoomEnabled; // @synthesize zoomEnabled=_isZoomEnabled;
- (CDStruct_90e2a262)convertRect:(struct CGRect)arg1 toRegionFromView:(id)arg2;
- (struct CGRect)convertRegion:(CDStruct_90e2a262)arg1 toRectToView:(id)arg2;
- (CDStruct_c3b9c2ee)convertPoint:(struct CGPoint)arg1 toCoordinateFromView:(id)arg2;
- (struct CGPoint)convertCoordinate:(CDStruct_c3b9c2ee)arg1 toPointToView:(id)arg2;
- (CDStruct_90e2a262)mapRectThatFits:(CDStruct_90e2a262)arg1 edgePadding:(struct UIEdgeInsets)arg2;
- (void)setVisibleMapRect:(CDStruct_90e2a262)arg1 edgePadding:(struct UIEdgeInsets)arg2 animated:(BOOL)arg3;
- (CDStruct_90e2a262)mapRectThatFits:(CDStruct_90e2a262)arg1;
- (void)setVisibleMapRect:(CDStruct_90e2a262)arg1 animated:(BOOL)arg2;
@property(nonatomic) CDStruct_90e2a262 visibleMapRect; // @synthesize visibleMapRect=_visibleMapRect;
- (struct CGRect)visibleRect;
- (CDStruct_90e2a262)regionThatFits:(CDStruct_90e2a262)arg1;
- (void)setCenterCoordinate:(CDStruct_c3b9c2ee)arg1 animated:(BOOL)arg2;
- (void)setCenterCoordinate:(CDStruct_c3b9c2ee)arg1 animated:(BOOL)arg2 withDelegate:(BOOL)arg3;
@property(nonatomic) CDStruct_c3b9c2ee centerCoordinate; // @synthesize centerCoordinate=_centerCoordinate;
- (void)setRegion:(CDStruct_90e2a262)arg1 animated:(BOOL)arg2;
@property(nonatomic) CDStruct_90e2a262 region; // @synthesize region=_region;
- (void)zoomOut;
- (void)zoomIn;
@property(nonatomic) int zoomLevel;
- (void)updateMapView;
- (void)sosoMapToGoogleMap;
- (BOOL)isInChina:(CDStruct_c3b9c2ee)arg1;
- (void)reverseGeocoder:(id)arg1 didFailWithError:(unsigned int)arg2;
- (void)reverseGeocoder:(id)arg1 didFindPlacemark:(id)arg2;
- (void)longPressedAtPoint:(struct CGPoint)arg1;
- (void)performDelegate;
- (void)zoomOutWidthPoint:(struct CGPoint)arg1;
- (void)zoomInWidthPoint:(struct CGPoint)arg1;
- (void)animationShineDidStop1:(id)arg1 context:(void *)arg2;
- (void)stopDropDownAnimation;
- (void)doStarZoomAnimating:(void *)arg1 scaleFactor:(float)arg2;
- (void)startMapZoomScaleAnimation:(float)arg1 zoomRect:(struct CGRect)arg2;
- (void)mapViewPositionChange;
- (void)mapViewScaleChange;
- (void)memoryWarningNotification:(id)arg1;
- (void)dealloc;
- (id)locationManager;
- (void)showCallOutView:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)viewForOverlay:(id)arg1;
@property(readonly, nonatomic) NSArray *overlays;
- (void)insertOverlay:(id)arg1 belowOverlay:(id)arg2;
- (void)insertOverlay:(id)arg1 aboveOverlay:(id)arg2;
- (void)exchangeOverlayAtIndex:(unsigned int)arg1 withOverlayAtIndex:(unsigned int)arg2;
- (void)insertOverlay:(id)arg1 atIndex:(unsigned int)arg2;
- (void)removeOverlays:(id)arg1;
- (void)removeOverlay:(id)arg1;
- (void)addOverlays:(id)arg1;
- (void)addOverlay:(id)arg1;
- (void)handleQTwoFingersSingleTap:(id)arg1;
- (void)handleQDoubleTap:(id)arg1;
- (void)handleQSingleTap:(id)arg1;
- (void)handleQLongPress:(id)arg1;
- (void)handlePan:(id)arg1;
- (void)initGestureRecognizer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

