//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QMBMWHMIBaseVC.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface QMBMWChannelRootVC : QMBMWHMIBaseVC
{
    NSMutableArray *_channelArray;
}

@property(retain, nonatomic) NSMutableArray *channelArray; // @synthesize channelArray=_channelArray;
- (void).cxx_destruct;
- (void)registerActionsAndEvents;
- (void)hmiStateFocusChange:(BOOL)arg1;
- (void)playSong:(id)arg1;
- (void)selChannel:(id)arg1;
- (BOOL)_isSamePlayingList:(id)arg1;
- (void)featureDidStop;
- (void)updateSongList:(id)arg1;
- (void)hmiStateVisibleChange:(BOOL)arg1;
- (void)featureDidStart;
- (id)initWithFeatureController:(id)arg1 hmiStateComponentId:(int)arg2;

@end

