//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QMChannelHomeView, QMChannelPieceView;

@protocol QMChannelHomeViewDelegate <NSObject>
- (void)channelHomeViewDidScroll:(QMChannelHomeView *)arg1;
- (void)channelHomeView:(QMChannelHomeView *)arg1 didTapPieceView:(QMChannelPieceView *)arg2;
@end

