//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface QMChannelHelper : NSObject
{
}

+ (id)getFormatIntroductionStr:(id)arg1 andIsReplaceZhibiao:(BOOL)arg2;
+ (id)getIntroductHtmlStr:(id)arg1;
+ (void)updateSideFadingImageView:(id)arg1 withImage:(id)arg2 restrictedInRect:(struct CGRect)arg3;
+ (id)getAdjustedImageFromImage:(id)arg1 toSize:(struct CGSize)arg2 withStyle:(int)arg3;

@end

