//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "QMChirrupRecorderDelegate.h"
#import "QMChirrupVCResetDelegate.h"

@class NSString, QMChirrupHistoryView, SongInfo;

__attribute__((visibility("hidden")))
@interface QMChirrupVC : SkinViewController <QMChirrupRecorderDelegate, QMChirrupVCResetDelegate>
{
    QMChirrupHistoryView *_viewHistory;
    NSString *_codeid;
    SongInfo *_songinfo;
    BOOL isViewShow;
}

- (void).cxx_destruct;
- (void)leaveRecordState;
- (void)enterRecordState;
- (void)delayPlay:(id)arg1;
- (void)nowPlayingButtonPressed:(id)arg1;
- (void)delayShowAlbumInfo:(id)arg1;
- (void)showAlbumInfo:(id)arg1 fromVC:(id)arg2;
- (void)delayShowSingerInfo:(id)arg1;
- (void)showSingerInfo:(id)arg1;
- (void)sendChirrup:(id)arg1;
- (void)recvChirrup:(id)arg1;
- (void)onChirrupSuccess:(id)arg1;
- (void)onChirrupData:(void *)arg1 Length:(int)arg2;
- (void)onNotifyReturnMiniPlayerFromPlayingView:(id)arg1;
- (void)onNotifySongsChangedLoveState:(id)arg1;
- (void)reqSong:(id)arg1;
- (int)vcType;
- (void)checkNewVersion;
- (void)doHandlePushComming:(id)arg1;
- (void)actionSheet:(id)arg1 actionSheetButtonClickedAtIndex:(int)arg2;
- (BOOL)showDelBtnInActionSheet:(id)arg1;
- (BOOL)enableShake;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)delayBack:(id)arg1;
- (void)back:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)loadView;
- (id)initWithSongInfo:(id)arg1;
- (id)initWithCodeid:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

