//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QMInfoTableViewCell.h"

__attribute__((visibility("hidden")))
@interface QMDetailViewCell : QMInfoTableViewCell
{
    BOOL _bMultiLine;
    float _height;
}

@property(nonatomic) BOOL bMultiLine; // @synthesize bMultiLine=_bMultiLine;
@property(nonatomic) float height; // @synthesize height=_height;
- (void)layoutSubviews;

@end

