//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, NSTimer;

__attribute__((visibility("hidden")))
@interface QMFlowCountVC : SkinViewController <UITableViewDataSource, UITableViewDelegate>
{
    NSTimer *refreshTimer;
    double lastTime;
}

@property(retain, nonatomic) NSTimer *refreshTimer; // @synthesize refreshTimer;
- (void).cxx_destruct;
- (void)pingFinish:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)delayReloadData;
- (void)openScreenFlowCountView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)flowCountCovertBetyToResult:(long long)arg1;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)back:(id)arg1;
- (void)setFlowCountToScreenView;
- (void)refreshData;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

