//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QMWebImageView, UIImageView;

__attribute__((visibility("hidden")))
@interface QMFocusView : UIView
{
    QMWebImageView *_focusImageView;
    UIImageView *_topInverseImageView;
}

@property(readonly, nonatomic) UIImageView *topInverseImageView; // @synthesize topInverseImageView=_topInverseImageView;
@property(retain, nonatomic) QMWebImageView *focusImageView; // @synthesize focusImageView=_focusImageView;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithFrame:(struct CGRect)arg1 showTopInverseImage:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

