//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

__attribute__((visibility("hidden")))
@interface QMMiniPlayerPlayButton : UIButton
{
    BOOL _isShowBackgroundColor;
    float _progress;
}

@property(nonatomic) BOOL isShowBackgroundColor; // @synthesize isShowBackgroundColor=_isShowBackgroundColor;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void)drawRect:(struct CGRect)arg1;
- (id)accessibilityLabel;

@end

