//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MTAnimatedLabel, MarqueeLabel, UIImageView;

__attribute__((visibility("hidden")))
@interface QMMiniPlayerSongInfoView : UIView
{
    UIImageView *_songImageView;
    MarqueeLabel *_songNameLabel;
    MarqueeLabel *_singerNameLabel;
    MTAnimatedLabel *_defaultTipLabel;
    id <QMMiniPlayerSongInfoViewDelegate> _delegate;
}

@property(nonatomic) id <QMMiniPlayerSongInfoViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MTAnimatedLabel *defaultTipLabel; // @synthesize defaultTipLabel=_defaultTipLabel;
@property(retain, nonatomic) MarqueeLabel *singerNameLabel; // @synthesize singerNameLabel=_singerNameLabel;
@property(retain, nonatomic) MarqueeLabel *songNameLabel; // @synthesize songNameLabel=_songNameLabel;
@property(retain, nonatomic) UIImageView *songImageView; // @synthesize songImageView=_songImageView;
- (void).cxx_destruct;
- (void)touchAction:(id)arg1;
- (void)setDefaultTipLabelHidden:(BOOL)arg1;
- (void)buildView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

