//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPageControl.h"

@class NSArray, UIImage;

__attribute__((visibility("hidden")))
@interface QMPageControl : UIPageControl
{
    UIImage *_activeImage;
    UIImage *_inactiveImage;
    NSArray *_usedToRetainOriginalSubview;
    float _kSpacing;
}

@property float kSpacing; // @synthesize kSpacing=_kSpacing;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)setNumberOfPages:(int)arg1;
- (void)setCurrentPage:(int)arg1;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)updateCurrentPageDisplay;
- (void)updateDots;
- (void)onNotifyColorStyleChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

