//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage, UIView;

@protocol QMPersonalCenterHeaderViewDataSource <NSObject>
- (NSString *)mainTitle;
- (UIImage *)headerImage;

@optional
- (UIImage *)blurHeaderImage:(UIImage *)arg1;
- (void)jumpToBuyTicketWeb;
- (UIImage *)showCoverImage;
- (void)gotoSingerDetailView;
- (UIImage *)headerImage:(BOOL)arg1;
- (UIView *)secondRightButtomView;
- (UIView *)firstRightButtomView;
- (UIView *)firstLeftBottomView;
- (UIView *)thirdSubView;
- (UIView *)secondSubView;
- (UIView *)firstSubView;
- (UIImage *)logoFollowingMainTitle;
@end

