//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BETouchView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UIView;

__attribute__((visibility("hidden")))
@interface QMPlayingQPlayTable : BETouchView <UITableViewDataSource, UITableViewDelegate>
{
    UIView *_QPlayDeviceList;
    id <QMPlayingViewDelegate> _playingDelegate;
}

@property(nonatomic) __weak id <QMPlayingViewDelegate> playingDelegate; // @synthesize playingDelegate=_playingDelegate;
@property(retain, nonatomic) UIView *QPlayDeviceList; // @synthesize QPlayDeviceList=_QPlayDeviceList;
- (void).cxx_destruct;
- (void)reloadData;
- (void)groupAccessoryButtonTapped:(id)arg1 withEvent:(id)arg2;
- (id)makeGroupAccessoryButton;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)setQPlayDeviceTableViewFrame;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)hideQPlayDeviceTableView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

