//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "EGORefreshTableHeaderDelegate.h"
#import "UITextFieldDelegate.h"

@class EGORefreshTableHeaderView, NSMutableDictionary, NSString, ProtocolHistoryRequestItem, UIButton, UITextField, UIView;

__attribute__((visibility("hidden")))
@interface QMProtocolDebugVC : SkinViewController <UITextFieldDelegate, EGORefreshTableHeaderDelegate>
{
    BOOL reloading;
    ProtocolHistoryRequestItem *_requestItem;
    NSMutableDictionary *_protocolDebugDataCopy;
    NSMutableDictionary *_filterProtocolDebugDataCopy;
    UIView *_searchUIContainerView;
    UITextField *_searchTextField;
    UIButton *_searchCancleButton;
    EGORefreshTableHeaderView *refreshHeaderView;
}

@property(nonatomic) BOOL reloading; // @synthesize reloading;
@property(retain, nonatomic) EGORefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(retain, nonatomic) UIButton *searchCancleButton; // @synthesize searchCancleButton=_searchCancleButton;
@property(retain, nonatomic) UITextField *searchTextField; // @synthesize searchTextField=_searchTextField;
@property(retain, nonatomic) UIView *searchUIContainerView; // @synthesize searchUIContainerView=_searchUIContainerView;
@property(retain, nonatomic) NSMutableDictionary *filterProtocolDebugDataCopy; // @synthesize filterProtocolDebugDataCopy=_filterProtocolDebugDataCopy;
@property(retain, nonatomic) NSMutableDictionary *protocolDebugDataCopy; // @synthesize protocolDebugDataCopy=_protocolDebugDataCopy;
@property(retain, nonatomic) ProtocolHistoryRequestItem *requestItem; // @synthesize requestItem=_requestItem;
- (void).cxx_destruct;
- (id)_drawProtocolDebugDetailView;
- (id)_meaningfulWorkresultText:(int)arg1;
- (id)_debugDataForDisplay;
- (void)_searchCancelButtonTapped:(id)arg1;
- (void)_searchTextChanged:(id)arg1;
- (void)_searchTextFieldTouchDown:(id)arg1;
- (id)_getFilterProtocolDebugDataCopy;
- (id)_getProtocolHistoryRequestItemAtIndexPath:(id)arg1;
- (id)_getProtocolDebugDictForSection:(int)arg1;
- (id)_objectAtIndex:(int)arg1 inDictionary:(id)arg2;
- (id)_keyAtIndex:(int)arg1 inDictionary:(id)arg2;
- (void)textFieldDidBeginEditing:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)doneLoadingTableViewData;
- (id)egoRefreshTableHeaderDataSourceLastUpdated:(id)arg1;
- (BOOL)egoRefreshTableHeaderDataSourceIsLoading:(id)arg1;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)reFresh;
- (int)headerHight;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

