//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface QMRotationArrowIcon : UIControl
{
    BOOL _selectedStatus;
    UIView *_leftPart;
    UIView *_rightPart;
}

@property(retain, nonatomic) UIView *rightPart; // @synthesize rightPart=_rightPart;
@property(retain, nonatomic) UIView *leftPart; // @synthesize leftPart=_leftPart;
@property(readonly, nonatomic, getter=isSelectedStatus) BOOL selectedStatus; // @synthesize selectedStatus=_selectedStatus;
- (void).cxx_destruct;
- (void)setSelectedStatus:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1 actionTarget:(id)arg2 actionSelector:(SEL)arg3;

@end

