//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AppidCheckRequestDelegate.h"

@class AppidCheckRequest, NSError, NSString;

@interface QMSdkDataMgr : NSObject <AppidCheckRequestDelegate>
{
    BOOL _openLog;
    int _initState;
    NSError *_initErr;
    NSString *_appid;
    NSString *_appkey;
    AppidCheckRequest *_aidRequest;
}

+ (BOOL)registerPluginWithId:(id)arg1;
+ (int)initResult;
+ (BOOL)canProcess;
+ (id)instance;
@property(retain, nonatomic) AppidCheckRequest *aidRequest; // @synthesize aidRequest=_aidRequest;
@property(nonatomic) BOOL openLog; // @synthesize openLog=_openLog;
@property(retain, nonatomic) NSString *appkey; // @synthesize appkey=_appkey;
@property(retain, nonatomic) NSString *appid; // @synthesize appid=_appid;
@property(retain, nonatomic) NSError *initErr; // @synthesize initErr=_initErr;
@property(nonatomic) int initState; // @synthesize initState=_initState;
- (void)checkAppid:(id)arg1 error:(id)arg2 type:(int)arg3;
- (void)checkAppid:(id)arg1 success:(id)arg2;
- (void)checkAppid:(id)arg1 appkey:(id)arg2;
- (void)dealloc;
- (id)init;

@end

