//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UIWebViewDelegate.h"

@class NSArray, NSString, UILabel, UISearchBar;

__attribute__((visibility("hidden")))
@interface QMShowLogVC : SkinViewController <UISearchBarDelegate, UIWebViewDelegate, UIGestureRecognizerDelegate>
{
    int _currentLevel;
    NSString *_currentCategory;
    NSString *_currentSearchStr;
    UISearchBar *_searchBar;
    UILabel *_resultLabel;
    NSArray *_logArray;
    NSArray *_totalLogArray;
}

@property(retain, nonatomic) NSArray *totalLogArray; // @synthesize totalLogArray=_totalLogArray;
@property(retain, nonatomic) NSArray *logArray; // @synthesize logArray=_logArray;
@property(retain, nonatomic) UILabel *resultLabel; // @synthesize resultLabel=_resultLabel;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) NSString *currentSearchStr; // @synthesize currentSearchStr=_currentSearchStr;
@property(retain, nonatomic) NSString *currentCategory; // @synthesize currentCategory=_currentCategory;
@property(nonatomic) int currentLevel; // @synthesize currentLevel=_currentLevel;
- (void).cxx_destruct;
- (id)getLogWithLevel:(int)arg1 withCategory:(id)arg2 withSearchText:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)_getCurLogStr:(id)arg1;
- (id)_getAttributedStringWithItem:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)_onTitleBarTapped;
- (void)onSettingButtonClicked:(id)arg1;
- (void)reloadData;
- (void)loadDataWithParam:(id)arg1;
- (id)emptyViewText;
- (void)didReceiveMemoryWarning;
- (void)viewDidPop;
- (void)viewDidLoad;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

