//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

__attribute__((visibility("hidden")))
@interface QMWaveDataView : UIView
{
    float fRed;
    float fGreen;
    float fBlue;
    float fWidth;
    float fHeight;
    float fSep;
    int nTimes;
    int nMSPerTime;
    BOOL isLightColor;
    vector_df58a32d *pVectWaveData;
    unsigned int dataLen;
    vector_2995ee75 *pVectPointData;
}

@property(nonatomic) BOOL isLightColor; // @synthesize isLightColor;
@property(nonatomic) vector_2995ee75 *pVectPointData; // @synthesize pVectPointData;
@property(nonatomic) unsigned int dataLen; // @synthesize dataLen;
@property(nonatomic) vector_df58a32d *pVectWaveData; // @synthesize pVectWaveData;
- (void)dealloc;
- (void)addData:(short *)arg1 dataLenByShort:(unsigned int)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)reloadColor;
- (id)initWithFrame:(struct CGRect)arg1;

@end

