//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface QPlayAuthProtocol : ProtocolBaseJason
{
    BOOL authed;
    NSDictionary *authInfo;
    NSString *identifier;
}

@property(nonatomic) BOOL authed; // @synthesize authed;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier;
@property(retain, nonatomic) NSDictionary *authInfo; // @synthesize authInfo;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (BOOL)canReportError;
- (int)cid;
- (id)init;

@end

