//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QPlaySpeaker.h"

@class NSDate, NSObject<OS_dispatch_queue>;

__attribute__((visibility("hidden")))
@interface QPlayStandardSpeaker : QPlaySpeaker
{
    int _eqObserverCount;
    NSObject<OS_dispatch_queue> *_renderingControlQueue;
}

@property(readonly, nonatomic) __weak NSObject<OS_dispatch_queue> *renderingControlQueue; // @synthesize renderingControlQueue=_renderingControlQueue;
@property(nonatomic) int eqObserverCount; // @synthesize eqObserverCount=_eqObserverCount;
- (void).cxx_destruct;
- (void)_attachWithSongs:(id)arg1 queueID:(int)arg2;
- (id)uriOfOwnQueue;
- (id)makeUrisAndMetadata:(id)arg1;
- (id)getContextFromMetaData:(id)arg1;
- (long long)getSongIDFromMetaData:(id)arg1;
- (void)tryToAttach2;
- (void)tryToAttach;
- (unsigned int)queueCapability;
- (void)getSpeakerMaxTracksCount;
- (void)getTracksCount;
- (void)getTracksInfo:(int)arg1 numberOfTracks:(int)arg2;
- (void)getMediaInfo;
- (void)removeTracksInRangeFromQueue:(struct _NSRange)arg1;
- (void)addTracks:(id)arg1 toQueueAtIndex:(int)arg2;
- (BOOL)replaceAllTracks:(id)arg1 currentTrackIndex:(int)arg2 newCurrentTrackIndex:(int)arg3 newNextTrackIndex:(int)arg4;
- (void)setTrackInfo;
- (void)qplayQueue4;
- (void)playQueue3;
- (void)playQueue2:(id)arg1;
- (id)description;
- (id)getAllNeededServices;
- (BOOL)supportQPlay;
- (void)dealloc;
- (void)setLogo:(id)arg1;
- (void)setNameWithControlPoint:(id)arg1 controlPoint:(id)arg2;
- (id)initWithIdentifer:(id)arg1 controlPoint:(id)arg2;
- (BOOL)performQAction:(id)arg1 arguments:(id)arg2 result:(id *)arg3;

// Remaining properties
@property(nonatomic) CDStruct_1b6d18a9 positionSnapshot;
@property(copy, nonatomic) NSDate *positionSnapshotTimeStamp;

@end

