//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QOverlayPathView.h"

@class QPolygon;

@interface QPolygonView : QOverlayPathView
{
    QPolygon *_polygon;
    float _mapScale;
}

@property(readonly, nonatomic) QPolygon *polygon; // @synthesize polygon=_polygon;
- (void)drawMapRect:(CDStruct_90e2a262)arg1 zoomScale:(float)arg2 inContext:(struct CGContext *)arg3;
- (BOOL)canDrawMapRect:(CDStruct_90e2a262)arg1 zoomScale:(float)arg2;
- (void)polygon:(id)arg1 toPath:(struct CGPath *)arg2;
- (id)initWithPolygon:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

