//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "FollowMoreDataManagerDelegate.h"
#import "FollowTableViewImageManagerDelegate.h"
#import "ImageManagerDelegate.h"
#import "QMSearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FollowMoreDataManager, NSString, QMSearchBar, UITableView, UIView;

__attribute__((visibility("hidden")))
@interface QQFriendsGroupVC : SkinViewController <QMSearchBarDelegate, FollowMoreDataManagerDelegate, FollowTableViewImageManagerDelegate, UITableViewDataSource, UITableViewDelegate, ImageManagerDelegate>
{
    BOOL isSearching;
    int _groupid;
    FollowMoreDataManager *_dataManager;
    QMSearchBar *_searchBar;
    UITableView *_searchTable;
    UIView *_dimView;
}

@property(retain, nonatomic) UIView *dimView; // @synthesize dimView=_dimView;
@property(retain, nonatomic) UITableView *searchTable; // @synthesize searchTable=_searchTable;
@property(retain, nonatomic) QMSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) FollowMoreDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(nonatomic) int groupid; // @synthesize groupid=_groupid;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)dismissSearchTableView;
- (void)switchToQQFriensTable;
- (void)cancleKeyboard;
- (void)newSearchTable;
- (void)hideDimView;
- (void)showDimView;
- (BOOL)searchRemarkName:(id)arg1 inQQFriendItem:(id)arg2;
- (BOOL)searchUserName:(id)arg1 inQQFriendItem:(id)arg2;
- (BOOL)searchUin:(id)arg1 inQQFriendItem:(id)arg2;
- (void)beginSearchWithSearchKey:(id)arg1;
- (void)searchTextChanged:(id)arg1;
- (void)searchTextFieldTouchDown:(id)arg1;
- (void)searchCancleButtonClicked:(id)arg1;
- (void)onSearchButtonClicked:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 TableView:(id)arg2 ImageFile:(id)arg3;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)findQQFriendItemWithUin:(unsigned long)arg1;
- (void)hostCallbackWithProtocol:(id)arg1 Result:(int)arg2;
- (id)emptyViewBgText;
- (id)emptyViewBgImage;
- (id)emptyViewText;
- (void)recommendToQQFriends;
- (void)syncFollowStatus:(id)arg1;
- (void)queryFollowQQFriendWithUin:(unsigned long)arg1 isFollow:(BOOL)arg2 AndCellIndex:(int)arg3;
- (void)queryQQFriendGroupDetailInfo:(int)arg1;
- (void)newSongTable;
- (int)searchHeight;
- (void)reFresh;
- (int)vcType;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidPop;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

