//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QQLineLyric : NSObject
{
    long _time;
    NSString *_text;
}

@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property long time; // @synthesize time=_time;
- (void).cxx_destruct;
- (BOOL)isTimeValided;
- (int)compareTime:(id)arg1;
- (id)description;
- (id)initWithTime:(long)arg1 text:(id)arg2;

@end

