//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface QQLuaPluginObject : NSObject
{
    NSString *_pluginId;
    id _luaPluginService;
    NSArray *_pluginServiceNames;
    NSString *_appVersion;
    NSString *_deviceType;
    NSString *_osVersion;
    NSString *_md5Value;
    NSString *_downloadUrl;
}

+ (id)translateToQQLuaPluginObjectFromDic:(id)arg1;
@property(retain, nonatomic) NSString *downloadUrl; // @synthesize downloadUrl=_downloadUrl;
@property(retain, nonatomic) NSString *md5Value; // @synthesize md5Value=_md5Value;
@property(retain, nonatomic) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(retain, nonatomic) NSString *deviceType; // @synthesize deviceType=_deviceType;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *pluginId; // @synthesize pluginId=_pluginId;
- (BOOL)isOsVersionInRange:(id)arg1;
- (BOOL)isLuaScriptFileRunForThisDevice;
- (BOOL)cleanMemory;
- (BOOL)isAvailable;
- (id)getDependentServices;
- (int)getVersion;
- (BOOL)isSuportService:(id)arg1;
- (id)getServices;
- (id)invokeService:(id)arg1 withParam:(id)arg2;
- (BOOL)initLuaPluginService;
- (void)dealloc;
- (void)initParam;
- (id)initWithPluginId:(id)arg1;

@end

