//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface QRouteSegmentForBus : NSObject
{
    unsigned int _distance;
    NSString *_name;
    unsigned int _stationNum;
    unsigned int _time;
    int _type;
    NSMutableArray *_routeNodeList;
    NSString *_whereGetOn;
    NSString *_whereGetOff;
    int _walkDirection;
    int _startIndex;
    int _endIndex;
}

@property(nonatomic) int endIndex; // @synthesize endIndex=_endIndex;
@property(nonatomic) int startIndex; // @synthesize startIndex=_startIndex;
@property(nonatomic) int walkDirection; // @synthesize walkDirection=_walkDirection;
@property(retain, nonatomic) NSString *whereGetOff; // @synthesize whereGetOff=_whereGetOff;
@property(retain, nonatomic) NSString *whereGetOn; // @synthesize whereGetOn=_whereGetOn;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) unsigned int time; // @synthesize time=_time;
@property(nonatomic) unsigned int stationNum; // @synthesize stationNum=_stationNum;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned int distance; // @synthesize distance=_distance;
- (void)dealloc;
- (id)init;

@end

