//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSoundSubVC : SkinViewController <UITableViewDataSource, UITableViewDelegate>
{
    int _type;
}

@property int type; // @synthesize type=_type;
- (void)loginFail;
- (void)loginSucess:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)headerCancelAction;
- (void)createCommonHeaderView;
- (void)viewDidPop;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

