//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QSoundMainVC : SkinViewController <UITableViewDataSource, UITableViewDelegate>
{
    BOOL _isYJEnable;
    BOOL _isEQEnable;
    BOOL _isSREnable;
}

+ (id)getSRNameWithParam:(int)arg1;
+ (id)getEQNameWithParam:(int)arg1;
+ (id)getCurrentEffectName;
@property BOOL isSREnable; // @synthesize isSREnable=_isSREnable;
@property BOOL isEQEnable; // @synthesize isEQEnable=_isEQEnable;
@property BOOL isYJEnable; // @synthesize isYJEnable=_isYJEnable;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (void)pushView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)applySetting;
- (void)_onSwitchSection03Clicked:(id)arg1;
- (void)_onSwitchSection02Clicked:(id)arg1;
- (void)_onSwitchSection01Clicked:(id)arg1;
- (void)headerCancelAction;
- (void)createCommonHeaderView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidPop;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

