//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "BackgroundThreadDelegate.h"
#import "QImageDownloadMgrDelegate.h"
#import "QOpenGLRenderTimerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class BackgroundThread, CMAttitude, CMMotionManager, EAGLContext, NSArray, NSMutableArray, NSString, QImageDownloadMgr, QOpenGLRenderTimer, UIButton, UIImageView, UILabel, UIScrollView;

@interface QStreetView : UIView <BackgroundThreadDelegate, QOpenGLRenderTimerDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate, QImageDownloadMgrDelegate>
{
    int backingWidth;
    int backingHeight;
    unsigned int viewRenderbuffer;
    unsigned int viewFramebuffer;
    unsigned int depthRenderbuffer;
    double animationInterval_;
    int m_nDrawTimes;
    float m_fWdith;
    float m_fHeight;
    EAGLContext *_context;
    EAGLContext *_threadGLContext;
    BOOL isDrawingLock_;
    BOOL isAfterDrawAgain_;
    BOOL isLayoutView_;
    BOOL isTryAgainNet_;
    id delegate_;
    double profileStart_;
    double profileLast_;
    BOOL _isOpenGLOpe;
    BOOL _allocContext;
    BOOL _isAnimationDrawing;
    CMMotionManager *_motionManager;
    CDStruct_6248f162 _deviceMotionParam;
    CMAttitude *referenceAttitude;
    int _pauseSecondForDeviceMotion;
    int _screenOrientation;
    int _justStart;
    QOpenGLRenderTimer *_openGLRenderTimer;
    NSMutableArray *_overlays;
    NSMutableArray *_floorButtonList;
    NSMutableArray *_floorItemList;
    int _selectedFloorIndex;
    NSMutableArray *_photoItemList;
    NSMutableArray *_photoButtonList;
    UIButton *_selectedPhotoFrame;
    int _selectedPhotoIndex;
    QImageDownloadMgr *_imageDownloadMgr;
    void *pWorld;
    BOOL _dirty;
    BackgroundThread *_backgroundThread;
    id <QStreetViewDelegate> _delegate;
    UILabel *_parkViewLabel;
    UIScrollView *_floorBar;
    UIScrollView *_photoBar;
    UIImageView *_logoImageView;
    UIView *_floorPhotoCutLine;
    BOOL _isHaveSetYaw;
    BOOL _isSupportMotionManager;
    BOOL _isSupportES2;
    NSMutableArray *arrAsyncCalback;
    NSString *_svid;
    NSString *_roadName;
    float _yaw;
    float _pitch;
    int _zoom;
    float _mercatorX;
    float _mercatorY;
    NSString *_parkViewName;
    NSString *_title;
    UIButton *_quitParkViewBtn;
}

+ (Class)layerClass;
@property(retain, nonatomic) UIButton *quitParkViewBtn; // @synthesize quitParkViewBtn=_quitParkViewBtn;
@property(nonatomic) BOOL isSupportES2; // @synthesize isSupportES2=_isSupportES2;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *parkViewName; // @synthesize parkViewName=_parkViewName;
@property(readonly, nonatomic) float mercatorY; // @synthesize mercatorY=_mercatorY;
@property(readonly, nonatomic) float mercatorX; // @synthesize mercatorX=_mercatorX;
@property(readonly, nonatomic) int zoom; // @synthesize zoom=_zoom;
@property(readonly, nonatomic) float pitch; // @synthesize pitch=_pitch;
@property(readonly, nonatomic) float yaw; // @synthesize yaw=_yaw;
@property(retain) NSString *roadName; // @synthesize roadName=_roadName;
@property(retain) NSString *svid; // @synthesize svid=_svid;
@property(nonatomic) BOOL isSupportMotionManager; // @synthesize isSupportMotionManager=_isSupportMotionManager;
@property(readonly, nonatomic) NSArray *overlays; // @synthesize overlays=_overlays;
@property(retain, nonatomic) EAGLContext *context; // @synthesize context=_context;
@property(nonatomic) BOOL isHaveSetYaw; // @synthesize isHaveSetYaw=_isHaveSetYaw;
@property(retain, nonatomic) QOpenGLRenderTimer *openGLRenderTimer; // @synthesize openGLRenderTimer=_openGLRenderTimer;
@property(retain, nonatomic) NSMutableArray *arrAsyncCalback; // @synthesize arrAsyncCalback;
@property(nonatomic) id <QStreetViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)updateParkViewName;
- (void)resetViewAfterAnimation;
- (void)moveQuitButtonFrameInVertical:(int)arg1;
- (id)stretchedImage:(id)arg1;
- (void)notifyImageDownloadMgr:(id)arg1 identifier:(id)arg2 image:(id)arg3;
- (id)handlePhotosInParkView:(struct _LibToAppTaskInfo *)arg1;
- (void)didNofifyGestureEvent:(int)arg1;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)setNeedsDisplay;
- (BOOL)showStreetView:(id)arg1;
- (void)reachabilityStatusChanged:(id)arg1;
- (BOOL)removeAllStreetViewOverlays;
- (BOOL)removeStreetViewOverlays:(id)arg1;
- (BOOL)removeStreetViewOverlay:(id)arg1;
- (BOOL)addStreetViewOverlays:(id)arg1;
- (BOOL)addStreetViewOverlay:(id)arg1;
- (void)loadStreetViewIcons;
- (void)pauseDeviceMotionShortTime;
- (void)pauseDeviceMotionLongTime;
- (void)removePoiOverlayItem:(void *)arg1;
- (void)addPoiOverlayItem:(CDStruct_7ebcfa3a *)arg1 animated:(BOOL)arg2 scaleEffect:(BOOL)arg3;
- (void)removePoiOverlay;
- (void)addPoiOverlay:(CDStruct_e817f9f7 *)arg1;
- (void)getOriginX:(int *)arg1 originY:(int *)arg2;
- (void)handlePauseDeviceMotion;
- (void)pauseDeviceMotion:(int)arg1;
- (void)initDeviceMotionInfo;
- (BOOL)isDeviceMotion;
- (void)setScreenOrientation:(int)arg1;
- (void)getDeviceMotionInfo:(const void *)arg1;
- (void)stopDeviceMotion;
- (void)updateDeviceMotion:(id)arg1;
- (void)loopHandleDeviceMotion;
- (void)startQueueForDeviceMotion;
- (void)startDeviceMotion;
- (void)getPOV:(id)arg1 deviceMotionParam:(CDStruct_6248f162 *)arg2;
- (void)processLowMemory;
- (void)mainProcessUIEvent:(id)arg1;
- (void)processUIEvent:(int)arg1;
- (void)setAnimationInterval:(double)arg1;
- (BOOL)isOpenGLOpe;
- (void)reLayoutView:(BOOL)arg1;
- (void)getCurrentImg:(void *)arg1;
- (void)reTryNetLater;
- (void)deLayReTryNetLater;
- (void)setAngleOfPOI:(double)arg1 oY:(double)arg2 poiX:(double)arg3 poiY:(double)arg4 poiName:(id)arg5 svid:(id)arg6;
- (double)printProfileStart:(const char *)arg1;
- (double)printProfile:(const char *)arg1;
- (void)offsetDeviceMotionAngleForResetTrueSensor:(double)arg1 yaw:(double)arg2;
- (void)offsetDeviceMotionAngle:(double)arg1 yaw:(double)arg2;
- (void)offsetAngle:(double)arg1 yawAngle:(double)arg2;
- (void)setPitchAngle:(float)arg1 yawAngle:(float)arg2;
- (void)delayshowNoWifiInfo;
- (void)showNoWifiInfo;
- (void)cancelWifiInfo;
- (void)initLoading;
- (BOOL)isRetina;
- (void)onNetAvailible;
- (void)showHelfInfo;
- (void)showProgressBar:(BOOL)arg1;
- (void)createIconWithText:(int)arg1 imageName:(id)arg2 text:(id)arg3;
- (void)createIcon:(int)arg1 imageName:(id)arg2;
- (void)startStreetBySvid:(const char *)arg1 pointX:(double)arg2 pointY:(double)arg3;
- (void)cancelAllRequest;
- (void)dataError;
- (void)netError;
- (void)handleNetCancel:(id)arg1;
- (void)handleNetFailWithError:(id)arg1;
- (void)handleNetCancelOrError:(id)arg1 resCode:(int)arg2;
- (void)handleDecodeTask:(id)arg1;
- (void)handleNetResponse:(id)arg1;
- (id)glContextForThread;
- (id)glContext;
- (void)sendDecodeReq_FunCallBack:(void *)arg1 ObjectCallBack:(void *)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)layoutOpenGLViewWidth:(float)arg1 Height:(float)arg2 context:(id)arg3;
- (id)layoutOpenGLViewPort:(float)arg1 Height:(float)arg2 context:(id)arg3;
- (void)handleDrawView;
- (void)drawShareView;
- (void)drawView;
- (void)stopAnimation;
- (int)startAnimation;
- (void)destroyBackgroundThread;
- (void)destroyFramebuffer;
- (BOOL)createFramebuffer;
- (void)layoutSubviews;
- (void)startStreetBySvid:(const char *)arg1;
- (void)startStreetBySvid:(const char *)arg1 x:(double)arg2 y:(double)arg3;
- (void)initOverlay:(const void *)arg1 length:(int)arg2;
- (void)initGLES;
- (void)destroyStreetView;
- (void)hibernate;
- (void)releaseOutlets;
- (void)cancelDelayedSelectors;
- (void)rebuild:(struct CGRect)arg1;
- (void)animationLoop;
- (void)renderOpenGLEvent;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleSwipeUp:(id)arg1;
- (void)handlePinch:(id)arg1;
- (void)handleDoubleTap:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (void)handlePan:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)initStreetViewAPIGesture;
- (void)streetViewstreetViewDidBecomeActive:(id)arg1;
- (void)streetViewWillResignActive:(id)arg1;
- (void)streetViewWillEnterForeground:(id)arg1;
- (void)streetViewDidEnterBackground:(id)arg1;
- (void)memoryWarningNotification:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)stretchImageWithName:(id)arg1;
- (void)parkViewPhotoButtonEvent:(id)arg1;
- (void)parkViewFloorButtonEvent:(id)arg1;
- (void)quitParkViewEvent:(id)arg1;
- (void)updatePhotoBar:(id)arg1;
- (void)updateFloorBar;
- (void)removeFloorBar;
- (void)createParkViewLabel;
- (void)createQuitParkViewButton;
- (void)createFloorPhotoCutLine;
- (void)createParkViewPhotoBar:(id)arg1;
- (void)createParkViewFloorBar:(id)arg1;
- (void)createParkView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 context:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)mainProcessAllUIEvent:(id)arg1;
- (void)libStateEvent:(id)arg1;
- (void)poiClickEvent:(CDStruct_7ebcfa3a *)arg1;
- (void *)handleLibToAppTaskDetail:(struct _LibToAppTaskInfo *)arg1;
- (void)updateCameraInfo:(id)arg1;
- (void)updateStreetInfo:(id)arg1;
- (void)netRequest:(struct SvNetReq *)arg1;
- (void)cancelTask:(void *)arg1;
- (void)cancelTasks:(void *)arg1 withTaskNum:(unsigned long)arg2;
- (void)handleLibToAppTask;
- (void)showParkView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

