//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class BuluoCluster, ListBase, ShowCluster, SingerCluster;

__attribute__((visibility("hidden")))
@interface QuerySingerInfoProtocol : ProtocolBaseJason
{
    SingerCluster *cluster;
    ListBase *list;
    int retState;
    int queryType;
    ShowCluster *_showInfoResult;
    BuluoCluster *_buluoInfoResult;
}

@property(retain, nonatomic) BuluoCluster *buluoInfoResult; // @synthesize buluoInfoResult=_buluoInfoResult;
@property(retain, nonatomic) ShowCluster *showInfoResult; // @synthesize showInfoResult=_showInfoResult;
@property(nonatomic) int queryType; // @synthesize queryType;
@property(nonatomic) int retState; // @synthesize retState;
@property(retain, nonatomic) ListBase *list; // @synthesize list;
@property(retain, nonatomic) SingerCluster *cluster; // @synthesize cluster;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (void)startWork;
- (id)getUrl;
- (BOOL)canReportError;
- (int)cid;

@end

