//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LoginViewController.h"

@class BELoadingView, UIActivityIndicatorView, UIButton;

__attribute__((visibility("hidden")))
@interface QuickLoginViewController : LoginViewController
{
    BOOL _isShowLoading;
    BOOL _isCommonLoginVCTop;
    UIButton *_cancelBtn;
    BELoadingView *_loadingView;
    UIActivityIndicatorView *_loginACView;
    UIButton *_quickLoginBtn;
}

@property(retain, nonatomic) UIButton *quickLoginBtn; // @synthesize quickLoginBtn=_quickLoginBtn;
@property(retain, nonatomic) UIActivityIndicatorView *loginACView; // @synthesize loginACView=_loginACView;
@property(retain, nonatomic) BELoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
- (void).cxx_destruct;
- (void)doneWithLoginFailed;
- (void)doneWithLoginSuccess;
- (void)enbaleUI:(BOOL)arg1;
- (void)onLoginBtnclicked:(id)arg1;
- (void)onQuickLoginBtnClicked:(id)arg1;
- (void)hideLoading;
- (void)doneWithLoadingView;
- (void)setShowLoading:(BOOL)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (void)resetBackgroundView;
- (void)loadView;

@end

