//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SongListBaseViewController.h"

@class BEActivityView, UIView;

__attribute__((visibility("hidden")))
@interface RadioDetailViewController : SongListBaseViewController
{
    int _animatedRow;
    BOOL _renewSongList;
    int _radioId;
    BEActivityView *_refreshActivityView;
    UIView *_formeView;
    id _target;
    SEL _action;
}

@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(retain, nonatomic) UIView *formeView; // @synthesize formeView=_formeView;
@property(retain, nonatomic) BEActivityView *refreshActivityView; // @synthesize refreshActivityView=_refreshActivityView;
@property(nonatomic) int radioId; // @synthesize radioId=_radioId;
- (void).cxx_destruct;
- (void)addActionSheetClickStat:(int)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)_renewRadioSongList;
- (void)_refreshButtonTapped:(id)arg1;
- (void)onColorStyleChanged;
- (BOOL)isShowErrTips;
- (BOOL)isShowNoNetView;
- (BOOL)isHasHeaderView;
- (void)updataDataSuccess:(id)arg1;
- (void)listDataDidUpdate:(id)arg1;
- (void)removeNotification;
- (void)addNewNotification;
- (void)navigateToGuessYouLike;
- (void)addSubviewsToHeaderView:(id)arg1;
- (id)buildTableHeaderView;
- (void)reFresh;
- (int)vcType;
- (void)setTarget:(id)arg1 forAction:(SEL)arg2;
- (void)viewDidLoad;
- (void)loadView;

@end

