//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChannelBaseTabVC.h"

#import "UITableViewDelegate.h"
#import "iCarouselDataSource.h"
#import "iCarouselDelegate.h"

@class ChannelV4Category, ChannelV4CategoryGroup, GroupChannelItem, NSString, SongListItem, UIButton, UITableView, UIView, iCarousel;

__attribute__((visibility("hidden")))
@interface RadioTabVC_V2 : ChannelBaseTabVC <iCarouselDataSource, iCarouselDelegate, UITableViewDelegate>
{
    BOOL _firstLoadCats;
    SongListItem *_playingRadioItem;
    SongListItem *_curLoadingRadioItem;
    ChannelV4Category *_selectedCategory;
    ChannelV4CategoryGroup *_categoryGroup;
    UITableView *_radioIndexTableView;
    GroupChannelItem *_radioItem;
    iCarousel *_carousel;
    float _radioItemWidth;
    UIView *_twoRadioPanel;
    UIButton *_changeTypeBtn;
    struct CGRect _radioIndexFrame;
}

@property(retain, nonatomic) UIButton *changeTypeBtn; // @synthesize changeTypeBtn=_changeTypeBtn;
@property(retain, nonatomic) UIView *twoRadioPanel; // @synthesize twoRadioPanel=_twoRadioPanel;
@property(nonatomic) BOOL firstLoadCats; // @synthesize firstLoadCats=_firstLoadCats;
@property(nonatomic) float radioItemWidth; // @synthesize radioItemWidth=_radioItemWidth;
@property(retain, nonatomic) iCarousel *carousel; // @synthesize carousel=_carousel;
@property(retain, nonatomic) GroupChannelItem *radioItem; // @synthesize radioItem=_radioItem;
@property(nonatomic) struct CGRect radioIndexFrame; // @synthesize radioIndexFrame=_radioIndexFrame;
@property(retain, nonatomic) UITableView *radioIndexTableView; // @synthesize radioIndexTableView=_radioIndexTableView;
@property(retain, nonatomic) ChannelV4CategoryGroup *categoryGroup; // @synthesize categoryGroup=_categoryGroup;
@property(retain, nonatomic) ChannelV4Category *selectedCategory; // @synthesize selectedCategory=_selectedCategory;
@property(retain, nonatomic) SongListItem *curLoadingRadioItem; // @synthesize curLoadingRadioItem=_curLoadingRadioItem;
@property(retain, nonatomic) SongListItem *playingRadioItem; // @synthesize playingRadioItem=_playingRadioItem;
- (void).cxx_destruct;
- (id)carousel:(id)arg1 accessibilityLabelAtIndex:(int)arg2;
- (void)carousel:(id)arg1 didSelectItemAtIndex:(int)arg2;
- (float)carousel:(id)arg1 valueForOption:(int)arg2 withDefault:(float)arg3;
- (struct CATransform3D)carousel:(id)arg1 itemTransformForOffset:(float)arg2 baseTransform:(struct CATransform3D)arg3;
- (float)carousel:(id)arg1 itemAlphaForOffset:(float)arg2;
- (float)carouselItemWidth:(id)arg1;
- (id)carousel:(id)arg1 viewForItemAtIndex:(int)arg2 reusingView:(id)arg3;
- (int)numberOfItemsInCarousel:(id)arg1;
- (void)reloadCellData:(id)arg1 cellData:(id)arg2;
- (void)radioCellClick:(id)arg1;
- (void)resetTowRadioPanel;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onNotifyPlayingSongChange:(id)arg1;
- (void)handleFetchRadioListStatus:(int)arg1 radioProtocol:(id)arg2 workResult:(int)arg3;
- (void)playRadio:(id)arg1;
- (void)requestToShowChannel:(id)arg1;
- (id)createFrom:(int)arg1;
- (id)getCurPlayingRadioItem;
- (id)getCurPlayingList;
- (void)_loginSuccess;
- (void)_listDataDidUpdate:(id)arg1;
- (void)modifyRadioItemCountForBeatiful;
- (void)reFreshWithNetworkDetection;
- (BOOL)isEmptyRadioIndexData;
- (void)radioCategoriesDataDidUpdate:(id)arg1;
- (void)indexTableViewReloadData;
- (void)onColorStyleChanged;
- (void)serverChanged;
- (void)reFreshWithCategory:(id)arg1;
- (void)reFreshRadioIndex;
- (id)emptyViewText;
- (id)emptyViewBgText;
- (id)emptyViewBgImage;
- (void)showEmptyView;
- (void)showNetErrWithResult:(int)arg1;
- (void)showLoadingView;
- (int)vcType;
- (void)willActiveCurrentTab;
- (void)viewDidLoad;
- (void)initCoverFlow;
- (void)initIndexView;
- (id)buildHeaderFooterView:(float)arg1 forHeader:(BOOL)arg2;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

