//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ImageManagerDelegate.h"

@class ChannelItem, NSString, UIActivityIndicatorView, UIImageView, UIImageViewWithUserInfo, UILabel;

__attribute__((visibility("hidden")))
@interface RadioCell : UIView <ImageManagerDelegate>
{
    ChannelItem *_item;
    UIImageView *_defaultImageView;
    UIImageViewWithUserInfo *_imageView;
    UIImageView *_listenIconImageView;
    UILabel *_listenNumLabel;
    UIActivityIndicatorView *_loadingIndiView;
    UIImageView *_nowplayingImgView;
}

@property(retain, nonatomic) UIImageView *nowplayingImgView; // @synthesize nowplayingImgView=_nowplayingImgView;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndiView; // @synthesize loadingIndiView=_loadingIndiView;
@property(retain, nonatomic) UILabel *listenNumLabel; // @synthesize listenNumLabel=_listenNumLabel;
@property(retain, nonatomic) UIImageView *listenIconImageView; // @synthesize listenIconImageView=_listenIconImageView;
@property(retain, nonatomic) UIImageViewWithUserInfo *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImageView *defaultImageView; // @synthesize defaultImageView=_defaultImageView;
@property(retain, nonatomic) ChannelItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (id)imageFileNameForItem:(id)arg1;
- (id)imageUrlForItem:(id)arg1;
- (id)trimImage:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)reloadDataForLoading:(BOOL)arg1 forNowPlaying:(BOOL)arg2;
- (id)defaultImage;
- (void)onNotifyColorStyleChanged:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

