//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ImageManagerDelegate.h"

@class ExpInfo, NSMutableArray, NSString, SongInfo, SongListItem, UIImage, UIImageView, UIView, UIViewController;

__attribute__((visibility("hidden")))
@interface RadioHistoryVC : SkinViewController <ImageManagerDelegate>
{
    UIImageView *albumImageView;
    NSMutableArray *historyPlayingList;
    BOOL isNeedToUpdateView;
    UIView *noHistoryView;
    BOOL _showing;
    UIViewController *_vcFrom;
    SongInfo *_radioSong;
    SongInfo *_curPlayingSong;
    NSMutableArray *historyExpinfoList;
    UIImage *_backBlurImage;
    ExpInfo *_curExpInfo;
    SongListItem *_commonRadioItem;
}

@property(nonatomic) BOOL showing; // @synthesize showing=_showing;
@property(retain, nonatomic) SongListItem *commonRadioItem; // @synthesize commonRadioItem=_commonRadioItem;
@property(retain, nonatomic) ExpInfo *curExpInfo; // @synthesize curExpInfo=_curExpInfo;
@property(retain, nonatomic) UIImage *backBlurImage; // @synthesize backBlurImage=_backBlurImage;
@property(retain, nonatomic) NSMutableArray *historyExpinfoList; // @synthesize historyExpinfoList;
@property(retain, nonatomic) NSMutableArray *historyPlayingList; // @synthesize historyPlayingList;
@property(retain, nonatomic) SongInfo *curPlayingSong; // @synthesize curPlayingSong=_curPlayingSong;
@property(retain, nonatomic) SongInfo *radioSong; // @synthesize radioSong=_radioSong;
@property(retain, nonatomic) UIViewController *vcFrom; // @synthesize vcFrom=_vcFrom;
- (void).cxx_destruct;
- (BOOL)canResponseLongPress;
- (void)animationRecover;
- (void)animationBefore;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setBackGroudImage:(id)arg1;
- (void)updateBackImage:(id)arg1;
- (void)clearBgImage;
- (float)_noHistoryViewTop;
- (void)_playListIndexChanged:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)updateNoHistoryViewFrame;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)formatTime:(double)arg1;
- (id)getExpInfoAtIndexPath:(id)arg1;
- (id)getSongInfoAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSections;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)addCommonRadioInfoView;
- (void)addSingleRadioInfoView;
- (void)createHeaderWithBg:(BOOL)arg1 LeftView:(id)arg2 HeaderText:(BOOL)arg3 RightView:(id)arg4;
- (id)emptyViewText;
- (id)emptyViewBgText;
- (int)headerHight;
- (void)headerFinish:(id)arg1;
- (void)headerCancel:(id)arg1;
- (void)doneAfterDismissMe;
- (void)createHeaderInfoView;
- (id)trimAlbumImage:(id)arg1;
- (void)addBackImageView;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

