//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChannelBaseTabVC.h"

__attribute__((visibility("hidden")))
@interface RankingTabVC : ChannelBaseTabVC
{
    BOOL _isLoading;
}

- (void)_listDataDidUpdate:(id)arg1;
- (void)reFresh;
- (int)vcType;
- (void)willActiveCurrentTab;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;

@end

