//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ListBase.h"

#import "ProtocolHostDelegate.h"

@class ReqSongRecordProtocol;

__attribute__((visibility("hidden")))
@interface ReqSongRecord : ListBase <ProtocolHostDelegate>
{
    BOOL m_bHasAnyMore;
    BOOL m_bForceRefresh;
    ReqSongRecordProtocol *m_reqSongRecordProtocol;
    unsigned long _uin;
    unsigned long lastUpdateTime;
    BOOL m_bLoadingMore;
}

@property(readonly, nonatomic) unsigned long lastUpdateTime; // @synthesize lastUpdateTime;
@property(nonatomic) BOOL m_bLoadingMore; // @synthesize m_bLoadingMore;
@property(nonatomic) BOOL m_bForceRefresh; // @synthesize m_bForceRefresh;
@property(retain, nonatomic) ReqSongRecordProtocol *m_reqSongRecordProtocol; // @synthesize m_reqSongRecordProtocol;
@property(nonatomic) BOOL m_bHasAnyMore; // @synthesize m_bHasAnyMore;
- (void).cxx_destruct;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)logout;
- (BOOL)getMore;
- (BOOL)update:(BOOL)arg1;
- (BOOL)startWorkWithMethod:(int)arg1 bForceRefresh:(BOOL)arg2;
- (void)onActive;
- (void)dealloc;
- (id)initWithUin:(unsigned long)arg1;

@end

