//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolAuthBase.h"

@class ListBase, ReqSongRecordInfo;

__attribute__((visibility("hidden")))
@interface ReqSongRecordDeleteProtocol : ProtocolAuthBase
{
    ListBase *m_listBase;
    ReqSongRecordInfo *m_reqSongRecordInfo;
}

@property(retain, nonatomic) ReqSongRecordInfo *m_reqSongRecordInfo; // @synthesize m_reqSongRecordInfo;
@property(retain, nonatomic) ListBase *m_listBase; // @synthesize m_listBase;
- (void).cxx_destruct;
- (void)onParseXmlData:(struct _xmlDoc *)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (id)init;

@end

