//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, SongInfoKey;

__attribute__((visibility("hidden")))
@interface RetryLogic : NSObject
{
    BOOL _canChangeQuality;
    BOOL _exist320KMp3;
    BOOL _existFLAC;
    BOOL _disableRetryLogic;
    int _eRetryLogicType;
    SongInfoKey *_songInfoKey;
    NSMutableArray *_downloadPropertys;
    int _defaultSongRateType;
    int _fixedSongRateType;
}

+ (int)getDefaultSongRateTypeBySetting:(int)arg1;
@property BOOL disableRetryLogic; // @synthesize disableRetryLogic=_disableRetryLogic;
@property int fixedSongRateType; // @synthesize fixedSongRateType=_fixedSongRateType;
@property int defaultSongRateType; // @synthesize defaultSongRateType=_defaultSongRateType;
@property BOOL existFLAC; // @synthesize existFLAC=_existFLAC;
@property BOOL exist320KMp3; // @synthesize exist320KMp3=_exist320KMp3;
@property BOOL canChangeQuality; // @synthesize canChangeQuality=_canChangeQuality;
@property(retain) NSMutableArray *downloadPropertys; // @synthesize downloadPropertys=_downloadPropertys;
@property(retain) SongInfoKey *songInfoKey; // @synthesize songInfoKey=_songInfoKey;
@property int eRetryLogicType; // @synthesize eRetryLogicType=_eRetryLogicType;
- (void).cxx_destruct;
- (void)disableRetry;
- (void)clearAllRecords;
- (void)canceledLast;
- (BOOL)canRetry;
- (void)setFixedRate:(int)arg1;
- (void)setLastError:(int)arg1;
- (int)getNextQuality;
- (id)getCurrentProperty;
- (unsigned int)getRetryCount;
- (unsigned int)getConnectCount;
- (id)getHistoryHosts;
- (void)addDownloadProperty:(id)arg1;
- (id)initWithRetryType:(int)arg1 songInfoKey:(id)arg2 exist320KMp3:(BOOL)arg3 existFlac:(BOOL)arg4 defaultSongRateType:(int)arg5;

@end

