//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RqdLocalObject.h"

#import "RqdLocalObjInitWithWupProtocol.h"

@class NSDictionary, NSString;

@interface RqdLocalStrategy : RqdLocalObject <RqdLocalObjInitWithWupProtocol>
{
    int zipAlg;
    int encAlg;
    NSString *encKey;
    NSString *encPubKey;
    int uploadStrategy;
    int queryInterval;
    NSString *url;
    _Bool enforceQuery;
    _Bool useServer;
    NSDictionary *moduleStrategys;
}

@property(nonatomic) _Bool useServer; // @synthesize useServer;
@property(nonatomic) _Bool enforceQuery; // @synthesize enforceQuery;
@property(retain, nonatomic) NSString *url; // @synthesize url;
@property(nonatomic) int queryInterval; // @synthesize queryInterval;
@property(nonatomic) int uploadStrategy; // @synthesize uploadStrategy;
@property(retain, nonatomic) NSDictionary *moduleStrategys; // @synthesize moduleStrategys;
@property(retain, nonatomic) NSString *encPubKey; // @synthesize encPubKey;
@property(retain, nonatomic) NSString *encKey; // @synthesize encKey;
@property(nonatomic) int encAlg; // @synthesize encAlg;
@property(nonatomic) int zipAlg; // @synthesize zipAlg;
- (void)dealloc;
- (void)checkSafe;
- (_Bool)isModuleEnabled:(int)arg1;
- (id)getStrategyForKey:(int)arg1;
- (_Bool)addModuleStrategy:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)initLocalObjWithWupBuffer:(JceInputStream_dae2ee3f *)arg1;
- (id)init;

@end

