//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RqdLocalObject.h"

@class NSString;

@interface RqdModuleStrategy : RqdLocalObject
{
    int moduleKey;
    _Bool needDetail;
    NSString *uploadUrl;
}

@property(retain, nonatomic) NSString *uploadUrl; // @synthesize uploadUrl;
@property(nonatomic) int moduleKey; // @synthesize moduleKey;
@property(nonatomic) _Bool needDetail; // @synthesize needDetail;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;

@end

