//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CloudProtocolAction, CloudProtocolSession, CloudProtocolsManager, ProtocolBase;

__attribute__((visibility("hidden")))
@interface SCloudProtocolCallBackParam : NSObject
{
    CloudProtocolsManager *_manager;
    CloudProtocolSession *_session;
    CloudProtocolAction *_action;
    ProtocolBase *_protocol;
    int _workResult;
}

@property int workResult; // @synthesize workResult=_workResult;
@property(retain) ProtocolBase *protocol; // @synthesize protocol=_protocol;
@property(retain) CloudProtocolAction *action; // @synthesize action=_action;
@property(retain) CloudProtocolSession *session; // @synthesize session=_session;
@property(retain) CloudProtocolsManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;

@end

