//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface SDHMIViewController : NSObject
{
    id <MCFeatureController> _featureController;
}

@property(readonly) id <MCFeatureController> featureController; // @synthesize featureController=_featureController;
- (void).cxx_destruct;
- (void)setNavigationDataModelWithId:(int)arg1 latitude:(float)arg2 longitude:(float)arg3 targetName:(id)arg4;
- (void)deregister;
- (void)setListFocus:(unsigned int)arg1 forListId:(unsigned int)arg2 withEvent:(unsigned int)arg3;
- (BOOL)focussedListIndex:(id)arg1;
- (unsigned int)selectedListIndex:(id)arg1;
- (BOOL)isViewFocussed:(id)arg1;
- (void)showWidgets:(id)arg1 visible:(BOOL)arg2;
- (void)setComponent:(unsigned int)arg1 toValid:(BOOL)arg2;
- (void)setTableData:(id)arg1 forListId:(int)arg2 forModelWithId:(int)arg3;
- (void)setText:(id)arg1 forDataModelWithId:(int)arg2;
- (void)setTextModelId:(int)arg1 withTextId:(int)arg2;
- (void)setImage:(id)arg1 forImageModelWithId:(int)arg2;
- (void)setImageModelId:(int)arg1 withPreInstImageId:(int)arg2;
- (void)setImageModelId:(int)arg1 withImageId:(int)arg2;
- (void)setToolbarButtonUnhidden:(int)arg1 imageModelId:(int)arg2 iconId:(int)arg3;
- (void)setToolbarButtonHidden:(int)arg1 imageModelId:(int)arg2 blankIconId:(int)arg3;
- (void)setToolbarButtonVisible:(int)arg1 visible:(BOOL)arg2;
- (void)setToolbarButtonEnabled:(int)arg1 enabled:(BOOL)arg2;
- (void)setToolbarButtonSelectable:(int)arg1 enabled:(BOOL)arg2;
- (void)setWaitingAnimationForWidget:(int)arg1 enabled:(BOOL)arg2;
- (void)setWidget:(int)arg1 visible:(BOOL)arg2;
- (void)setWidget:(int)arg1 enabled:(BOOL)arg2;
- (void)setListItem:(int)arg1 limitedTo3Lines:(BOOL)arg2;
- (void)onHMITimeFormatChanged;
- (void)onHMIDateFormatChanged;
- (void)onHMIDistanceFormatChanged;
- (void)onHMILanguageChanged;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithFeatureController:(id)arg1;

@end

