//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQMusicCell.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface SearchClearHistoryCell : QQMusicCell
{
    UIButton *_delBtn;
}

@property(nonatomic) __weak UIButton *delBtn; // @synthesize delBtn=_delBtn;
- (void).cxx_destruct;
- (void)onNotifySkinSettingChange:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

