//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface ServerRequestLogItem : NSObject
{
    BOOL _allowUploadByCarrier;
    BOOL _canceled;
    NSString *_dateOriginal;
    NSDate *_dateFrom;
    int _retryCount;
    int _seq;
    int _eServerRequestLogType;
    int _eServerRequestLogResult;
    NSString *_log;
    NSString *_crc;
    NSString *_msg;
    unsigned long long _uin;
}

@property(retain) NSString *msg; // @synthesize msg=_msg;
@property(retain) NSString *crc; // @synthesize crc=_crc;
@property(retain) NSString *log; // @synthesize log=_log;
@property int eServerRequestLogResult; // @synthesize eServerRequestLogResult=_eServerRequestLogResult;
@property int eServerRequestLogType; // @synthesize eServerRequestLogType=_eServerRequestLogType;
@property int seq; // @synthesize seq=_seq;
@property BOOL canceled; // @synthesize canceled=_canceled;
@property int retryCount; // @synthesize retryCount=_retryCount;
@property BOOL allowUploadByCarrier; // @synthesize allowUploadByCarrier=_allowUploadByCarrier;
@property(retain) NSDate *dateFrom; // @synthesize dateFrom=_dateFrom;
@property(retain) NSString *dateOriginal; // @synthesize dateOriginal=_dateOriginal;
@property unsigned long long uin; // @synthesize uin=_uin;
- (void).cxx_destruct;

@end

