//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QMWorker.h"

#import "ProtocolHostDelegate.h"

@class ShareObject;

__attribute__((visibility("hidden")))
@interface ShareTimelineEditor : QMWorker <ProtocolHostDelegate>
{
    ShareObject *_editingShareObj;
}

@property(readonly, nonatomic) ShareObject *editingShareObj; // @synthesize editingShareObj=_editingShareObj;
- (void).cxx_destruct;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)deleteShareObj:(id)arg1;

@end

