//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface SingalHttpSubject : NSObject
{
    NSMutableArray *observerList;
    NSMutableDictionary *allHttpDic;
}

+ (void)setSigalHttpSubject:(id)arg1;
+ (id)getIntanceHttpSubject;
@property(readonly, nonatomic) NSMutableDictionary *AllHttpDic; // @synthesize AllHttpDic=allHttpDic;
- (void)dealloc;
- (void)unregisterObserver:(id)arg1;
- (void)registerObserver:(id)arg1;
- (void)onStartMessage:(id)arg1;
- (void)onErrorMessage:(id)arg1;
- (void)onPauseMessage:(id)arg1;
- (void)onReadyMessage:(id)arg1;
- (void)onFinishMessage:(id)arg1;
- (id)init;

@end

