//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController_Detail.h"

#import "ImageManagerDelegate.h"
#import "QMFollowOrCancelViewDelegate.h"
#import "QMPersonalCenterHeaderViewDataSource.h"
#import "QMTabBarDelegate.h"

@class NSArray, NSString, QMPersonalCenterHeaderView, QMTabBar, SingerCluster, UIImage, UIView;

__attribute__((visibility("hidden")))
@interface SingerViewController : SkinViewController_Detail <ImageManagerDelegate, QMTabBarDelegate, QMPersonalCenterHeaderViewDataSource, QMFollowOrCancelViewDelegate>
{
    BOOL _loadingMore;
    UIImage *_imageMVDefault;
    BOOL _isNeedToShowTips;
    int firstPage;
    BOOL _isCancelFollow;
    SingerCluster *_singerCluster;
    id <SingerViewControllerDelegate> _delegate;
    NSArray *_tabTitleNums;
    int _currentTabIndex;
    QMTabBar *_headerTabBar;
    UIView *_topBgView;
    QMPersonalCenterHeaderView *_headerView;
}

@property(retain) QMPersonalCenterHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain) UIView *topBgView; // @synthesize topBgView=_topBgView;
@property(retain) QMTabBar *headerTabBar; // @synthesize headerTabBar=_headerTabBar;
@property(nonatomic) int currentTabIndex; // @synthesize currentTabIndex=_currentTabIndex;
@property(retain, nonatomic) NSArray *tabTitleNums; // @synthesize tabTitleNums=_tabTitleNums;
@property(nonatomic) __weak id <SingerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SingerCluster *singerCluster; // @synthesize singerCluster=_singerCluster;
- (void).cxx_destruct;
- (void)onColorStyleChanged;
- (void)onNotifySingerListenListChange:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (BOOL)showDelBtnInActionSheet:(id)arg1;
- (BOOL)showSingerInfoBtnInActionSheet:(id)arg1;
- (id)_addRedMaskToCell:(id)arg1;
- (BOOL)moreDataIsLoading:(id)arg1;
- (void)processingLoadMoreAction:(id)arg1;
- (BOOL)hasMoreDataInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onList:(id)arg1 ChangeByType:(int)arg2 Index:(int)arg3 Info:(id)arg4;
- (void)onList:(id)arg1 WithResult:(int)arg2 AndAct:(id)arg3;
- (void)onList:(id)arg1 InfoChangeByInfo:(id)arg2 ChangeType:(int)arg3 Index:(unsigned int)arg4;
- (id)selectedImageView:(id)arg1;
- (void)touchUpInside:(id)arg1 itemAtIndex:(unsigned int)arg2;
- (id)selectetdItemImage:(id)arg1 atIndex:(unsigned int)arg2;
- (id)backgroundImage:(id)arg1;
- (id)accessibilityLabel:(id)arg1 atIndex:(unsigned int)arg2;
- (id)imageFor:(id)arg1 atIndex:(unsigned int)arg2;
- (void)_listenOrCancelListenSuccessCallback:(id)arg1;
- (void)updateLoginUserFollowNum:(BOOL)arg1;
- (void)_refreshSingerFunsNum:(BOOL)arg1;
- (void)onFollowOrCancelViewClicked:(id)arg1;
- (void)finishedTips;
- (void)jumpToSingerBuluoWeb;
- (void)jumpToBuyTicketWeb;
- (void)gotoSingerDetailView;
- (id)showCoverImage;
- (id)secondRightButtomView;
- (id)firstRightButtomView;
- (id)firstLeftBottomView;
- (id)secondSubView;
- (id)thirdSubView;
- (id)firstSubView;
- (id)logoFollowingMainTitle;
- (id)mainTitle;
- (id)headerImage:(BOOL)arg1;
- (id)headerImage;
- (void)_onTouchUpInsideSingerCenter:(id)arg1;
- (void)downloadAll;
- (void)onSongsEdit:(id)arg1;
- (void)handleBatchAction:(int)arg1;
- (void)removeTableHeader;
- (void)addTableViewHeader;
- (id)_listKey;
- (void)_blankMethod;
- (void)_hideTabInfoView;
- (void)_showTabInfoViewWithTitle:(id)arg1 subtitle:(id)arg2 tapSelector:(SEL)arg3;
- (void)_hideTabLoadingView;
- (void)_showTabLoadingView;
- (void)_reloadHeaderTabBar;
- (void)_buildHeaderTabBar;
- (void)_reloadOtherData;
- (void)_setTag:(id)arg1;
- (void)_loadFolderList;
- (void)_loadMVList;
- (void)_loadAlbumList;
- (void)_loadSongList;
- (void)onTouchUpInsideMore:(id)arg1;
- (id)singerInfo;
- (void)back:(id)arg1;
- (void)willBack;
- (void)reFresh;
- (void)reachabilityChanged:(id)arg1;
- (void)contentAreaHeightDidChanged:(float)arg1;
- (void)viewDidPop;
- (int)vcType;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

