//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtocolHostDelegate.h"

@class NSArray, NSMutableArray, SingerListenItem, SingerListenQueryProtocol, SingerListenSyncProtocol;

__attribute__((visibility("hidden")))
@interface SingerListenManager : NSObject <ProtocolHostDelegate>
{
    unsigned long _uin;
    SingerListenItem *_backSingerListenItem;
    NSMutableArray *_currentListenList;
    SingerListenQueryProtocol *_singerListenQueryProtocol;
    SingerListenSyncProtocol *_singerListenSyncProtocol;
    NSArray *_currentFollowCreatorList;
}

@property(retain, nonatomic) NSArray *currentFollowCreatorList; // @synthesize currentFollowCreatorList=_currentFollowCreatorList;
@property(retain, nonatomic) SingerListenSyncProtocol *singerListenSyncProtocol; // @synthesize singerListenSyncProtocol=_singerListenSyncProtocol;
@property(retain, nonatomic) SingerListenQueryProtocol *singerListenQueryProtocol; // @synthesize singerListenQueryProtocol=_singerListenQueryProtocol;
@property(retain, nonatomic) NSMutableArray *currentListenList; // @synthesize currentListenList=_currentListenList;
@property(retain, nonatomic) SingerListenItem *backSingerListenItem; // @synthesize backSingerListenItem=_backSingerListenItem;
- (void).cxx_destruct;
- (void)processSingerListenCommand:(id)arg1;
- (void)onLogouted;
- (void)onLogSuccess;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (BOOL)isCreatorFollowed:(id)arg1;
- (BOOL)isSingerListened:(id)arg1;
- (void)deleteListenSinger:(id)arg1 andNextCall:(id)arg2 selector:(SEL)arg3 param:(id)arg4;
- (void)addNewListenSinger:(id)arg1 andNextCall:(id)arg2 selector:(SEL)arg3 param:(id)arg4 refreshTaoge:(BOOL)arg5;
- (void)addNewListenSinger:(id)arg1 andNextCall:(id)arg2 selector:(SEL)arg3 param:(id)arg4;
- (void)checkSyncAndReloadSingerListenList;
- (void)_doneWithSyncSuccess;
- (void)_processLocalListDataWithNewListData:(id)arg1;
- (void)_syncSingerListenList:(id)arg1;
- (void)_reloadSingerListenList;
- (void)_syncTaogeDarenFollowList:(id)arg1 andIsAdd:(BOOL)arg2;
- (BOOL)_tryToSync;
- (id)_getFirstNeedSyncItem;
- (void)_getCurrentListenList;
- (void)_readDataFromFile;
- (void)dealloc;
- (id)initWithUin:(unsigned long)arg1;

@end

