//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface SingleQRCRect : NSObject
{
    int _wordIndex;
    int _lineIndex;
    struct CGRect _rect;
}

@property int lineIndex; // @synthesize lineIndex=_lineIndex;
@property int wordIndex; // @synthesize wordIndex=_wordIndex;
@property struct CGRect rect; // @synthesize rect=_rect;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

