//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SingerListenItem : NSObject <NSCoding, NSCopying>
{
    unsigned long uin;
    NSMutableArray *listenList;
    long long timeTag;
}

+ (void)saveListenSingerlistWithItem:(id)arg1;
+ (id)loadListenSingerListByUin:(unsigned long)arg1;
+ (id)getSingerListenFilePathForUin:(unsigned long)arg1;
+ (id)unarchiveObjectFromFile:(id)arg1;
+ (void)archiveObject:(id)arg1 toFile:(id)arg2;
@property(retain) NSMutableArray *listenList; // @synthesize listenList;
@property unsigned long uin; // @synthesize uin;
@property long long timeTag; // @synthesize timeTag;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

