//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SongInfo, UIViewController;

@protocol SongListSearchVCDelegate

@optional
- (void)didSelectSong:(SongInfo *)arg1 VC:(UIViewController *)arg2;
- (void)didheaderCancel:(id)arg1 VC:(UIViewController *)arg2;
@end

