//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ASIHTTPRequest, NSError, NSString, SingleHourglass, SongInfo;

__attribute__((visibility("hidden")))
@interface SongLengthVerifier : NSObject
{
    ASIHTTPRequest *_request;
    SingleHourglass *_hourglass;
    NSError *_error;
    int _result;
    SongInfo *_song;
    id <SongLengthVerifierDelegate> _delegate;
    NSString *_sVerifyURL;
    double _costTime;
}

@property(readonly, nonatomic) NSString *sVerifyURL; // @synthesize sVerifyURL=_sVerifyURL;
@property(readonly, nonatomic) double costTime; // @synthesize costTime=_costTime;
@property(nonatomic) __weak id <SongLengthVerifierDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) SongInfo *song; // @synthesize song=_song;
@property(nonatomic) int result; // @synthesize result=_result;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) SingleHourglass *hourglass; // @synthesize hourglass=_hourglass;
@property(retain, nonatomic) ASIHTTPRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (void)requestFailed:(id)arg1;
- (void)request:(id)arg1 didReceiveResponseHeaders:(id)arg2;
- (void)readFileAndChechMD5:(id)arg1;
- (void)cancel;
- (void)startVerify;
- (id)initWithSong:(id)arg1;
- (void)dealloc;

@end

