//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ListTagDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSObject, NSString;

__attribute__((visibility("hidden")))
@interface SongSelectVC : SkinViewController <UITableViewDataSource, UITableViewDelegate, ListTagDelegate>
{
    NSObject *key;
    id <SongSelectVCDelegate> delegate;
    int songVCtype;
    BOOL _willAddSongToFolder;
}

@property(nonatomic) BOOL willAddSongToFolder; // @synthesize willAddSongToFolder=_willAddSongToFolder;
@property(nonatomic) int songVCtype; // @synthesize songVCtype;
@property(nonatomic) __weak id <SongSelectVCDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSObject *key; // @synthesize key;
- (void).cxx_destruct;
- (void)onList:(id)arg1 WithResult:(int)arg2 AndAct:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)back:(id)arg1;
- (void)headerCancel:(id)arg1;
- (void)showAddSongTips:(id)arg1;
- (id)loadingViewText;
- (id)emptyViewText;
- (id)emptyViewBgText;
- (id)emptyViewBgImage;
- (void)reFresh;
- (void)dealloc;
- (void)viewDidPop;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

