//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQMusicCell.h"

#import "ImageManagerDelegate.h"

@class NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface SongCell : QQMusicCell <ImageManagerDelegate>
{
    UILabel *songNameLabel;
    UILabel *albumAndSingerNameLabel;
    UIImageView *playingImageview;
    UIImageView *hqImageView;
    BOOL isPlaying;
    BOOL isErr;
    BOOL isHq;
    int version;
    int lang;
    int tag;
    id <SongCellDelegate> cellDelegate;
    UIImageView *m_checkImageView;
    BOOL checked;
    BOOL isSq;
    BOOL isExclusive;
    UIImageView *sqImageView;
    UIImageView *exclusiveImageView;
    UIImageView *mvImageView;
    UIImageView *versionImageView;
}

@property(nonatomic) __weak id <SongCellDelegate> cellDelegate; // @synthesize cellDelegate;
@property(nonatomic) int tag; // @synthesize tag;
@property(nonatomic) int lang; // @synthesize lang;
@property(nonatomic) int version; // @synthesize version;
@property(retain, nonatomic) UIImageView *versionImageView; // @synthesize versionImageView;
@property(retain, nonatomic) UIImageView *mvImageView; // @synthesize mvImageView;
@property(retain, nonatomic) UIImageView *playingImageview; // @synthesize playingImageview;
@property(nonatomic) BOOL checked; // @synthesize checked;
@property(retain, nonatomic) UIImageView *exclusiveImageView; // @synthesize exclusiveImageView;
@property(retain, nonatomic) UIImageView *sqImageView; // @synthesize sqImageView;
@property(retain, nonatomic) UIImageView *hqImageView; // @synthesize hqImageView;
@property(retain, nonatomic) UILabel *albumAndSingerNameLabel; // @synthesize albumAndSingerNameLabel;
@property(retain, nonatomic) UILabel *songNameLabel; // @synthesize songNameLabel;
@property(nonatomic) BOOL isExclusive; // @synthesize isExclusive;
@property(nonatomic) BOOL isSq; // @synthesize isSq;
@property(nonatomic) BOOL isHq; // @synthesize isHq;
@property(nonatomic) BOOL isErr; // @synthesize isErr;
@property(nonatomic) BOOL isPlaying; // @synthesize isPlaying;
- (void).cxx_destruct;
- (void)onNotifySkinSettingChange:(id)arg1;
- (BOOL)showArrow;
- (int)qmCellType;
- (void)handleLongPress:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (id)accessibilityLabel;
- (void)layoutMVHQlogoFrame:(id)arg1;
- (void)setMvLogo:(BOOL)arg1;
- (void)setRankingRow:(int)arg1 rankInfo:(id)arg2 isSpecialType:(BOOL)arg3;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setCheckImageViewCenter:(struct CGPoint)arg1 alpha:(float)arg2 animated:(BOOL)arg3;
- (void)dealloc;
- (void)setCellBackgroundColor;
- (void)addLongPressGesture;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

