//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LibrarySearchVC.h"

#import "ListTagDelegate.h"
#import "SongListSearchResultVCDelegate.h"
#import "SongSelectVCDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ListBase, NSMutableArray, NSString, SongListItem, VoiceInputVC;

__attribute__((visibility("hidden")))
@interface SongListSearchVC : LibrarySearchVC <UITableViewDataSource, UITableViewDelegate, ListTagDelegate, SongSelectVCDelegate, SongListSearchResultVCDelegate>
{
    id <SongListSearchVCDelegate> _delegate;
    BOOL _needShowFav;
    BOOL _willAddSongToFolder;
    VoiceInputVC *_voiceInputVC;
    SongListItem *_songListItem;
    SongListItem *_item;
    NSMutableArray *_arrayAll;
    ListBase *_songList;
}

@property(retain, nonatomic) ListBase *songList; // @synthesize songList=_songList;
@property(retain, nonatomic) NSMutableArray *arrayAll; // @synthesize arrayAll=_arrayAll;
@property(retain, nonatomic) SongListItem *item; // @synthesize item=_item;
@property(retain, nonatomic) SongListItem *songListItem; // @synthesize songListItem=_songListItem;
@property(nonatomic) BOOL willAddSongToFolder; // @synthesize willAddSongToFolder=_willAddSongToFolder;
@property(retain, nonatomic) VoiceInputVC *voiceInputVC; // @synthesize voiceInputVC=_voiceInputVC;
@property(nonatomic) __weak id <SongListSearchVCDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)onNotifyFolderSongDataSaved:(id)arg1;
- (void)onNotifyGetHotSongs:(id)arg1;
- (void)onTouchUpInsideVoiceInput:(id)arg1;
- (void)beginSearch;
- (void)headerCancelAction:(id)arg1;
- (id)listData;
- (BOOL)canAddSongToFolder:(id)arg1;
- (void)headerCancel:(id)arg1;
- (void)didSelectSong:(id)arg1;
- (BOOL)FreshSongsBykey:(id)arg1 andNewSongVC:(id)arg2;
- (id)currentFolders;
- (void)showLoadingView;
- (void)showTable;
- (void)reFresh;
- (id)_getItemKey;
- (id)_hotSongListChannelItem;
- (void)dismissSearchTableView;
- (void)showSearchTableView;
- (void)createCommonHeaderView;
- (void)newTable;
- (id)getBgName;
- (float)getSeperateLineWidth;
- (void)dealloc;
- (void)viewDidPop;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

