//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface SpeedResult : NSObject
{
    BOOL _shouldRetry;
    NSString *_host;
    unsigned int _speed;
    NSDate *_testDate;
    int _retryCount;
    int _downTime;
    NSDate *_bindedUntilDate;
    int _errorCode;
}

@property(nonatomic) int errorCode; // @synthesize errorCode=_errorCode;
@property(retain, nonatomic) NSDate *bindedUntilDate; // @synthesize bindedUntilDate=_bindedUntilDate;
@property(nonatomic) int downTime; // @synthesize downTime=_downTime;
@property(nonatomic) int retryCount; // @synthesize retryCount=_retryCount;
@property(nonatomic) BOOL shouldRetry; // @synthesize shouldRetry=_shouldRetry;
@property(retain, nonatomic) NSDate *testDate; // @synthesize testDate=_testDate;
@property(nonatomic) unsigned int speed; // @synthesize speed=_speed;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;

@end

