//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QStreamAudioPlayerBase.h"

@class NSCondition, NSMutableArray, NSMutableData, NSThread;

__attribute__((visibility("hidden")))
@interface StreamMusicPlayerThread : QStreamAudioPlayerBase
{
    struct CMutex _audioQueueLock;
    struct OpaqueAudioQueue *_audioQueue;
    struct CStreamMusicBuffer *_audioQueueBuffer[4];
    unsigned int _currentAudioQueueBufferIndex;
    unsigned long _maxAudioQueueBufferSize;
    struct CMutex _getBuffersLeftCountLock;
    NSMutableArray *_parserData;
    NSMutableData *_currentData;
    struct CMutex _getSetActionLock;
    NSMutableArray *_actionArray;
    NSThread *_mainThread;
    double _seekTime;
    double _seekByte;
    BOOL _isSeeking;
    void *_pEffectHandle;
    BOOL _bEnableEffect;
    NSMutableData *writer1;
    NSMutableData *writer2;
    BOOL _isThreadStop;
    BOOL _isStartPlayed;
    int _audioBuffersLeftCount;
    int _nEffectType;
    int _nEffectParam;
    NSCondition *_decodeCondition;
}

@property(nonatomic) BOOL isStartPlayed; // @synthesize isStartPlayed=_isStartPlayed;
@property(retain, nonatomic) NSCondition *decodeCondition; // @synthesize decodeCondition=_decodeCondition;
@property int nEffectParam; // @synthesize nEffectParam=_nEffectParam;
@property int nEffectType; // @synthesize nEffectType=_nEffectType;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)decodeRun;
- (BOOL)startThread;
- (void)cancelThread;
- (void)handlePropertyChangeForQueue:(struct OpaqueAudioQueue *)arg1 propertyID:(unsigned long)arg2;
- (void)handleBufferCompleteForQueue:(struct OpaqueAudioQueue *)arg1 buffer:(struct AudioQueueBuffer *)arg2;
- (void)enqueueBuffer;
- (void)tryToStart;
- (BOOL)isBuffering;
- (void)createAudioQueue:(id)arg1 withInputDesc:(id)arg2;
- (void)createAudioFileStreamByCurrentData;
- (void)stopAudioQueue;
- (void)resumeAudioQueue;
- (void)pauseAudioQueue;
- (void)pauseAudioQueueDelay;
- (long)fadePauseAudioQueue;
- (long)fadeStartAudioQueue;
- (void)fadeAudioQueueWithDuration:(double)arg1;
- (short *)addAudioEffect:(id)arg1;
- (void)releaseAudioEffect;
- (BOOL)initAudioEffect;
- (void)threadSetEffect;
- (void)handleAudioStreamRead;
- (void)handleAudioStreamPacketDesctiption:(id)arg1 PacketData:(id)arg2;
- (void)handleAudioStreamDesc:(id)arg1 withInputDesc:(id)arg2;
- (void)clearData;
- (void)threadClear;
- (void)threadStop:(BOOL)arg1 finish:(BOOL)arg2;
- (void)threadSeek:(double)arg1;
- (void)threadResume;
- (void)threadPause;
- (void)threadPlay;
- (void)threadPrepare;
- (id)init;
- (void)AudioBuffersLeftCountDel;
- (void)AudioBuffersLeftCountAdd;
@property(nonatomic) int audioBuffersLeftCount; // @synthesize audioBuffersLeftCount=_audioBuffersLeftCount;
@property BOOL isThreadStop; // @synthesize isThreadStop=_isThreadStop;

@end

