//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SubscribeListItem : NSObject <NSCoding, NSCopying>
{
    unsigned long _uin;
    NSMutableArray *_channels;
    long long _timeTag;
}

@property(retain) NSMutableArray *channels; // @synthesize channels=_channels;
@property unsigned long uin; // @synthesize uin=_uin;
@property long long timeTag; // @synthesize timeTag=_timeTag;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;

@end

