//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SVFloorBarItem : NSObject
{
    unsigned int _id;
    NSString *_name;
    NSString *_short_name;
    NSString *_svid;
}

@property(retain, nonatomic) NSString *svid; // @synthesize svid=_svid;
@property(retain, nonatomic) NSString *short_name; // @synthesize short_name=_short_name;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned int id; // @synthesize id=_id;
- (void)dealloc;
- (BOOL)isEqual:(struct FloorInfo *)arg1;
- (id)initWithFloorInfo:(struct FloorInfo *)arg1;

@end

