//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FMCProxyListener.h"

@class FMCSyncProxy, NSMutableData;

__attribute__((visibility("hidden")))
@interface SyncBrain : NSObject <FMCProxyListener>
{
    int autoIncCorrID;
    int cmdID;
    BOOL firstTimeStartUp;
    NSMutableData *audioPassThruData;
    BOOL _bFristActived;
    FMCSyncProxy *proxy;
}

+ (id)getInstance;
@property(nonatomic) BOOL bFristActived; // @synthesize bFristActived=_bFristActived;
@property(nonatomic) int autoIncCorrID; // @synthesize autoIncCorrID;
@property(retain, nonatomic) FMCSyncProxy *proxy; // @synthesize proxy;
- (void).cxx_destruct;
- (void)onUnsubscribeVehicleDataResponse:(id)arg1;
- (void)onUnsubscribeButtonResponse:(id)arg1;
- (void)onUnregisterAppInterfaceResponse:(id)arg1;
- (void)onSubscribeVehicleDataResponse:(id)arg1;
- (void)onSubscribeButtonResponse:(id)arg1;
- (void)onSpeakResponse:(id)arg1;
- (void)onSliderResponse:(id)arg1;
- (void)onShowResponse:(id)arg1;
- (void)onSetMediaClockTimerResponse:(id)arg1;
- (void)onSetGlobalPropertiesResponse:(id)arg1;
- (void)onSetDisplayLayoutResponse:(id)arg1;
- (void)onSetAppIconResponse:(id)arg1;
- (void)onScrollableMessageResponse:(id)arg1;
- (void)onResetGlobalPropertiesResponse:(id)arg1;
- (void)onRegisterAppInterfaceResponse:(id)arg1;
- (void)onReadDIDResponse:(id)arg1;
- (void)onPutFileResponse:(id)arg1;
- (void)onPerformInteractionResponse:(id)arg1;
- (void)onOnVehicleData:(id)arg1;
- (void)onOnPermissionsChange:(id)arg1;
- (void)onOnLanguageChange:(id)arg1;
- (void)onOnCommand:(id)arg1;
- (void)onOnButtonPress:(id)arg1;
- (void)onOnButtonEvent:(id)arg1;
- (void)onPerformAudioPassThruResponse:(id)arg1;
- (void)onOnAudioPassThru:(id)arg1;
- (void)onOnAppInterfaceUnregistered:(id)arg1;
- (void)onListFilesResponse:(id)arg1;
- (void)onGetVehicleDataResponse:(id)arg1;
- (void)onGetDTCsResponse:(id)arg1;
- (void)onGenericResponse:(id)arg1;
- (void)onError:(id)arg1;
- (void)onEndAudioPassThruResponse:(id)arg1;
- (void)onDeleteSubMenuResponse:(id)arg1;
- (void)onDeleteInteractionChoiceSetResponse:(id)arg1;
- (void)onDeleteFileResponse:(id)arg1;
- (void)onDeleteCommandResponse:(id)arg1;
- (void)onCreateInteractionChoiceSetResponse:(id)arg1;
- (void)onChangeRegistrationResponse:(id)arg1;
- (void)onAlertResponse:(id)arg1;
- (void)onAddSubMenuResponse:(id)arg1;
- (void)onAddCommandResponse:(id)arg1;
- (void)onOnDriverDistraction:(id)arg1;
- (void)tearDownProxy;
- (void)onOnHMIStatus:(id)arg1;
- (void)onProxyClosed;
- (void)onProxyOpened;
- (void)disposeProxy;
- (void)cycleProxy;
- (void)setupProxy;
- (void)initialShow;
- (void)savePreferences;
- (void)subscribeButtonPressed:(id)arg1;
- (void)changeRegistrationPressedWithLanguage:(id)arg1 WithHmiDisplayLanguage:(id)arg2;
- (void)sliderPressedWithNumTicks:(id)arg1 position:(id)arg2 sliderHeader:(id)arg3 sliderFooter:(id)arg4 timeOut:(id)arg5;
- (void)scrollableMessagePressedWithScrollableMessageBody:(id)arg1 timeOut:(id)arg2 softButtons:(id)arg3;
- (void)getVehicleDataPressedWithGps:(id)arg1 speed:(id)arg2 rpm:(id)arg3 fuelLevel:(id)arg4 fuelLevelState:(id)arg5 instantFuelConsumption:(id)arg6 externalTemperature:(id)arg7 vin:(id)arg8 prndl:(id)arg9 tirePressure:(id)arg10 odometer:(id)arg11 beltStatus:(id)arg12 bodyInformation:(id)arg13 deviceStatus:(id)arg14 driverBraking:(id)arg15 wiperStatus:(id)arg16 headLampStatus:(id)arg17 engineTorque:(id)arg18 accPedalPosition:(id)arg19 steeringWheelAngle:(id)arg20;
- (void)unSubscribeVehicleDataPressedWithGps:(id)arg1 speed:(id)arg2 rpm:(id)arg3 fuelLevel:(id)arg4 fuelLevelState:(id)arg5 instantFuelConsumption:(id)arg6 externalTemperature:(id)arg7 prndl:(id)arg8 tirePressure:(id)arg9 odometer:(id)arg10 beltStatus:(id)arg11 bodyInformation:(id)arg12 deviceStatus:(id)arg13 driverBraking:(id)arg14 wiperStatus:(id)arg15 headLampStatus:(id)arg16 engineTorque:(id)arg17 accPedalPosition:(id)arg18 steeringWheelAngle:(id)arg19;
- (void)subscribeVehicleDataPressedWithGps:(id)arg1 speed:(id)arg2 rpm:(id)arg3 fuelLevel:(id)arg4 fuelLevelState:(id)arg5 instantFuelConsumption:(id)arg6 externalTemperature:(id)arg7 prndl:(id)arg8 tirePressure:(id)arg9 odometer:(id)arg10 beltStatus:(id)arg11 bodyInformation:(id)arg12 deviceStatus:(id)arg13 driverBraking:(id)arg14 wiperStatus:(id)arg15 headLampStatus:(id)arg16 engineTorque:(id)arg17 accPedalPosition:(id)arg18 steeringWheelAngle:(id)arg19;
- (void)endAudioPassThruPressed;
- (void)performAudioPassThruPressedWithInitialPrompt:(id)arg1 disPlayText1:(id)arg2 disPlayText2:(id)arg3 samplingRate:(id)arg4 maxDuration:(id)arg5 bitsPerSample:(id)arg6 audioType:(id)arg7 muteAudio:(id)arg8;
- (int)getCmdID;
- (void)incCmdID;
- (void)postToConsoleLog:(id)arg1;
- (id)getNextCorrID;
- (void)sendAndPostRPCMessage:(id)arg1;

@end

