//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBase.h"

#import "ProtocolHostDelegate.h"

@class FolderInfo, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface SyncFolderProtocol : ProtocolBase <ProtocolHostDelegate>
{
    id <SyncFolderProtocolDelegate> _delegate;
    FolderInfo *_folderInfoCurrent;
    int iLastSyncFolderId;
    int iLastFolderSeq;
    int _folderSynType;
    unsigned long _iQQUin;
    BOOL bSuccess;
    unsigned long _uin;
    NSMutableArray *_retFolders;
    NSString *_folderIcoURL;
    NSString *_folderIcoLocalPath;
    NSString *_folderIcoOriginalURL;
}

@property(retain, nonatomic) NSString *folderIcoOriginalURL; // @synthesize folderIcoOriginalURL=_folderIcoOriginalURL;
@property(retain, nonatomic) NSString *folderIcoLocalPath; // @synthesize folderIcoLocalPath=_folderIcoLocalPath;
@property(retain, nonatomic) NSString *folderIcoURL; // @synthesize folderIcoURL=_folderIcoURL;
@property(retain, nonatomic) NSMutableArray *retFolders; // @synthesize retFolders=_retFolders;
@property(retain, nonatomic) FolderInfo *folderInfoCurrent; // @synthesize folderInfoCurrent=_folderInfoCurrent;
- (void).cxx_destruct;
- (void)removeChannelDataCache:(id)arg1;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (void)dealloc;
- (void)processFolder:(id)arg1;
- (void)onParseXmlData:(struct _xmlDoc *)arg1;
- (BOOL)parseData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (void)startWork;
- (void)syncToCloud;
- (BOOL)performSyncAfter;
- (BOOL)needSyncFolderIcoURL:(id)arg1;
- (id)getFirstAppropriateFolderInfo;
- (id)getUrl;
- (int)cid;
- (id)initWithDelegate:(id)arg1 uin:(unsigned long)arg2;

@end

