//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SyncWithCloud;

@protocol SyncWithCloudProtocol
- (void)onSyncWithCloudDone:(SyncWithCloud *)arg1 workResult:(int)arg2;
@end

