//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaseTabVC, NSObject, NSString, SongListItem, UIScrollView;

@protocol TabScrollDelegate <NSObject>
- (void)cancleLoveFolder;
- (void)onSongDeleteFromFolder:(NSObject *)arg1;
- (void)onNavTitleEditFinishWithSongListItem:(SongListItem *)arg1;
- (void)updateHeaderTabNum:(int)arg1 atIndex:(int)arg2;
- (void)hideNetErrView;
- (void)hideAll;
- (void)showNoNetViewWithInfo1:(NSString *)arg1 andInfo2:(NSString *)arg2 iconName:(NSString *)arg3;
- (void)hideLoadingView;
- (void)showLoadingView;
- (void)hideTabInfoView;
- (void)showTabInfoViewWithTitle:(NSString *)arg1 subtitle:(NSString *)arg2 tapSelector:(SEL)arg3;
- (void)hideTabLoadingView:(BaseTabVC *)arg1;
- (void)showTabLoadingView:(BaseTabVC *)arg1;
- (void)updateLoveBtnState;
- (void)onSongListItemLoaded:(SongListItem *)arg1;
- (float)getHeaderTabBarY;
- (float)getClearViewHeight;
- (void)tabDidscroll:(UIScrollView *)arg1 toPoint:(struct CGPoint)arg2;
@end

