//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QLAdThumbViewDelegate.h"
#import "TADEventCenter.h"

@class NSString;

@interface TADBaseManager : NSObject <TADEventCenter, QLAdThumbViewDelegate>
{
    NSString *_channelId;
    id _delegate;
}

@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
- (void)adLandingViewDidAppear:(id)arg1;
- (void)adThumbViewClicked:(id)arg1;
- (void)onEvent:(int)arg1 userInfo:(id)arg2;
- (void)dealloc;
- (id)initWithChannelId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

