//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TADHttpRequestDelegate.h"

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface TADManager : NSObject <TADHttpRequestDelegate>
{
    NSMutableArray *_requestList;
    NSMutableDictionary *_updateRecordMap;
    NSMutableArray *_needUpdateChannels;
    NSArray *_channels;
}

+ (void)purgeSharedInstance;
+ (id)sharedInstance;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(retain, nonatomic) NSMutableArray *needUpdateChannels; // @synthesize needUpdateChannels=_needUpdateChannels;
@property(retain, nonatomic) NSMutableDictionary *updateRecordMap; // @synthesize updateRecordMap=_updateRecordMap;
@property(retain, nonatomic) NSMutableArray *requestList; // @synthesize requestList=_requestList;
- (void).cxx_destruct;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (int)adIntervalForTag:(id)arg1;
- (id)p_requestTagWithChannel:(id)arg1 ForAdType:(id)arg2;
- (BOOL)p_shouldUpdateFromNetForTag:(id)arg1;
- (void)p_LoadAdforSplash;
- (void)p_LoadAdforChannels:(id)arg1;
- (void)p_LoadAdforChannel:(id)arg1 flags:(id)arg2;
- (id)adTypeStreamForChannel:(id)arg1;
- (void)preloadAdforSplash;
- (id)adItemForSplash;
- (id)adItemForChannel:(id)arg1 withType:(id)arg2 flags:(int)arg3;
- (id)adItemForChannel:(id)arg1 withType:(id)arg2;
- (id)adForChannel:(id)arg1 withType:(id)arg2;
- (void)preLoadStreamAdForChannels:(id)arg1;
- (void)preLoadAdforChannel:(id)arg1;
- (void)loadAdforChannelInfo:(id)arg1;
- (void)appDidDidBecomeActiveNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

