//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TADReportVideoCacheHitItem : NSObject
{
    BOOL _isHit;
    NSString *_vid;
    NSString *_definition;
}

@property(nonatomic) BOOL isHit; // @synthesize isHit=_isHit;
@property(retain, nonatomic) NSString *definition; // @synthesize definition=_definition;
@property(retain, nonatomic) NSString *vid; // @synthesize vid=_vid;
- (void).cxx_destruct;

@end

