//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UILabel;

@interface TADRemainView : UIView <UIGestureRecognizerDelegate>
{
    BOOL _skippable;
    id <TADRemainViewDelegate> _delegate;
    int _style;
    float _fitWidth;
    float _fitHeight;
    UILabel *_timeLabel;
    UILabel *_skipLabel;
}

@property(nonatomic) UILabel *skipLabel; // @synthesize skipLabel=_skipLabel;
@property(nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) float fitHeight; // @synthesize fitHeight=_fitHeight;
@property(nonatomic) float fitWidth; // @synthesize fitWidth=_fitWidth;
@property(nonatomic) int style; // @synthesize style=_style;
@property(nonatomic) BOOL skippable; // @synthesize skippable=_skippable;
@property(nonatomic) id <TADRemainViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)insetsLabelWithText:(id)arg1 andTextColor:(id)arg2 fitSystemFontOfSize:(float)arg3 bold:(BOOL)arg4;
- (void)setInitialRemainTimeOfSecond:(unsigned int)arg1;
- (void)setRemainTimeOfSecond:(unsigned int)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleSkipLabelTouch:(id)arg1;
- (void)changeToStyle:(int)arg1;
- (void)arrangeTextLabels:(int)arg1;
- (void)setupTextLabels;
- (void)setupBottomView;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2 skippable:(BOOL)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithStyle:(int)arg1 skippable:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

