//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TodayKey : NSObject
{
    int _eTodayItemType;
    long long _targetId;
}

@property long long targetId; // @synthesize targetId=_targetId;
@property int eTodayItemType; // @synthesize eTodayItemType=_eTodayItemType;
- (id)description;
- (id)key;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

