//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TodayHelper : NSObject
{
}

+ (BOOL)_todayValided;
+ (void)releaseInstance;
+ (id)sharedInstance;
- (id)_stringByMd5:(id)arg1;
- (id)_rootPath;
- (id)filePathByFileURL:(id)arg1;
- (id)imagePathByURL:(id)arg1;
- (id)_imageRootPath;
- (id)sharedUserDefault;
- (id)groupName;
- (id)object2Data:(id)arg1;
- (id)data2object:(id)arg1;
- (id)loadAllTodayItems;
- (void)testByContainer;
- (void)_updateiOS8TodayConfigure;
- (void)delayUpdateiOS8TodayConfigure;
- (void)createWidgetUpdateEvent;
- (void)_onTimerUpdateWidget:(id)arg1;
- (BOOL)needFetchNewData;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (long long)_tidFromMusicListInfoProtocol:(id)arg1 Result:(int)arg2;
- (void)_fetchSongListByChannelItemType:(int)arg1 channelItemId:(long long)arg2 userInfo:(id)arg3;
- (void)_fetchSongListTidsByCategory:(long long)arg1 userInfo:(id)arg2;
- (void)asyncFetchSongList:(long long)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (id)_removeListenedTidsFrom:(id)arg1 listenedTids:(id)arg2;
- (BOOL)fetchSongList:(long long)arg1 toResult:(id)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (id)_downloadedListbase;
- (id)_iPodFolderSongs;
- (id)_recentPlayFolderSongs;
- (void)startDownloadImages;
- (id)_randomObjectInArray:(id)arg1;
- (id)_randomTodayKeyInTodayKeys:(id)arg1 listenedTodayKeys:(id)arg2;
- (id)_arrayByRemoveExpiredListenedTodayKeys:(id)arg1;
- (id)_arrayByRemoveExpiredListenedSongListTids:(id)arg1;
- (void)_saveRootObject:(id)arg1 toKey:(id)arg2;
- (void)addNewListenedTodayKey:(id)arg1;
- (void)_addNewListenedSongListTid:(long long)arg1;
- (void)_saveAllTodayItems:(id)arg1 category2SongListId:(id)arg2;
- (void)saveAllTodayItemsExcludeToday:(id)arg1 category2SongListId:(id)arg2;
- (id)_allCategoryIdInTodayItems:(id)arg1;
- (id)_seprateTodayItemsToTodayAndLater:(id)arg1;
- (long long)startTimeOfToday;
- (id)todayKeyById:(long long)arg1;
- (id)_loadAllCategoryId2SongListIds;
- (id)_loadAllListenedSongListTids;
- (id)_loadAllListenedTodayKeys;
- (id)_findTodayItemIn:(id)arg1 todayId:(long long)arg2;

@end

