//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComRootCell.h"

#import "ImageManagerDelegate.h"

@class NSString, QMLabel, SongListItem, UIButton, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TopicChannelCell : ComRootCell <ImageManagerDelegate>
{
    BOOL _useMVPlayButton;
    id <TopicChannelCellDelegate> _delegate;
    SongListItem *_songListItem;
    QMLabel *_introductionLabel;
    UIView *_bottomView;
    UIImageView *_headsetIcon;
    UILabel *_listenersLabel;
    UIButton *_playBtn;
    UIImageView *_separateLine;
    UILabel *_dateLabel;
    UIImageView *_clockIcon;
    UIImageView *_defaultBgImage;
}

@property(nonatomic) BOOL useMVPlayButton; // @synthesize useMVPlayButton=_useMVPlayButton;
@property(retain, nonatomic) UIImageView *defaultBgImage; // @synthesize defaultBgImage=_defaultBgImage;
@property(retain, nonatomic) UIImageView *clockIcon; // @synthesize clockIcon=_clockIcon;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UIImageView *separateLine; // @synthesize separateLine=_separateLine;
@property(retain, nonatomic) UIButton *playBtn; // @synthesize playBtn=_playBtn;
@property(retain, nonatomic) UILabel *listenersLabel; // @synthesize listenersLabel=_listenersLabel;
@property(retain, nonatomic) UIImageView *headsetIcon; // @synthesize headsetIcon=_headsetIcon;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) QMLabel *introductionLabel; // @synthesize introductionLabel=_introductionLabel;
@property(retain, nonatomic) SongListItem *songListItem; // @synthesize songListItem=_songListItem;
@property(nonatomic) __weak id <TopicChannelCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)setIsLastRow:(BOOL)arg1;
- (void)playBtnTapped:(id)arg1;
- (id)reuseIdentifier;
- (void)onNotifyColorStyleChanged:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

