//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError, NSString, TVKMediaPlayer;

@protocol TVKMediaPlaybackDelegate <NSObject>

@optional
- (void)mediaPlayer:(TVKMediaPlayer *)arg1 progressUpdated:(double)arg2 duration:(double)arg3;
- (void)mediaPlayer:(TVKMediaPlayer *)arg1 eventOccur:(int)arg2 userInfo:(NSDictionary *)arg3;
- (void)mediaPlayer:(TVKMediaPlayer *)arg1 screenChanged:(BOOL)arg2;
- (void)mediaPlayer:(TVKMediaPlayer *)arg1 stateChanged:(int)arg2 withError:(NSError *)arg3;
- (NSString *)mediaPlayer:(TVKMediaPlayer *)arg1 willPlayUrl:(NSString *)arg2;
@end

