//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProtocolHostDelegate.h"

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface TVRecognize : NSObject <ProtocolHostDelegate>
{
    id m_deletegate;
    NSString *m_mode;
    NSString *m_version;
    float m_thresthold;
    int m_start;
    NSMutableDictionary *m_requests;
    int m_recogid;
}

+ (double)getFirstTime;
- (void).cxx_destruct;
- (void)setThresthold:(float)arg1;
- (void)hostCallBackWithWorkProtocol:(id)arg1 Result:(int)arg2;
- (BOOL)processData:(id)arg1;
- (id)makeTime;
- (BOOL)recognizeAsync:(int)arg1;
- (BOOL)recognizeReset;
- (void)recognizeFinished:(id)arg1;
- (void)setMode:(id)arg1;
- (void)dealloc;
- (id)initWithDeletegate:(id)arg1;

@end

