//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GameProductModel, NSString, UIImage;

@protocol UIGameCoinPromotionViewDatasource <NSObject>
- (GameProductModel *)gameProductModelAtIndex:(unsigned int)arg1;
- (UIImage *)gameCoinIcon;
- (NSString *)produceName;
- (unsigned int)productCount;

@optional
- (NSString *)promotionMessege;
@end

