//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (WebP)
+ (id)webpImageWithData:(id)arg1;
+ (id)imageFromWebP:(id)arg1;
+ (BOOL)isWebPImage:(id)arg1;
+ (id)imageNamedWebP:(id)arg1;
@end

