//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (ColorStyle)
- (id)applyCurrentColorStyle;
- (id)applyColorStyle:(struct SColorStyle)arg1 name:(id)arg2;
- (id)_applyColorStyle:(struct SColorStyle)arg1 name:(id)arg2;
- (void)calcComponentOffset:(int *)arg1 componentCount:(int)arg2 ofBitmapInfo:(unsigned int)arg3;
@end

