//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIGameCoinPromotionItemView, UIListView;

@protocol UIListViewDataSource <NSObject>
- (unsigned int)cellCountOfListView:(UIListView *)arg1;
- (UIGameCoinPromotionItemView *)listView:(UIListView *)arg1 cellAtIndex:(unsigned int)arg2;
- (float)seperatorMarginWidthOfListView:(UIListView *)arg1;
@end

