//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QMLabel, UIImageView;

__attribute__((visibility("hidden")))
@interface UINumberView : UIView
{
    QMLabel *_labelNumber;
    UIImageView *_rightImage;
}

- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (void)setNumber:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

