//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface UIPayHeaderView : UIView
{
    int _orientation;
    NSString *_title;
    float _msgLbHeightPortrait;
    id <UIPayHeaderViewDelegate> _delegate;
}

@property(nonatomic) id <UIPayHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onRightBtnTapped:(id)arg1;
- (void)onLeftBtnTapped:(id)arg1;
- (void)layoutSubviews;
- (void)initAllSubviews;
- (void)setShowRightImgBtn:(id)arg1;
- (void)setShowLeftImgBtn:(id)arg1;
- (void)setHeaderPromotionMessage:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 orientation:(int)arg2;

@end

