//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class UpgradeInfo;

__attribute__((visibility("hidden")))
@interface UnifiedUpgradeProtocol : ProtocolBaseJason
{
    UpgradeInfo *_upgradeInfo;
}

@property(retain, nonatomic) UpgradeInfo *upgradeInfo; // @synthesize upgradeInfo=_upgradeInfo;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (BOOL)canReportError;
- (id)getUrl;
- (int)cid;

@end

