//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBase.h"

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface UpdateFolderProtocol : ProtocolBase
{
    NSMutableArray *optionArray;
    NSMutableArray *ordersArray;
    unsigned long _uin;
    NSArray *_folders;
}

@property(retain, nonatomic) NSArray *folders; // @synthesize folders=_folders;
@property(nonatomic) unsigned long uin; // @synthesize uin=_uin;
@property(readonly, nonatomic) NSMutableArray *ordersArray; // @synthesize ordersArray;
@property(readonly, nonatomic) NSMutableArray *optionArray; // @synthesize optionArray;
- (void).cxx_destruct;
- (id)translateFolderFromNode:(struct _xmlNode *)arg1;
- (void)onParseXmlData:(struct _xmlDoc *)arg1;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (BOOL)canReportError;
- (id)getUrl;
- (id)getFolderList;
- (void)startWork;
- (id)getUser;
- (id)initWithUin:(unsigned long)arg1;

@end

