//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QPlaySpeaker.h"

@class NSDate, NSObject<OS_dispatch_queue>;

__attribute__((visibility("hidden")))
@interface UPnPSpeaker : QPlaySpeaker
{
    int _eqObserverCount;
    NSObject<OS_dispatch_queue> *_renderingControlQueue;
}

@property(readonly, nonatomic) __weak NSObject<OS_dispatch_queue> *renderingControlQueue; // @synthesize renderingControlQueue=_renderingControlQueue;
@property(nonatomic) int eqObserverCount; // @synthesize eqObserverCount=_eqObserverCount;
- (void).cxx_destruct;
- (id)getAllNeededServices;
- (BOOL)supportQPlay;
- (id)description;
- (void)setLogo:(id)arg1;
- (void)dealloc;
- (void)setNameWithControlPoint:(id)arg1 controlPoint:(id)arg2;
- (id)initWithIdentifer:(id)arg1 controlPoint:(id)arg2;

// Remaining properties
@property(nonatomic) CDStruct_1b6d18a9 positionSnapshot;
@property(copy, nonatomic) NSDate *positionSnapshotTimeStamp;

@end

