//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CloudFolder, CloudFolderEdit, CloudFolderHistory, CloudFolderStat, CloudProtocolsManager, DownloadHistoryUploader, FolderIcoUploaderManager, KSongNewInfo, LoginOutControl, PersistentConnection, QQUser, ReceiveSongProtocol, ReqSongRecord, SingerListenManager, UserSessionTimers;

__attribute__((visibility("hidden")))
@interface UserSession : NSObject
{
    unsigned long long _uin;
    CloudFolder *_cloudFolder;
    CloudProtocolsManager *_cloudProtocolsManager;
    QQUser *_qqUser;
    LoginOutControl *_loginOutControl;
    PersistentConnection *_persistentConnection;
    UserSessionTimers *_userSessionTimers;
    CloudFolderEdit *_cloudFolderEdit;
    DownloadHistoryUploader *_downloadHistoryUploader;
    CloudFolderStat *_cloudFolderStat;
    ReqSongRecord *_reqSongRecord;
    ReceiveSongProtocol *_receiveSongProtocol;
    SingerListenManager *_singerListenManager;
    CloudFolderHistory *_cloudFolderHistory;
    unsigned int _iApprovedCount;
    FolderIcoUploaderManager *_folderIcoUploaderManager;
    KSongNewInfo *_ksongNewInfo;
}

+ (void)loadUserSession;
@property(readonly) KSongNewInfo *ksongNewInfo; // @synthesize ksongNewInfo=_ksongNewInfo;
@property(readonly) FolderIcoUploaderManager *folderIcoUploaderManager; // @synthesize folderIcoUploaderManager=_folderIcoUploaderManager;
@property(readonly) unsigned int iApprovedCount; // @synthesize iApprovedCount=_iApprovedCount;
@property(readonly) CloudFolderHistory *cloudFolderHistory; // @synthesize cloudFolderHistory=_cloudFolderHistory;
@property(readonly) SingerListenManager *singerListenManager; // @synthesize singerListenManager=_singerListenManager;
@property(readonly) ReceiveSongProtocol *receiveSongProtocol; // @synthesize receiveSongProtocol=_receiveSongProtocol;
@property(readonly) ReqSongRecord *reqSongRecord; // @synthesize reqSongRecord=_reqSongRecord;
@property(readonly) CloudFolderStat *cloudFolderStat; // @synthesize cloudFolderStat=_cloudFolderStat;
@property(readonly) DownloadHistoryUploader *downloadHistoryUploader; // @synthesize downloadHistoryUploader=_downloadHistoryUploader;
@property(readonly) CloudFolderEdit *cloudFolderEdit; // @synthesize cloudFolderEdit=_cloudFolderEdit;
@property(readonly) UserSessionTimers *userSessionTimers; // @synthesize userSessionTimers=_userSessionTimers;
@property(readonly) PersistentConnection *persistentConnection; // @synthesize persistentConnection=_persistentConnection;
@property(readonly) LoginOutControl *loginOutControl; // @synthesize loginOutControl=_loginOutControl;
@property(readonly) QQUser *qqUser; // @synthesize qqUser=_qqUser;
@property(readonly) CloudProtocolsManager *cloudProtocolsManager; // @synthesize cloudProtocolsManager=_cloudProtocolsManager;
@property(readonly) CloudFolder *cloudFolder; // @synthesize cloudFolder=_cloudFolder;
- (void).cxx_destruct;
- (void)handlePersisitCommandForMe:(id)arg1;
- (void)handlePersisitCommandZaned:(id)arg1;
- (void)setApprovedCount:(unsigned int)arg1;
- (void)onSyncFolderAddFinish:(id)arg1 serverFolder:(id)arg2;
- (void)onActive;
- (void)onLogouted;
- (void)onWillLogout;
- (void)onLoginSuccess;
- (void)reachabilityChanged:(id)arg1;
- (void)dealloc;
- (id)initWithUin:(unsigned long)arg1;

@end

