//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComRootCell.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface UserInfoCell : ComRootCell
{
    UIImageView *greenView;
}

@property(retain, nonatomic) UIImageView *greenView; // @synthesize greenView;
- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

