//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtocolBase.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface VKeyProtocol : ProtocolBase
{
    NSString *_networkStatusName;
    NSString *_vkeyNormalQuality;
    NSString *_vkeyHighQuality;
    NSString *_serverCheck;
    NSArray *_expressHosts;
    NSString *_testFileCarrier;
    NSString *_testFileWifi;
    int _SQSongsNumber;
    NSString *_defaultHost;
    NSString *_guid;
    unsigned long long _uin;
    CDStruct_939ea9c7 _exclusiveLimit;
}

@property(nonatomic) unsigned long long uin; // @synthesize uin=_uin;
@property(copy, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(readonly, nonatomic) NSString *defaultHost; // @synthesize defaultHost=_defaultHost;
@property(readonly, nonatomic) CDStruct_939ea9c7 exclusiveLimit; // @synthesize exclusiveLimit=_exclusiveLimit;
@property(readonly, nonatomic) int SQSongsNumber; // @synthesize SQSongsNumber=_SQSongsNumber;
@property(readonly, nonatomic) NSString *testFileWifi; // @synthesize testFileWifi=_testFileWifi;
@property(readonly, nonatomic) NSString *testFileCarrier; // @synthesize testFileCarrier=_testFileCarrier;
@property(readonly, nonatomic) NSArray *expressHosts; // @synthesize expressHosts=_expressHosts;
@property(readonly, nonatomic) NSString *serverCheck; // @synthesize serverCheck=_serverCheck;
@property(readonly, nonatomic) NSString *vkeyHighQuality; // @synthesize vkeyHighQuality=_vkeyHighQuality;
@property(readonly, nonatomic) NSString *vkeyNormalQuality; // @synthesize vkeyNormalQuality=_vkeyNormalQuality;
@property(readonly, nonatomic) NSString *networkStatusName; // @synthesize networkStatusName=_networkStatusName;
- (void).cxx_destruct;
- (BOOL)useCustomQQ;
- (id)trimScheme:(id)arg1;
- (void)_parseVkey:(struct _xmlDoc *)arg1;
- (void)onParseXmlData:(struct _xmlDoc *)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (void)dealloc;
- (id)initWithNetworkStatusName:(id)arg1 uin:(unsigned long long)arg2;

@end

