//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasePPTVC.h"

#import "UIScrollViewDelegate.h"

@class GenericWebViewController, NSMutableArray, NSString, UIImageView, UIScrollView;

__attribute__((visibility("hidden")))
@interface WebPPTVC : BasePPTVC <UIScrollViewDelegate>
{
    UIScrollView *pagingScrollView;
    NSMutableArray *views;
    GenericWebViewController *_welcomeVC;
    UIImageView *_imageViewBackground;
}

@property(retain, nonatomic) UIImageView *imageViewBackground; // @synthesize imageViewBackground=_imageViewBackground;
@property(retain, nonatomic) NSMutableArray *views; // @synthesize views;
@property(retain, nonatomic) UIScrollView *pagingScrollView; // @synthesize pagingScrollView;
@property(retain, nonatomic) GenericWebViewController *welcomeVC; // @synthesize welcomeVC=_welcomeVC;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidAppear:(BOOL)arg1;
- (void)_fadeBgAndFinishSelf;
- (void)doHandlePushComming:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)requestToFinish;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

