//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIWebViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, UIWebView;

__attribute__((visibility("hidden")))
@interface WebViewJavascriptBridge : NSObject <UIWebViewDelegate>
{
    id <QMJsMessageDelegate> _jsMessageDelegate;
    NSMutableArray *_startupMessageQueue;
    NSMutableDictionary *_responseCallbacks;
    NSMutableDictionary *_messageHandlers;
    int _uniqueId;
    UIWebView *_webView;
    id <UIWebViewDelegate> _webViewDelegate;
    CDUnknownBlockType _messageHandler;
}

+ (void)enableLogging;
+ (id)bridgeForWebView:(id)arg1 webViewDelegate:(id)arg2 jsMsgDelegate:(id)arg3 handler:(CDUnknownBlockType)arg4;
+ (id)bridgeForWebView:(id)arg1 webViewDelegate:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (id)bridgeForWebView:(id)arg1 handler:(CDUnknownBlockType)arg2;
@property(copy, nonatomic) CDUnknownBlockType messageHandler; // @synthesize messageHandler=_messageHandler;
@property(nonatomic) __weak id <UIWebViewDelegate> webViewDelegate; // @synthesize webViewDelegate=_webViewDelegate;
@property(nonatomic) __weak UIWebView *webView; // @synthesize webView=_webView;
@property int uniqueId; // @synthesize uniqueId=_uniqueId;
@property(retain, nonatomic) NSMutableDictionary *messageHandlers; // @synthesize messageHandlers=_messageHandlers;
@property(retain, nonatomic) NSMutableDictionary *responseCallbacks; // @synthesize responseCallbacks=_responseCallbacks;
@property(retain, nonatomic) NSMutableArray *startupMessageQueue; // @synthesize startupMessageQueue=_startupMessageQueue;
@property(nonatomic) __weak id <QMJsMessageDelegate> jsMessageDelegate; // @synthesize jsMessageDelegate=_jsMessageDelegate;
- (void).cxx_destruct;
- (BOOL)checkUrlInWhiteList:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)_log:(id)arg1 json:(id)arg2;
- (id)_deserializeMessageJSON:(id)arg1;
- (id)_serializeMessage:(id)arg1;
- (void)_flushMessageQueue:(id)arg1;
- (void)_dispatchMessage:(id)arg1;
- (void)_queueMessage:(id)arg1;
- (void)_sendData:(id)arg1 responseCallback:(CDUnknownBlockType)arg2 handlerName:(id)arg3;
- (void)reset;
- (void)registerHandler:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)callHandler:(id)arg1 data:(id)arg2 responseCallback:(CDUnknownBlockType)arg3;
- (void)callHandler:(id)arg1 data:(id)arg2;
- (void)callHandler:(id)arg1;
- (void)send:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (void)send:(id)arg1;
- (void)removeDelegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

