//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SocketNetworkAdapterProtocol.h"

@class MemSig, NSData, NSString, SocketNetworkAdapter, WloginPkgHead;

@interface WloginTransport : NSObject <SocketNetworkAdapterProtocol>
{
    WloginPkgHead *pkgHead;
    unsigned char cReplyCode;
    NSString *crtCarrierName;
    SocketNetworkAdapter *socketAdapter;
    double timeOut;
    char sKey[16];
    char A1_Key[16];
    id transportDelegate;
    NSString *nowHost;
    unsigned short nowPort;
    struct timeval startTime;
    CDStruct_34f44c17 stInfo;
    unsigned short retryTimes;
    unsigned int dwTmpUin;
    unsigned int dwTmpAppid;
    unsigned int dwTmpRole;
    unsigned int dwTmpTime;
    MemSig *sTmpST;
    MemSig *sTmpA2;
    NSData *sTmpData;
    int dwTmpType;
}

@property(readonly) unsigned char cReplyCode; // @synthesize cReplyCode;
- (void)onSocket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)onSocketDidDisconnect:(id)arg1;
- (void)onSocket:(id)arg1 didDisconnectWithError:(id)arg2;
- (void)onSocket:(id)arg1 didReadData:(id)arg2 withTag:(long)arg3;
- (void)recvPkgError;
- (void)networkInfoReport:(short)arg1 andErrorStr:(id)arg2;
- (int)sendToWtloginTran:(unsigned int)arg1 andAppid:(unsigned int)arg2 andRole:(unsigned int)arg3 andTranType:(int)arg4 andSt:(id)arg5 andA2:(id)arg6 andData:(id)arg7 andSvrTime:(unsigned int)arg8;
- (void)disconnect;
- (int)connectToRemortServer;
- (void)dealloc;
- (BOOL)resetTransport;
- (id)initTranWithClientVer:(unsigned short)arg1 andPubNo:(unsigned int)arg2 andClientType:(unsigned int)arg3 andDelegate:(id)arg4;

@end

