//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol wwjsReportDataSource <NSObject>
- (int)configID;
- (NSString *)IDFA;
- (NSString *)distributeID;
- (NSString *)wwjsReportVUserID;
- (NSString *)wwjsReportGUID;
- (BOOL)wwjsNetworkAvailable;
- (BOOL)wwjsWifiAvailable;
- (BOOL)wwjsReportShouldReport;
- (short)wwjsReportCurrentNetworkType;
- (int)wwjsReportDeviceType;
- (NSString *)wwjsReportDeviceID;
- (double)wwjsReportUserQQ;
- (int)wwjsReportProductIdentifying;
- (NSString *)wwjsReportAppVersion;
@end

