//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WXSpeechRecognizerConnectionDelegate.h"
#import "WXSpeechRecognizerRecorderDelegate.h"

@class NSMutableArray, NSString, WXSpeechRecognizerConnection, WXSpeechRecognizerRecorder;

@interface WXVoiceSDK : NSObject <WXSpeechRecognizerRecorderDelegate, WXSpeechRecognizerConnectionDelegate>
{
    WXSpeechRecognizerConnection *_connection;
    WXSpeechRecognizerRecorder *_recorder;
    BOOL _isStart;
    BOOL _hasSpeak;
    BOOL _isFinish;
    float _sampleRate;
    int _maxResultCount;
    int _resultType;
    int _netType;
    float _outTime;
    int _uselessLength;
    BOOL _needCallbackCancel;
    id <WXVoiceDelegate> _delegate;
    float _silTime;
    NSMutableArray *_tmpVoiceDataArray;
    int _domain;
}

+ (void)releaseWXVoice;
+ (id)sharedWXVoice;
+ (id)allocWXVoice;
+ (id)alloc;
@property(retain, nonatomic) NSMutableArray *tmpVoiceDataArray; // @synthesize tmpVoiceDataArray=_tmpVoiceDataArray;
@property(nonatomic) float silTime; // @synthesize silTime=_silTime;
@property(nonatomic) id <WXVoiceDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)shouldSendData:(id)arg1 withUrlArgs:(id)arg2 delegate:(id)arg3;
- (float)calculateVolumnBytes:(void *)arg1 andLength:(unsigned long)arg2;
- (BOOL)isCompletedOnceWithVoiceDataBytes:(void *)arg1 andLength:(unsigned long)arg2;
- (int)byteFromChar16:(BOOL)arg1;
- (void)connectionDidCancel;
- (void)connectionResultArray:(id)arg1;
- (void)connectionErrorCode:(int)arg1 andHttpStatus:(int)arg2;
- (void)recorderRecordingBytes:(void *)arg1 length:(unsigned long)arg2;
- (void)finish;
- (void)cancelAll;
- (void)cancel;
- (BOOL)startSpeechRecognizer;
- (BOOL)startOnce;
- (BOOL)startOnceWithGrammarString:(id)arg1 andType:(int)arg2;
- (void)canRecord;
- (void)setResultType:(int)arg1;
- (void)setMaxResultCount:(int)arg1;
- (void)setAppID:(id)arg1;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (void)dealloc;
- (id)init;
@property(nonatomic) int domain; // @synthesize domain=_domain;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

