//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ChannelCreator, NSDate, ShareObject;

__attribute__((visibility("hidden")))
@interface ZanMessageObject : NSObject
{
    ChannelCreator *_zanPerson;
    NSDate *_dateAndTime;
    ShareObject *_shareObj;
}

+ (id)translateFromJsonData:(id)arg1;
@property(retain, nonatomic) ShareObject *shareObj; // @synthesize shareObj=_shareObj;
@property(retain, nonatomic) NSDate *dateAndTime; // @synthesize dateAndTime=_dateAndTime;
@property(retain, nonatomic) ChannelCreator *zanPerson; // @synthesize zanPerson=_zanPerson;
- (void).cxx_destruct;

@end

